'(
  (ac-tex-ref . [(2) nil "auto-complete for tex-mode \\ref and \\cite labels" single ((:url . "http://user42.tuxfamily.org/ac-tex-ref/index.html")) "user42"])
  (accjournal . [(6) nil "double entry journal accounting" single ((:url . "http://user42.tuxfamily.org/accjournal/index.html")) "user42"])
  (align-let . [(12) nil "align expressions in a lisp \"let\"" single ((:url . "http://user42.tuxfamily.org/align-let/index.html")) "user42"])
  (arc-lzh-exe . [(7) nil "archive-mode support for LHa self-extracting .exe" single ((:url . "http://user42.tuxfamily.org/arc-lzh-exe/index.html")) "user42"])
  (areabrowse . [(3) nil "browse diku mud .are area files" single ((:url . "http://user42.tuxfamily.org/areabrowse/index.html")) "user42"])
  (aumix-mode . [(7) nil "run the aumix program in a buffer" single ((:url . "http://user42.tuxfamily.org/aumix-mode/index.html")) "user42"])
  (bytecomp-simplify . [(18) nil "byte compile warnings for simplifications" single ((:url . "http://user42.tuxfamily.org/bytecomp-simplify/index.html")) "user42"])
  (checkdoc-autoload . [(2) nil "check for various autoload cookies" single ((:url . "http://user42.tuxfamily.org/checkdoc-autoload/index.html")) "user42"])
  (checkdoc-batch . [(6) nil "batch report of M-x checkdoc things" single ((:url . "http://user42.tuxfamily.org/checkdoc-batch/index.html")) "user42"])
  (checkdoc-keywords . [(6) nil "check for known values in Keywords header" single ((:url . "http://user42.tuxfamily.org/checkdoc-keywords/index.html")) "user42"])
  (checkdoc-url-buttonize . [(1) nil "check URL `' linking in docstrings" single ((:url . "http://user42.tuxfamily.org/checkdoc-url-buttonize/index.html")) "user42"])
  (cl-loop-aplist . [(4) nil "cl loop macro alist and plist support" single ((:url . "http://user42.tuxfamily.org/cl-loop-aplist/index.html")) "user42"])
  (compilation-always-kill . [(5) nil "kill compilation without prompting" single ((:url . "http://user42.tuxfamily.org/compilation-always-kill/index.html")) "user42"])
  (compilation-emacs21-batch . [(4) nil "error regexps for emacs21 byte compiler" single ((:url . "http://user42.tuxfamily.org/compilation-emacs21-batch/index.html")) "user42"])
  (compilation-ledger . [(1) nil "error regexps for ledger" single ((:url . "http://user42.tuxfamily.org/compilation-ledger/index.html")) "user42"])
  (compilation-onewin . [(3) nil "whole-frame window for compile buffer" single ((:url . "http://user42.tuxfamily.org/compilation-onewin/index.html")) "user42"])
  (compilation-perl . [(13) nil "extra error regexps for Perl" single ((:url . "http://user42.tuxfamily.org/compilation-perl/index.html")) "user42"])
  (compilation-recenter-end . [(6) nil "compilation-mode window recentre" single ((:url . "http://user42.tuxfamily.org/compilation-recenter-end/index.html")) "user42"])
  (compilation-weblint . [(6) nil "error regexps for weblint" single ((:url . "http://user42.tuxfamily.org/compilation-weblint/index.html")) "user42"])
  (compile-command-default . [(12) nil "establish a default for M-x compile" single ((:url . "http://user42.tuxfamily.org/compile-command-default/index.html")) "user42"])
  (completion-ignored-build . [(11) nil "some built completion-ignored-extensions" single ((:url . "http://user42.tuxfamily.org/completion-ignored-build/index.html")) "user42"])
  (copyright-both-ends . [(4) nil "update copyright at start and end of file" single ((:url . "http://user42.tuxfamily.org/copyright-both-ends/index.html")) "user42"])
  (diff-save-buffer . [(13) nil "default filename when saving a diff." single ((:url . "http://user42.tuxfamily.org/diff-save-buffer/index.html")) "user42"])
  (dired-visit-history . [(3) nil "add dired visited files to find-file history" single ((:url . "http://user42.tuxfamily.org/dired-visit-history/index.html")) "user42"])
  (do-not-edit . [(14) nil "read-only buffer for generated files" single ((:url . "http://user42.tuxfamily.org/do-not-edit/index.html")) "user42"])
  (elisp-docstring-preview . [(4) nil "preview Emacs Lisp docstring" single ((:url . "http://user42.tuxfamily.org/elisp-docstring-preview/index.html")) "user42"])
  (ffap-I-option . [(1) nil "recognise -I/usr/include/foo" single ((:url . "http://user42.tuxfamily.org/ffap-I-option/index.html")) "user42"])
  (ffap-gcc-path . [(8) nil "get gcc's include path for ffap-c-path" single ((:url . "http://user42.tuxfamily.org/ffap-gcc-path/index.html")) "user42"])
  (ffap-href . [(4) nil "find href URL/link anywhere in the tag" single ((:url . "http://user42.tuxfamily.org/ffap-href/index.html")) "user42"])
  (ffap-include-start . [(10) nil "recognise C #include when at start of line" single ((:url . "http://user42.tuxfamily.org/ffap-include-start/index.html")) "user42"])
  (ffap-makefile-vars . [(4) nil "find file with makefile variables expanded" single ((:url . "http://user42.tuxfamily.org/ffap-makefile-vars/index.html")) "user42"])
  (ffap-mml . [(8) nil "find Gnus message MML attached file at point" single ((:url . "http://user42.tuxfamily.org/ffap-mml/index.html")) "user42"])
  (ffap-perl-module . [(23) nil "find perl module at point with ffap" single ((:url . "http://user42.tuxfamily.org/ffap-perl-module/index.html")) "user42"])
  (ffap-pod-F . [(5) nil "follow Perl pod F<filename>" single ((:url . "http://user42.tuxfamily.org/ffap-pod-F/index.html")) "user42"])
  (ffap-rfc-directories . [(8) nil "look for RFCs in local directories too" single ((:url . "http://user42.tuxfamily.org/ffap-rfc-directories/index.html")) "user42"])
  (ffap-rfc-space . [(10) nil "recognise RFC with a space, like \"RFC 1234\"" single ((:url . "http://user42.tuxfamily.org/ffap-rfc-space/index.html")) "user42"])
  (filladapt-pat . [(5) nil "add or remove some filladapt patterns" single ((:url . "http://user42.tuxfamily.org/filladapt-pat/index.html")) "user42"])
  (formfeed-hline . [(4) nil "display formfeed with horizontal line" single ((:url . "http://user42.tuxfamily.org/formfeed-hline/index.html")) "user42"])
  (gtk-look . [(26) nil "lookup Gtk and Gnome documentation." single ((:url . "http://user42.tuxfamily.org/gtk-look/index.html")) "user42"])
  (gutenberg-coding . [(14) nil "coding system for Project Gutenberg EBooks." single ((:url . "http://user42.tuxfamily.org/gutenberg-coding/index.html")) "user42"])
  (help-xref-elfiles . [(4) nil "buttonize foo.el and .emacs filenames in docstrings" single ((:url . "http://user42.tuxfamily.org/help-xref-elfiles/index.html")) "user42"])
  (html-coding . [(12) nil "coding system from meta in html files (for Emacs 21)" single ((:url . "http://user42.tuxfamily.org/html-coding/index.html")) "user42"])
  (html-sizes . [(14) nil "maintain file sizes shown for html links" single ((:url . "http://user42.tuxfamily.org/html-sizes/index.html")) "user42"])
  (html-smarter-href . [(1) nil "smarter html-href-anchor reading" single ((:url . "http://www.geocities.com/user42_kevin/html-smarter-href/")) "user42"])
  (imagetext . [(10) nil "show text parts of image files" single ((:url . "http://user42.tuxfamily.org/imagetext/index.html")) "user42"])
  (info-lookmore . [(5) nil "more things for info-look.el" single ((:url . "http://user42.tuxfamily.org/info-lookmore/index.html")) "user42"])
  (ispell-stopwords . [(8) nil "use perl POD \"=for stopwords\" in ispell" single ((:url . "http://user42.tuxfamily.org/ispell-stopwords/index.html")) "user42"])
  (jka-compr-dictzip . [(1) nil "dictzip .dz for jka-compr" single ((:url . "http://user42.tuxfamily.org/jka-compr-dictzip/index.html")) "user42"])
  (localedef-overlay . [(3) nil "mode for glibc locale definition files" single ((:url . "http://user42.tuxfamily.org/localedef-overlay/index.html")) "user42"])
  (mailcap-mode . [(3) nil "mailcap file editing mode" single ((:url . "http://user42.tuxfamily.org/mailcap-mode/index.html")) "user42"])
  (make-mode-fillindent . [(4) nil "filling indented makefile comments" single ((:url . "http://user42.tuxfamily.org/make-mode-fillindent/index.html")) "user42"])
  (makeinfo-info . [(8) nil "use Info-mode with makeinfo-buffer." single ((:url . "http://user42.tuxfamily.org/makeinfo-info/index.html")) "user42"])
  (man-completion . [(33) nil "completion for M-x man" single ((:url . "http://user42.tuxfamily.org/man-completion/index.html")) "user42"])
  (man-preview . [(9) nil "preview nroff man file source" single ((:url . "http://user42.tuxfamily.org/man-preview/index.html")) "user42"])
  (mine-sweeper-auto . [(6) nil "automated mine sweeping for mine-sweeper.el" single ((:url . "http://user42.tuxfamily.org/mine-sweeper-auto/index.html")) "user42"])
  (mo-mode . [(13) nil "view and edit gettext .mo message files" single ((:url . "http://user42.tuxfamily.org/mo-mode/index.html")) "user42"])
  (nobreak-fade . [(8) nil "some functions for `fill-nobreak-predicate'" single ((:url . "http://user42.tuxfamily.org/nobreak-fade/index.html")) "user42"])
  (nroff-filladapt . [(4) nil "nroff comment prefixes for filladapt" single ((:url . "http://user42.tuxfamily.org/nroff-filladapt/index.html")) "user42"])
  (oeis . [(5) nil "helpers for the Online Encyclopedia of Integer Sequences" single ((:url . "http://user42.tuxfamily.org/oeis-el/index.html")) "user42"])
  (parasep . [(4) nil "more paragraph separators" single ((:url . "http://user42.tuxfamily.org/parasep/index.html")) "user42"])
  (pcf2bdf . [(13) nil "view .pcf compiled font files as bdf" single ((:url . "http://user42.tuxfamily.org/pcf2bdf/index.html")) "user42"])
  (perl-env-substitute . [(1) nil "Perl style $ENV{VARNAME} in substitute-in-filename" single ((:url . "http://user42.tuxfamily.org/perl-env-substitute/index.html")) "user42"])
  (perl-pod-coding . [(7) nil "coding system from =encoding in perl files" single ((:url . "http://user42.tuxfamily.org/perl-pod-coding/index.html")) "user42"])
  (perl-pod-gt . [(18) nil "helpers for Perl POD <> markup" single ((:url . "http://user42.tuxfamily.org/perl-pod-gt/index.html")) "user42"])
  (perl-pod-preview . [(16) nil "preview perl pod documentation" single ((:url . "http://user42.tuxfamily.org/perl-pod-preview/index.html")) "user42"])
  (perl-quote . [(4) nil "helpers for Perl quoted strings" single ((:url . "http://user42.tuxfamily.org/perl-quote/index.html")) "user42"])
  (perl-use-utf8-coding . [(4) nil "coding system from \"use utf8\" in perl code" single ((:url . "http://user42.tuxfamily.org/perl-use-utf8-coding/index.html")) "user42"])
  (pst-format . [(7) nil "view perl Storable files as human readable text" single ((:url . "http://user42.tuxfamily.org/pst-format/index.html")) "user42"])
  (quick-yes . [(8) nil "M-y to answer \"yes\" to `yes-or-no-p'." single ((:url . "http://user42.tuxfamily.org/quick-yes/index.html")) "user42"])
  (scroll-1 . [(8) nil "bind j and k to scroll the window up and down" single ((:url . "http://user42.tuxfamily.org/scroll-1/index.html")) "user42"])
  (sh-autoconf . [(7) nil "autoconf flavour for sh-mode" single ((:url . "http://user42.tuxfamily.org/sh-autoconf/index.html")) "user42"])
  (sqlite-dump . [(9) nil "view dump of sqlite database file" single ((:url . "http://user42.tuxfamily.org/sqlite-dump/index.html")) "user42"])
  (startup-file-name-history . [(4) nil "command line files into file-name-history" single ((:url . "http://user42.tuxfamily.org/startup-file-name-history/index.html")) "user42"])
  (tcd-format . [(7) nil "view XTide .tcd tide constituent database files" single ((:url . "http://user42.tuxfamily.org/tcd-format/index.html")) "user42"])
  (tex-math-preview . [(15) nil "preview TeX math expressions." single ((:url . "http://user42.tuxfamily.org/tex-math-preview/index.html")) "user42"])
  (texinfo-nobreak . [(6) nil "texinfo line break workarounds" single ((:url . "http://user42.tuxfamily.org/texinfo-nobreak/index.html")) "user42"])
  (texinfo-warn . [(8) nil "warn about tabs and more in texinfo" single ((:url . "http://user42.tuxfamily.org/texinfo-warn/index.html")) "user42"])
  (tty-format . [(9) nil "text file backspacing and ANSI SGR as faces" single ((:url . "http://user42.tuxfamily.org/tty-format/index.html")) "user42"])
  (unicode-disp . [(10) nil "display-table fallbacks for some unicode chars" single ((:url . "http://user42.tuxfamily.org/unicode-disp/index.html")) "user42"])
  (upstr . [(3) nil "up-list out of a string or TeX maths too" single ((:url . "http://user42.tuxfamily.org/upstr/index.html")) "user42"])
  (variable-at-point-tick . [(3) nil "variable-at-point on a 'foo (for Emacs 23)" single ((:url . "http://user42.tuxfamily.org/variable-at-point-tick/index.html")) "user42"])
  (weblint . [(5) nil "run the weblint program" single ((:url . "http://user42.tuxfamily.org/weblint/index.html")) "user42"])
  (wx-look . [(5) nil "lookup wxWidgets functions in its manual." single ((:url . "http://user42.tuxfamily.org/wx-look/index.html")) "user42"])
  (xml-coding . [(8) nil "coding system from tag in xml files (for Emacs 21)" single ((:url . "http://user42.tuxfamily.org/xml-coding/index.html")) "user42"])
  (xtide . [(24) nil "XTide display in Emacs" single ((:url . "http://user42.tuxfamily.org/xtide/index.html")) "user42"])
 )
