'(
  (fit-frame . [(20130723 2311) nil "Resize a frame.  In particular, fit a frame to its buffers. [wiki]" single "melpa"])
  (flymake-puppet . [(20130731 2203) ((flymake-easy (0 9))) "An Emacs flymake handler for syntax-checking puppet using puppet-lint [github]" single "melpa"])
  (org-pandoc . [(20130729 2050) nil "Export from Org using Pandoc [github]" tar "melpa"])
  (palimpsest . [(20130731 1821) nil "Various deletion strategies when editing [github]" single "melpa"])
  (perl-completion . [(20090528 1536) nil "No description available. [github]" single "melpa"])
  (py-import-check . [(20130802 1150) nil "Finds the unused python imports using importchecker [github]" single "melpa"])
  (vc-check-status . [(20130730 1656) nil "Warn you when quitting emacs and leaving repo dirty. [github]" tar "melpa"])
  (wgrep-ag . [(20130725 1831) ((wgrep (2 1 5))) "Writable ag buffer and apply the changes to files [github]" single "melpa"])
  (cubicle-mode . [(0 1) nil "Cubicle major mode for emacs" single "marmalade"])
  (pickup . [(0 0 3) nil "pickup file. " single "marmalade"])
 )
