'(
  (java-file-create . [(1 0) nil "automatically insert contents of empty java files" single "marmalade"])
  (isgd . [(20130927) nil "Shorten URLs using the isgd.com shortener service" single "marmalade"])
  (whitespace-cleanup-mode . [(0 4) nil "Intelligently call whitespace-cleanup on save" single "marmalade"])
  (highlight-current-line . [(0 57) nil "highlight line where the cursor is." single "marmalade"])
  (hl-spotlight . [(0) nil "Extension of hl-line.el to spotlight current few lines." single "marmalade"])
  (f . [(0 11 0) ((s (1 7 0)) (dash (2 2 0))) "Modern API for working with files and directories" single "marmalade"])
  (shell-pop . [(0 2) nil "helps you to use shell easily on Emacs. Only one key action to work." single "marmalade"])
  (skewer-mode . [(1 5 3) ((simple-httpd (1 4 0)) (js2-mode (20090723))) "live browser JavaScript, CSS, and HTML interaction" tar "marmalade"])
  (elfeed-web . [(1 0 1) ((simple-httpd (1 4 3)) (elfeed (1 0 1)) (emacs (24 1))) "web interface to Elfeed" tar "marmalade"])
  (elfeed . [(1 0 1) ((emacs (24 1))) "an Emacs web feed reader" tar "marmalade"])
  (simple-httpd . [(1 4 4) nil "pure elisp HTTP server" single "marmalade"])
  (wonderland . [(0 1 1) ((dash (2 0 0)) (dash-functional (1 0 0)) (multi (2 0 0)) (emacs (24))) "declarative configuration for Emacsen -*- lexical-binding: t -*-" single "marmalade"])
  (ps-ccrypt . [(1 10) nil "reading/writing/loading encrypted files" tar "marmalade"])
  (jujube-theme . [(0 1) nil "Pastel theme loosely based on jellybeans" single "marmalade"])
  (helm-helm-commands . [(0 2) ((helm (1 5 4))) "List all helm commands with helm" single "marmalade"])
  (evil-indent-textobject . [(0 2) ((evil (0))) "evil textobjects based on indentation" single "marmalade"])
  (multi . [(2 0 0) ((emacs (24))) "Clojure-style multi-methods for emacs lisp -*- lexical-binding: t -*-" single "marmalade"])
  (gerrit-download . [(0 2) ((magit (20130828 1540))) "Show gerrit reviews in a diff buffer." single "marmalade"])
  (waher-theme . [(20130917 7) ((emacs (24 1))) "Emacs 24 theme based on waher for st2 by dduckster" single "marmalade"])
  (comint-better-defaults . [(1 0) nil "better defaults for comint-derived modes" single "marmalade"])
  (winpoint-ignore-dired . [(1 1) ((winpoint (1 0))) "Have winpoint ignore dired-mode buffers" single "marmalade"])
  (tox . [(0 1) nil "Launch current python test with tox." single "marmalade"])
  (insert-shebang . [(0 9 2) nil "Inserts shebang line automatically" tar "marmalade"])
  (smart-whitespace-comment-fixup . [(1 0) nil "Enables advice around yanking/killing lines that auto-indents and formats properly" single "marmalade"])
  (figlet . [(289) nil "banner generator" single "marmalade"])
  (smtpmail-multi . [(0 5) nil "Use different smtp servers for sending mail" single "marmalade"])
  (tronesque-theme . [(1 3) nil "Color Theme based on Tron universe." single "marmalade"])
  (openstack-cgit-browse-file . [(0 2) nil "Browse the current file in OpenStack cgit" single "marmalade"])
  (flycheck-cask . [(0 1) ((flycheck (0 14)) (dash (2 0 0)) (f (0 6 0))) "Cask support in Flycheck -*- lexical-binding: t; -*-" single "marmalade"])
  (dash-functional . [(1 0 0) ((dash (2 0 0)) (emacs (24))) "Collection of useful combinators for Emacs Lisp  -*- lexical-binding: t -*-" single "marmalade"])
  (pkg-info . [(0 1) ((dash (1 6 0)) (s (1 6 0))) "Information about packages       -*- lexical-binding: t; -*-" single "marmalade"])
  (aok . [(0 1) nil "various useful ways to do `multi-occur'" single "marmalade"])
  (magit-tramp . [(0 1 0) ((magit (1 2 0))) "git method for TRAMP" single "marmalade"])
  (helm-recoll . [(20130905 2330) ((helm (1 5 4))) "helm interface for the recoll desktop search tool." single "marmalade"])
  (god-mode . [(2 7 2) nil "God-like command entering minor mode" single "marmalade"])
  (heroku-theme . [(1 1 0) nil "Heroku color theme" single "marmalade"])
  (wisp-mode . [(0 1 2) nil "Major mode for editing wisp: Whitespace-to-Lisp" single "marmalade"])
  (tsql . [(1 0) nil "customizes sql.el for T-SQL" single "marmalade"])
  (helm-delicious . [(1 1) nil "helm extensions for delicious bookmarks" single "marmalade"])
  (wedge-ws . [(0 1 1) nil "Wedge whitespace between columns in text" tar "marmalade"])
  (sparkline . [(0 3 0) nil "Make sparkline images from a list of numbers" single "marmalade"])
  (flymake-puppet . [(1 0 0) ((flymake-easy (0 9))) "An Emacs flymake handler for syntax-checking puppet using puppet-lint" single "marmalade"])
  (palimpsest . [(0 8) nil "Various deletion strategies when editing" single "marmalade"])
  (py-import-check . [(0 2) nil "Finds the unused python imports using importchecker" single "marmalade"])
  (cubicle-mode . [(0 1) nil "Cubicle major mode for emacs" single "marmalade"])
  (pickup . [(0 0 3) nil "pickup file. " single "marmalade"])
  (fit-frame . [(0) nil "Resize a frame.  In particular, fit a frame to its buffers." single "marmalade"])
  (zone-matrix . [(0 0 1) nil "Matrix themed Zone mode" tar "marmalade"])
  (discord . [(0 5) nil "Discordian dates for calendar" single "marmalade"])
  (osx-pseudo-daemon . [(1 0) nil "Daemon mode that plays nice with OSX." single "marmalade"])
 )
