'(
  (ac-slime . [(0 5) nil "An auto-complete source using slime completions" single "marmalade"])
  (scheme-here . [(0 3) nil "cmuscheme extension for multiple inferior processes" single "marmalade"])
  (awk-it . [(0 77) nil "Run AWK interactively on region!" single "marmalade"])
  (page-break-lines . [(0 8) nil "Display ugly ^L page breaks as tidy horizontal lines" single "marmalade"])
  (clues-theme . [(20130908 801) ((emacs (24 0))) "an Emacs 24 theme which may well be fully awesome..." single "marmalade"])
  (purple-haze-theme . [(20130930 36) ((emacs (24 0))) "an overtly purple color theme for Emacs24." single "marmalade"])
  (paste-kde . [(0 4) ((web (0 3 6))) "paste text to KDE's pastebin service" single "marmalade"])
  (git-gutter+ . [(0 1) ((git-commit-mode (1 0))) "Manage Git hunks straight from the buffer" single "marmalade"])
  (frame-restore . [(0 4) ((dash (1 2)) (f (0 11)) (emacs (24 1))) "Restore Emacs frame -*- lexical-binding: t; -*-" single "marmalade"])
  (ample-theme . [(0 2 4) nil "Calm Dark Theme for Emacs " single "marmalade"])
  (emmet-mode . [(1 0 5) nil "Unofficial Emmet's support for emacs" single "marmalade"])
  (web-mode . [(7 0 21) nil "major mode for editing html templates -*- coding: utf-8 -*-" single "marmalade"])
  (processing-mode . [(1 2 1) nil "Major mode for Processing 2.0" single "marmalade"])
  (git-gutter-fringe+ . [(0 0 2) ((git-gutter+ (0 1)) (fringe-helper (20130519 1641))) "Fringe version of git-gutter+.el" single "marmalade"])
  (remember-theme . [(20130807 1251) nil "Remembers the last theme in use and re-loads for the next session." single "marmalade"])
  (org-trello . [(0 2 2) ((org (8 0 7)) (dash (1 5 0)) (request (0 2 0)) (cl-lib (0 3 0)) (json (1 2)) (elnode (0 9 9 7 6)) (esxml (0 3 0)) (s (1 7 0)) (kv (0 0 17))) "Org minor mode to synchronize with trello" tar "marmalade"])
  (sourcetalk . [(1 1 0) ((request (0 2 0))) "SourceTalk (http://sourcetalk.net) plugin for Emacs" single "marmalade"])
  (jb-misc-macros . [(0 4) ((macro-utils (1 0))) "Miscellaneous macros" single "marmalade"])
  (syslog-mode . [(2 1) ((hide-lines (20130623))) "Major-mode for viewing log files" single "marmalade"])
  (php-extras . [(1 0 0 20130923) ((php-mode (1 5 0))) "Extra features for `php-mode'" tar "marmalade"])
  (flymake-less . [(0 3) ((less-css-mode (0 15))) "Flymake handler for LESS stylesheets (lesscss.org)" single "marmalade"])
  (org-journal . [(1 4 4) nil "a simple org-mode based journaling mode" single "marmalade"])
  (desktop-registry . [(1 1 0) nil "Keep a central registry of desktop files -*- lexical-binding: t -*-" single "marmalade"])
  (show-marks . [(0 4) ((fm (1 0))) "Navigate and visualize the mark-ring" single "marmalade"])
  (kmacro-decision . [(1 5) ((el-x (1 0)) (jb-misc-macros (0 2))) "Add conditional branching to keyboard macros" single "marmalade"])
  (evil-leader . [(0 4 1) ((evil (0))) "let there be <leader>" single "marmalade"])
  (simple-call-tree+ . [(1 3) nil "Extensions to simple-call-tree" single "marmalade"])
  (noflet . [(0 0 10) nil "locally override functions" single "marmalade"])
  (org-dotemacs . [(0 3) ((org (7 9 3)) (cl-lib (1 0))) "Store your emacs config as an org file, and choose which bits to load." single "marmalade"])
  (ag . [(0 27) nil "A front-end for ag ('the silver searcher'), the C ack replacement." single "marmalade"])
  (groovy-mode . [(201203310931) nil "Groovy mode derived mode" single "marmalade"])
  (rubocop . [(0 3) ((dash (1 0 0))) "An Emacs interface for RuboCop" single "marmalade"])
  (flymake-elixir . [(0 5) nil "A flymake handler for elixir-mode .ex files.     " single "marmalade"])
  (ibuffer-vc . [(0 7) ((cl-lib (0 2))) "Group ibuffer's list by VC project, or show VC status" single "marmalade"])
  (psgml . [(1 4 1) nil "Lennart Staflin's Psgml package, with Elisp syntax and sgml-validate fixed for Emacsen >=24." tar "marmalade"])
  (smartparens . [(1 5) ((cl-lib (0 1)) (dash (1 1 0))) "Automatic insertion, wrapping and paredit-like navigation with user defined pairs." tar "marmalade"])
  (grapnel . [(0 5 3) nil "HTTP request lib with flexible callback dispatch" single "marmalade"])
  (evil . [(1 0 7) ((undo-tree (0 5 1))) "Extensible Vi layer for Emacs." tar "marmalade"])
  (rbenv . [(0 0 3) nil "Emacs integration for rbenv" single "marmalade"])
  (creole . [(1 0 3) ((noflet (0 0 3)) (kv (0 0 17))) "A parser for the Creole Wiki language" single "marmalade"])
  (robe . [(0 7 6) ((inf-ruby (2 3 0))) "Code navigation, documentation lookup and completion for Ruby" tar "marmalade"])
  (evil-nerd-commenter . [(1 2 4) nil "Comment/uncomment lines efficiently. Like Nerd Commenter in Vim" tar "marmalade"])
  (cpputils-cmake . [(0 4 0) nil "Easy real time C++ syntax check and intellisense if you use CMake." tar "marmalade"])
  (flycheck . [(0 14 1) ((s (1 6 0)) (dash (1 6 0)) (f (0 5 0)) (cl-lib (0 1)) (emacs (24 1))) "On-the-fly syntax checking (Flymake done right)" tar "marmalade"])
  (elpy . [(1 1) ((auto-complete (1 4)) (fuzzy (0 1)) (yasnippet (0 8)) (virtualenv (1 2)) (highlight-indentation (0 5 0)) (find-file-in-project (3 2)) (idomenu (0 1)) (nose (0 1 1)) (iedit (0 97))) "Emacs Lisp Python Environment" tar "marmalade"])
  (auto-indent-mode . [(0 108) nil "Auto indent Minor mode" single "marmalade"])
  (flymake-coffee . [(0 12) ((flymake-easy (0 1))) "A flymake handler for coffee script" single "marmalade"])
  (bug-reference-github . [(0 2 0) nil "Automatically set `bug-reference-url-format' in Github repositories." single "marmalade"])
  (less-css-mode . [(0 17) nil "Major mode for editing LESS CSS files (lesscss.org)" single "marmalade"])
  (lispyscript-mode . [(0 3 0) nil "Major mode for LispyScript code." single "marmalade"])
  (json-mode . [(1 1 0) nil "Major mode for editing JSON files" single "marmalade"])
  (dash . [(2 2 0) nil "A modern list library for Emacs" single "marmalade"])
  (git-commit-mode . [(0 13) nil "Major mode for editing git commit messages -*- lexical-binding: t; -*-" single "marmalade"])
  (s . [(1 8 0) nil "The long lost Emacs string manipulation library." single "marmalade"])
  (exec-path-from-shell . [(1 6) nil "Get environment variables such as $PATH from the shell" single "marmalade"])
  (ac-nrepl . [(0 20) ((nrepl (0 1)) (auto-complete (1 4))) "auto-complete sources for Clojure using nrepl completions" single "marmalade"])
  (ruby-test-mode . [(1 7) ((ruby-mode (1 0))) "Minor mode for Behaviour and Test Driven" single "marmalade"])
  (fill-column-indicator . [(1 85) nil "Graphically indicate the fill column" single "marmalade"])
  (nrepl . [(0 1 8) ((clojure-mode (2 0 0)) (cl-lib (0 3))) "Client for Clojure nREPL" single "marmalade"])
  (android-mode . [(0 2 4) nil "Minor mode for Android application development" single "marmalade"])
  (ack-and-a-half . [(1 2 0) nil "Yet another front-end for ack" single "marmalade"])
  (ido-ubiquitous . [(2 8) ((emacs (24 1))) "Use ido (nearly) everywhere." single "marmalade"])
  (langtool . [(1 2 1) nil "Grammar check utility using LanguageTool" single "marmalade"])
  (yaml-mode . [(0 0 9) nil "Major mode for editing YAML files" single "marmalade"])
 )
