'(
  (f . [(0 6 0) ((s (1 6 1)) (dash (1 5 0))) "Modern API for working with files and directories" single "marmalade"])
  (aok . [(0 1) nil "various useful ways to do `multi-occur'" single "marmalade"])
  (magit-tramp . [(0 1 0) ((magit (1 2 0))) "git method for TRAMP" single "marmalade"])
  (tronesque-theme . [(1 2) nil "Color Theme based on Tron universe." single "marmalade"])
  (helm-recoll . [(20130815 0) ((helm (20130806 1505))) "helm interface for the recoll desktop search tool." single "marmalade"])
  (god-mode . [(2 7 0) nil "God-like command entering minor mode" single "marmalade"])
  (heroku-theme . [(1 1 0) nil "Heroku color theme" single "marmalade"])
  (wisp-mode . [(0 1 1) nil "Major mode for editing wisp: Whitespace-to-Lisp" single "marmalade"])
  (tsql . [(1 0) nil "customizes sql.el for T-SQL" single "marmalade"])
  (helm-delicious . [(1 1) nil "helm extensions for delicious bookmarks" single "marmalade"])
  (wedge-ws . [(0 1 1) nil "Wedge whitespace between columns in text" tar "marmalade"])
  (sparkline . [(0 3 0) nil "Make sparkline images from a list of numbers" single "marmalade"])
  (flymake-puppet . [(1 0 0) ((flymake-easy (0 9))) "An Emacs flymake handler for syntax-checking puppet using puppet-lint" single "marmalade"])
  (palimpsest . [(0 8) nil "Various deletion strategies when editing" single "marmalade"])
  (py-import-check . [(0 2) nil "Finds the unused python imports using importchecker" single "marmalade"])
  (cubicle-mode . [(0 1) nil "Cubicle major mode for emacs" single "marmalade"])
  (pickup . [(0 0 3) nil "pickup file. " single "marmalade"])
  (fit-frame . [(0) nil "Resize a frame.  In particular, fit a frame to its buffers." single "marmalade"])
  (discord . [(0 5) nil "Discordian dates for calendar" single "marmalade"])
 )
