'(
  (abl-mode . [(0 9 0) nil "Python TDD minor mode" single "marmalade"])
  (ac-ja . [(0 0 1) nil "auto-complete-mode source for Japanese" single "marmalade"])
  (ac-nrepl . [(0 21) ((cider (0 1)) (auto-complete (1 4))) "auto-complete sources for Clojure using nrepl completions" single "marmalade"])
  (ac-slime . [(0 5) nil "An auto-complete source using slime completions" single "marmalade"])
  (ace-jump-mode . [(2 0 0 0) nil "a quick cursor location minor mode for emacs" single "marmalade"])
  (ack-and-a-half . [(1 2 0) nil "Yet another front-end for ack" single "marmalade"])
  (ag . [(0 42) nil "A front-end for ag ('the silver searcher'), the C ack replacement." single "marmalade"])
  (align-cljlet . [(0 3) ((clojure-mode (1 11 5))) "Space align various Clojure forms" single "marmalade"])
  (ample-theme . [(0 12) ((color-theme (6 5 5))) "Calm Dark Theme for Emacs" single "marmalade"])
  (anaphora . [(1 0 0) nil "anaphoric macros providing implicit temp variables" single "marmalade"])
  (android-mode . [(0 4 0) nil "Minor mode for Android application development" single "marmalade"])
  (auto-indent-mode . [(0 126) nil "Auto indent Minor mode" single "marmalade"])
  (awk-it . [(0 77) nil "Run AWK interactively on region!" single "marmalade"])
  (babcore . [(0 0 5) nil "Core Emacs configuration. This should be the minimum in every emacs config." single "marmalade"])
  (back-button . [(0 6 6) ((nav-flash (1 0 0)) (smartrep (0 0 3)) (ucs-utils (0 7 2)) (persistent-soft (0 8 8)) (pcache (0 2 3))) "Visual navigation through mark rings" single "marmalade"])
  (browse-kill-ring . [(2 0 0) nil "interactively insert items from kill-ring" single "marmalade"])
  (browse-url-dwim . [(0 6 6) ((string-utils (0 3 2))) "Context-sensitive external browse URL or Internet search" single "marmalade"])
  (buffer-move . [(0 6 1) nil "" single "marmalade"])
  (buffer-utils . [(0 1 0) nil "Buffer-manipulation utility functions" single "marmalade"])
  (bug-reference-github . [(0 2 0) nil "Automatically set `bug-reference-url-format' in Github repositories." single "marmalade"])
  (butler . [(0 2 0) ((deferred (3 1)) (json (1 2))) "Emacs client for Jenkins" tar "marmalade"])
  (button-lock . [(1 0 0) nil "Clickable text defined by regular expression" single "marmalade"])
  (c-eldoc . [(0 7) nil "helpful description of the arguments to C functions" single "marmalade"])
  (calfw-gcal . [(0 0 3) nil "edit Google calendar for calfw.el." single "marmalade"])
  (charmap . [(0 0 1) nil "Unicode table for Emacs" single "marmalade"])
  (chicken-scheme . [(1 3 0) nil "Scheme-mode extensions for Chicken Scheme" single "marmalade"])
  (circe . [(1 5) ((lui (1 5)) (lcs (1 5))) "Client for IRC in Emacs" tar "marmalade"])
  (clips-mode . [(0 7) nil "Major mode for editing CLIPS code and REPL" tar "marmalade"])
  (clj-refactor . [(0 13 0) ((s (1 8 0)) (dash (2 4 0)) (yasnippet (0 6 1)) (paredit (22)) (multiple-cursors (1 2 2)) (cider (0 6 0))) "A collection of clojure refactoring functions" single "marmalade"])
  (clojure-mode . [(4 0 1) ((emacs (24 1))) "Major mode for Clojure code" single "marmalade"])
  (clues-theme . [(20130908 801) ((emacs (24 0))) "an Emacs 24 theme which may well be fully awesome..." single "marmalade"])
  (cmake-mode . [(20110824) nil "Major mode for editing CMake sources." single "marmalade"])
  (cmake-project . [(0 7) nil "Integrates CMake build process with Emacs" single "marmalade"])
  (color-theme . [(6 6 1) nil "install color themes" single "marmalade"])
  (color-theme-complexity . [(0 1 1) ((color-theme (6 6 0))) "A black and green color theme for Emacs." single "marmalade"])
  (color-theme-ir-black . [(1 0 1) ((color-theme (6 6 1))) "pastel color theme" single "marmalade"])
  (combinators . [(0 0 1) nil "" single "marmalade"])
  (cpputils-cmake . [(0 4 8) nil "Easy real time C++ syntax check and intellisense if you use CMake" tar "marmalade"])
  (creole . [(1 0 6) ((noflet (0 0 3)) (kv (0 0 17))) "A parser for the Creole Wiki language" single "marmalade"])
  (cryptol-mode . [(0 1 0) nil "Cryptol major mode for Emacs" single "marmalade"])
  (csharp-mode . [(0 8 8) nil "C# mode derived mode" tar "marmalade"])
  (ctags-update . [(0 1 2) nil "auto update TAGS in parent directory using exuberant-ctags" single "marmalade"])
  (dart-mode . [(0 11) nil "Major mode for editing Dart files" single "marmalade"])
  (dash . [(2 10 0) nil "A modern list library for Emacs" single "marmalade"])
  (db . [(0 0 7) ((kv (0 0 19))) "A database for EmacsLisp" single "marmalade"])
  (desktop-registry . [(1 2 0) nil "Keep a central registry of desktop files" single "marmalade"])
  (dired-single . [(1 7) nil "reuse the current dired buffer to visit another directory" single "marmalade"])
  (drupal-mode . [(0 5 0) ((php-mode (1 5 0))) "Advanced minor mode for Drupal development" tar "marmalade"])
  (dynamic-fonts . [(0 6 4) ((font-utils (0 7 0)) (persistent-soft (0 8 8)) (pcache (0 2 3))) "Set faces based on available fonts" single "marmalade"])
  (editorconfig . [(0 4) nil "EditorConfig Emacs extension" single "marmalade"])
  (eieio . [(1 4) nil "Enhanced Implementation of Emacs Interpreted Objects" single "marmalade"])
  (el-autoyas . [(0 20) nil "Automatically create Emacs-Lisp Yasnippets" single "marmalade"])
  (el-x . [(0 3 0) ((cl-lib (0 2))) "Emacs-lisp extensions." tar "marmalade"])
  (elisp-slime-nav . [(0 7) ((cl-lib (0 2))) "Make M-. and M-, work in elisp like they do in slime" single "marmalade"])
  (elixir-mix . [(1 0 0) nil "Emacs integration for Elixir's mix" single "marmalade"])
  (elnode . [(0 9 9 8 8) ((web (0 4 3)) (dash (2 9 0)) (noflet (0 0 14)) (s (1 5 0)) (creole (1 0 6)) (fakir (0 1 9)) (db (0 0 6)) (kv (0 0 19))) "The Emacs webserver." tar "marmalade"])
  (elpakit . [(2 0 4) ((dash (2 9 0)) (shadchen (1 2)) (noflet (0 0 14)) (s (1 9 0))) "The ELPA package maintainer's friend" tar "marmalade"])
  (elpy . [(1 6 0) ((company (0 8 2)) (find-file-in-project (3 3)) (highlight-indentation (0 5 0)) (idomenu (0 1)) (pyvenv (1 3)) (yasnippet (0 8 0))) "Emacs Python Development Environment" tar "marmalade"])
  (emmet-mode . [(1 0 10) nil "Unofficial Emmet's support for emacs" single "marmalade"])
  (eshell-manual . [(20141024) nil "An manual for Eshell." tar "marmalade"])
  (evil . [(1 0 8) ((undo-tree (0 6 3)) (goto-last-change (1 2))) "Extensible Vi layer for Emacs." tar "marmalade"])
  (evil-leader . [(0 4 3) ((evil (0))) "let there be <leader>" single "marmalade"])
  (evil-nerd-commenter . [(1 3 1) nil "Comment/uncomment lines efficiently. Like Nerd Commenter in Vim" tar "marmalade"])
  (evil-numbers . [(0 4) nil "increment/decrement numbers like in vim" single "marmalade"])
  (exec-path-from-shell . [(1 7) nil "Get environment variables such as $PATH from the shell" single "marmalade"])
  (expand-region . [(0 10 0) nil "Increase selected region by semantic units." tar "marmalade"])
  (expectations-mode . [(0 0 5) ((cider (0 7 0))) "Minor mode for expectations tests" single "marmalade"])
  (express . [(0 6 0) ((string-utils (0 3 2))) "Alternatives to `message'" single "marmalade"])
  (fakir . [(0 1 9) ((noflet (0 0 8)) (dash (1 3 2)) (kv (0 0 19))) "fakeing bits of Emacs" single "marmalade"])
  (fill-column-indicator . [(1 86) nil "Graphically indicate the fill column" single "marmalade"])
  (find-file-in-project . [(3 3) nil "Find files in a project quickly." single "marmalade"])
  (fixmee . [(0 8 4) ((button-lock (1 0 0)) (nav-flash (1 0 0)) (back-button (0 6 0)) (smartrep (0 0 3)) (string-utils (0 3 2)) (tabulated-list (0))) "Quickly navigate to FIXME notices in code" single "marmalade"])
  (flycheck . [(0 22) ((dash (2 4 0)) (pkg-info (0 4)) (let-alist (1 0 1)) (cl-lib (0 3)) (emacs (24 1))) "Modern on-the-fly syntax checking for GNU Emacs" tar "marmalade"])
  (flycheck-color-mode-line . [(0 3) ((flycheck (0 15)) (dash (1 2)) (emacs (24 1))) "Change mode line color with Flycheck status" single "marmalade"])
  (flymake-checkers . [(0 5) nil "Transition package to Flycheck" single "marmalade"])
  (flymake-coffee . [(0 12) ((flymake-easy (0 1))) "A flymake handler for coffee script" single "marmalade"])
  (flymake-elixir . [(0 5) nil "A flymake handler for elixir-mode .ex files." single "marmalade"])
  (flymake-haskell-multi . [(0 3) ((flymake-easy (0 1))) "Syntax-check haskell-mode using both ghc and hlint" single "marmalade"])
  (flymake-less . [(0 3) ((less-css-mode (0 15))) "Flymake handler for LESS stylesheets (lesscss.org)" single "marmalade"])
  (flymake-python-pyflakes . [(0 9) ((flymake-easy (0 8))) "A flymake handler for python-mode files using pyflakes (or flake8)" single "marmalade"])
  (flyspell-lazy . [(0 6 6) nil "Improve flyspell responsiveness using idle timers" single "marmalade"])
  (fold-dwim-org . [(0 5) ((fold-dwim (1 2))) "Fold DWIM bound to org key-strokes." single "marmalade"])
  (font-utils . [(0 7 0) ((persistent-soft (0 8 8)) (pcache (0 2 3))) "Utility functions for working with fonts" single "marmalade"])
  (frame-restore . [(0 5) ((emacs (24 1))) "Restore Emacs frame" single "marmalade"])
  (framesize . [(0 0 5) ((key-chord (0 5 20080915))) "change the size of frames in Emacs" single "marmalade"])
  (geiser . [(0 6) nil "GNU Emacs and Scheme talk to each other" tar "marmalade"])
  (gh . [(0 8 2) ((eieio (1 4)) (pcache (0 2 4)) (logito (0 1))) "A GitHub library for Emacs" tar "marmalade"])
  (ghci-completion . [(0 1 3) nil "Completion for GHCi commands in inferior-haskell buffers" single "marmalade"])
  (gist . [(1 2 1) ((eieio (1 4)) (gh (0 8 1)) (tabulated-list (0))) "Emacs integration for gist.github.com" single "marmalade"])
  (git-auto-commit-mode . [(4 3 0) nil "Emacs Minor mode to automatically commit and push" single "marmalade"])
  (git-commit-mode . [(0 13) nil "Major mode for editing git commit messages" single "marmalade"])
  (git-gutter . [(0 78) ((cl-lib (0 5)) (emacs (24))) "Port of Sublime Text plugin GitGutter" single "marmalade"])
  (gitconfig-mode . [(0 3) nil "Major mode for editing .gitconfig files" single "marmalade"])
  (github-browse-file . [(0 4 0) ((cl-lib (0 5))) "View the file you're editing on GitHub" single "marmalade"])
  (gnusnotes . [(0 91) nil "Adding per-message notes in gnus summary buffer" single "marmalade"])
  (go-mode . [(20131222) nil "Major mode for the Go programming language" single "marmalade"])
  (google-translate . [(0 10 4) nil "Emacs interface to Google Translate." tar "marmalade"])
  (goto-last-change . [(1 2) nil "Move point through buffer-undo-list positions" single "marmalade"])
  (grapnel . [(0 5 3) nil "HTTP request lib with flexible callback dispatch" single "marmalade"])
  (grep-a-lot . [(1 0 7) nil "manages multiple search results buffers for grep.el" single "marmalade"])
  (grep-o-matic . [(1 0 6) nil "auto grep word under cursor" single "marmalade"])
  (groovy-mode . [(201203310931) nil "Groovy mode derived mode" single "marmalade"])
  (gruber-darker-theme . [(0 6) nil "Gruber Darker color theme for Emacs 24." single "marmalade"])
  (guru-mode . [(0 2) nil "Become an Emacs guru" single "marmalade"])
  (hackernews . [(0 2 1) ((json (1 2))) "Access the hackernews aggregator from Emacs" tar "marmalade"])
  (haml-mode . [(3 1 8) ((ruby-mode (1 0))) "Major mode for editing Haml files" single "marmalade"])
  (hardhat . [(0 4 4) ((ignoramus (0 7 0))) "Protect against clobbering user-writable files" single "marmalade"])
  (helm-projectile . [(0 10 0) ((helm (1 4 0)) (projectile (0 10 0))) "Helm integration for Projectile" single "marmalade"])
  (highlight-escape-sequences . [(0 1) nil "Highlight escape sequences" single "marmalade"])
  (hippie-namespace . [(0 5 8) nil "Special treatment for namespace prefixes in hippie-expand" single "marmalade"])
  (ht . [(1 5) nil "The missing hash table library for Emacs" single "marmalade"])
  (hungry-delete . [(1 1 2) nil "hungry delete minor mode" single "marmalade"])
  (ibuffer-vc . [(0 7) ((cl-lib (0 2))) "Group ibuffer's list by VC project, or show VC status" single "marmalade"])
  (ido-better-flex . [(0 2) nil "A better flex (fuzzy) algorithm for Ido." single "marmalade"])
  (ido-load-library . [(0 2 0) ((persistent-soft (0 8 8)) (pcache (0 2 3))) "Load-library alternative using ido-completing-read" single "marmalade"])
  (ido-ubiquitous . [(2 10) ((emacs (24 1))) "Use ido (nearly) everywhere." single "marmalade"])
  (ignoramus . [(0 7 2) nil "Ignore backups, build files, et al." single "marmalade"])
  (inf-ruby . [(2 3 2) nil "Run a Ruby process in a buffer" single "marmalade"])
  (inform-mode . [(1 6 2) nil "Major mode for Inform 6 interactive fiction code" single "marmalade"])
  (isea . [(0 0 2) ((elpakit (0 0 18))) "interactive server eval at mode, a comint for a daemonized emacs" single "marmalade"])
  (jb-misc-macros . [(0 4) ((macro-utils (1 0))) "Miscellaneous macros" single "marmalade"])
  (jenkins-watch . [(1 2) nil "Watch continuous integration build status" single "marmalade"])
  (json-mode . [(1 2 0) nil "Major mode for editing JSON files" single "marmalade"])
  (kanban . [(0 1 3) nil "Parse org-todo headlines to use org-tables as Kanban tables" single "marmalade"])
  (kmacro-decision . [(1 5) ((el-x (1 0)) (jb-misc-macros (0 2))) "Add conditional branching to keyboard macros" single "marmalade"])
  (kv . [(0 0 19) nil "key/value data structure functions" single "marmalade"])
  (langtool . [(1 2 1) nil "Grammar check utility using LanguageTool" single "marmalade"])
  (lcs . [(1 5) nil "find out the longest common sequence" single "marmalade"])
  (legalese . [(20120706) nil "Add legalese to your program files" single "marmalade"])
  (less-css-mode . [(0 18) nil "Major mode for editing LESS CSS files (lesscss.org)" single "marmalade"])
  (let-recur . [(0 0 5) nil "Simplified implementation of recur" single "marmalade"])
  (lexbind-mode . [(0 9) nil "Puts the value of lexical-binding in the mode line" single "marmalade"])
  (list-utils . [(0 4 2) nil "List-manipulation utility functions" single "marmalade"])
  (lui . [(1 5) ((tracking (1 5))) "Linewise User Interface" tar "marmalade"])
  (macrostep . [(0 8) nil "interactive macro stepper for Emacs Lisp" single "marmalade"])
  (magit . [(1 2 2) nil "Control Git from Emacs." tar "marmalade"])
  (maildir . [(0 0 28) ((kv (0 0 17)) (dash (2 3 0)) (s (1 9 0)) (noflet (0 0 8))) "Simple maildir based MUA." tar "marmalade"])
  (markdown-mode . [(2 0) nil "Emacs Major mode for Markdown-formatted text files" single "marmalade"])
  (marmalade-service . [(2 0 16) ((dash (1 1 0)) (s (1 6 0)) (kv (0 0 16)) (noflet (0 0 7)) (elnode (0 9 9 8 6)) (file-format (0 0 1)) (htmlize (1 3 9))) "The Marmalade package store service." tar "marmalade"])
  (minimal-session-saver . [(0 6 2) nil "Very lean session saver" single "marmalade"])
  (mocker . [(0 3 0) ((eieio (1 3)) (el-x (0 2 4))) "mocking framework for emacs" single "marmalade"])
  (mode-compile . [(2 29) nil "Smart command for compiling files" single "marmalade"])
  (monokai-theme . [(0 0 12) nil "DEPRECATED: Monokai Color Theme for Emacs." single "marmalade"])
  (multi-project . [(0 0 16) nil "Easily work with multiple projects." single "marmalade"])
  (multiple-cursors . [(1 3 0) nil "Multiple cursors for Emacs." tar "marmalade"])
  (nav-flash . [(1 1 0) nil "Briefly highlight the current line" single "marmalade"])
  (noflet . [(0 0 15) nil "locally override functions" single "marmalade"])
  (nurumacs . [(3 5 4) nil "smooth-scrolling and minimap, like sublime editor" single "marmalade"])
  (org-dotemacs . [(0 3) ((org (7 9 3)) (cl-lib (1 0))) "Store your emacs config as an org file, and choose which bits to load." single "marmalade"])
  (org-ehtml . [(0 20131014) ((elnode (20130416 1626)) (org-plus-contrib (20131007))) "Export Org-mode files as editable web pages" tar "marmalade"])
  (org-email . [(3 0 1) ((shadchen (1 2)) (dash (2 9 0)) (noflet (0 0 12))) "use org for an email database" single "marmalade"])
  (org-journal . [(1 6 4) nil "a simple org-mode based journaling mode" single "marmalade"])
  (org-magit . [(0 2 2) ((magit (1 2 0)) (org (6 1))) "basic support for magit links" single "marmalade"])
  (org-table-comment . [(0 2) nil "Org table comment modes." single "marmalade"])
  (org-trello . [(0 6 8) ((request-deferred (0 1 0)) (deferred (0 3 2)) (s (1 9 0)) (dash (2 8 0)) (emacs (24))) "Minor mode to synchronize org-mode buffer and trello board" tar "marmalade"])
  (osx-browse . [(0 8 8) ((string-utils (0 3 2)) (browse-url-dwim (0 6 6))) "Web browsing helpers for OS X" single "marmalade"])
  (pabbrev . [(4 1) nil "Predictive abbreviation expansion" single "marmalade"])
  (package . [(1 0 1) ((tabulated-list (1 0))) "Simple package system for Emacs" single "marmalade"])
  (page-break-lines . [(0 9) nil "Display ugly ^L page breaks as tidy horizontal lines" single "marmalade"])
  (paredit . [(22) nil "minor mode for editing parentheses" single "marmalade"])
  (paredit-everywhere . [(0 3) ((paredit (22))) "Enable some paredit features in non-lisp buffers" single "marmalade"])
  (parenface-reversion . [(1 2) nil "Provide a face for parens in lisp modes." single "marmalade"])
  (paste-kde . [(0 6) ((web (0 3 6))) "paste text to KDE's pastebin service" single "marmalade"])
  (pcache . [(0 2 4) ((eieio (1 3))) "persistent caching for Emacs" single "marmalade"])
  (pcmpl-args . [(0 1 1) nil "Enhanced shell command completion" single "marmalade"])
  (pcsv . [(1 3 3) nil "Parser of csv" single "marmalade"])
  (perl-myvar . [(1 23) nil "Declare lexicaly scoped vars as my()." single "marmalade"])
  (persistent-soft . [(0 8 8) ((pcache (0 2 3)) (list-utils (0 4 2))) "Persistent storage, returning nil on failure" single "marmalade"])
  (perspective . [(1 10) nil "switch between named \"perspectives\" of the editor" single "marmalade"])
  (php-extras . [(2 2 0 20140405) ((php-mode (1 5 0))) "Extra features for `php-mode'" tar "marmalade"])
  (pinboard . [(0 0 1) nil "get stuff from pinboard" single "marmalade"])
  (po-elscreen . [(1 4 6) nil "Screen for Emacsen(this is not original. original is http://www.morishima.net/~naoto/elscreen-en/?lang=en)" single "marmalade"])
  (pos-tip . [(0 4 5) nil "Show tooltip at point" single "marmalade"])
  (pretty-mode-plus . [(1 2) nil "Redisplay parts of the buffer as pretty symbols." tar "marmalade"])
  (processing-mode . [(1 2 1) nil "Major mode for Processing 2.0" single "marmalade"])
  (projectile . [(0 10 0) ((s (1 6 0)) (dash (1 5 0)) (pkg-info (0 4))) "Manage and navigate projects in Emacs easily" single "marmalade"])
  (psgml . [(1 4 1) nil "Lennart Staflin's Psgml package, with Elisp syntax and sgml-validate fixed for Emacsen >=24." tar "marmalade"])
  (puppet-mode . [(0 3) ((emacs (24 1)) (cl-lib (0 5)) (pkg-info (0 4))) "Major mode for Puppet manifests" single "marmalade"])
  (purple-haze-theme . [(20130930 36) ((emacs (24 0))) "an overtly purple color theme for Emacs24." single "marmalade"])
  (python-mode . [(6 1 3) nil "An Emacs mode for editing Python code" tar "marmalade"])
  (rainbow-delimiters . [(1 3 21) nil "Highlight nested parens, brackets, braces a different color at each depth." single "marmalade"])
  (rbenv . [(0 0 3) nil "Emacs integration for rbenv" single "marmalade"])
  (rcirc-notify . [(0 9) nil "libnotify popups" single "marmalade"])
  (rcirc-robots . [(0 0 7) ((kv (0 0 8)) (anaphora (0 0 5))) "robots based on rcirc irc" single "marmalade"])
  (rcirc-ssh . [(0 0 7) ((kv (0 0 3))) "do irc over ssh sessions" single "marmalade"])
  (recursive-narrow . [(20140811 1546) nil "narrow-to-region that operates recursively" single "marmalade"])
  (refheap . [(0 0 6) ((json (1 2))) "A library for pasting to https://refheap.com" single "marmalade"])
  (region-list-edit . [(20100530 808) nil "Add/delete a region into/from a region list, such as ((4 . 7) (11 . 15) (17 . 17) (20 . 25))." single "marmalade"])
  (remember-theme . [(20140122 1500) nil "Remembers the last theme in use and re-loads for the next session." single "marmalade"])
  (repository-root . [(1 0 4) nil "deduce the repository root directory for a given file" single "marmalade"])
  (robe . [(0 7 7) ((inf-ruby (2 3 0))) "Code navigation, documentation lookup and completion for Ruby" tar "marmalade"])
  (rspec-mode . [(1 10) nil "Enhance ruby-mode for RSpec" tar "marmalade"])
  (rubocop . [(0 3) ((dash (1 0 0))) "An Emacs interface for RuboCop" single "marmalade"])
  (ruby-compilation . [(2 10) ((inf-ruby (2 2 1))) "run a ruby process in a compilation buffer" single "marmalade"])
  (ruby-end . [(0 3 1) nil "Automatic insertion of end blocks for Ruby" single "marmalade"])
  (ruby-hash-syntax . [(0 3) nil "Toggle ruby hash syntax between classic and 1.9 styles" single "marmalade"])
  (ruby-test-mode . [(1 7) ((ruby-mode (1 0))) "Minor mode for Behaviour and Test Driven" single "marmalade"])
  (s . [(1 9 0) nil "The long lost Emacs string manipulation library." single "marmalade"])
  (sass-mode . [(3 0 16) ((haml-mode (3 0 15))) "Major mode for editing Sass files" single "marmalade"])
  (save-visited-files . [(1 2) nil "save opened files across sessions" single "marmalade"])
  (scpaste . [(0 6 3) ((htmlize (1 39))) "Paste to the web via scp." single "marmalade"])
  (sea-before-storm-theme . [(0 4 20141114) nil "Sea Before Storm color theme for Emacs 24" single "marmalade"])
  (sequence . [(0 0 1) nil "makes sequences of numbers" single "marmalade"])
  (shadchen . [(1 4) nil "pattern matching for elisp" single "marmalade"])
  (shorten . [(0 3) nil "component-wise string shortener" single "marmalade"])
  (show-marks . [(0 4) ((fm (1 0))) "Navigate and visualize the mark-ring" single "marmalade"])
  (simpleclip . [(1 0 0) nil "Simplified access to the system clipboard" single "marmalade"])
  (skinny . [(0 0 6) ((elnode (0 9 9 6 1)) (creole (0 8 17))) "a blog engine with elnode" single "marmalade"])
  (slime-clj . [(0 1 6) nil "slime extensions for swank-clj" single "marmalade"])
  (smart-operator . [(2 0 20110812) nil "Insert operators with surrounding spaces smartly" single "marmalade"])
  (smartparens . [(1 4) ((dash (1 1 0))) "Automatic insertion, wrapping and paredit-like navigation with user defined pairs." tar "marmalade"])
  (smex . [(3 0) nil "M-x interface with Ido-style fuzzy matching." single "marmalade"])
  (sourcetalk . [(1 2 0) ((request (0 2 0))) "SourceTalk (http://sourcetalk.net) plugin for Emacs" single "marmalade"])
  (sparql-mode . [(0 8 4) nil "Edit and interactively evaluate SPARQL queries." tar "marmalade"])
  (spotify . [(0 3) nil "Control the spotify application from emacs" single "marmalade"])
  (string-utils . [(0 3 2) ((list-utils (0 4 2))) "String-manipulation utilities" single "marmalade"])
  (subshell-proc . [(1 0 0) nil "Functions for working with comints" single "marmalade"])
  (sudden-death . [(0 1) nil "Totsuzen-no-Shi" single "marmalade"])
  (syntactic-sugar . [(0 9 4) nil "Effect-free forms such as if/then/else" single "marmalade"])
  (syslog-mode . [(2 2) ((hide-lines (20130623))) "Major-mode for viewing log files" single "marmalade"])
  (test-case-mode . [(0 1 9) nil "unit test front-end" single "marmalade"])
  (tracking . [(1 5) ((shorten (0 3))) "Buffer modification tracking" single "marmalade"])
  (truthy . [(0 2 8) ((list-utils (0 4 2))) "Test the content of a value" single "marmalade"])
  (tuareg . [(2 0 8) ((caml (3 12 0 1))) "OCaml mode for Emacs" tar "marmalade"])
  (tumblesocks . [(0 0 7) ((htmlize (1 39)) (oauth (1 0 3)) (markdown-mode (1 8 1))) "An Emacs tumblr client." tar "marmalade"])
  (twittering-mode . [(3 0 1) nil "Major mode for Twitter" single "marmalade"])
  (ucs-utils . [(0 7 10) ((persistent-soft (0 8 8)) (pcache (0 2 3)) (list-utils (0 4 2))) "Utilities for Unicode characters" single "marmalade"])
  (ujelly-theme . [(1 0 35) nil "Ujelly theme for GNU Emacs 24 (deftheme)" single "marmalade"])
  (unicode-enbox . [(0 1 4) ((string-utils (0 3 2)) (ucs-utils (0 7 6)) (persistent-soft (0 8 8)) (pcache (0 2 3))) "Surround a string with box-drawing characters" single "marmalade"])
  (unicode-fonts . [(0 3 8) ((font-utils (0 7 0)) (ucs-utils (0 7 6)) (persistent-soft (0 8 8)) (pcache (0 2 3))) "Configure Unicode fonts" single "marmalade"])
  (unicode-progress-reporter . [(0 5 4) ((emacs (24 1 0)) (ucs-utils (0 7 6)) (persistent-soft (0 8 8)) (pcache (0 2 3))) "Progress-reporter with fancy characters" single "marmalade"])
  (unicode-whitespace . [(0 2 4) ((ucs-utils (0 7 6)) (persistent-soft (0 8 8)) (pcache (0 2 3))) "teach whitespace-mode about fancy characters" single "marmalade"])
  (vector-utils . [(0 1 2) nil "Vector-manipulation utility functions" single "marmalade"])
  (virtualenv . [(1 2) nil "Virtualenv for Python" single "marmalade"])
  (wacspace . [(0 4 2) ((dash (1 2 0)) (cl-lib (0 2))) "The WACky WorkSPACE manager for emACS" tar "marmalade"])
  (wc-mode . [(1 3) nil "Running word count with goals (minor mode)" single "marmalade"])
  (wcheck-mode . [(2014 6 21) nil "General interface for text checkers" tar "marmalade"])
  (weather-metno . [(20140909) ((emacs (24)) (cl-lib (0 3))) "Weather data from met.no in Emacs" tar "marmalade"])
  (web . [(0 5 2) ((dash (2 9 0)) (s (1 5 0))) "useful HTTP client" single "marmalade"])
  (web-mode . [(8 0 4) nil "major mode for editing html templates" single "marmalade"])
  (wiki-nav . [(1 0 0) ((button-lock (1 0 0)) (nav-flash (1 0 0))) "Simple file navigation using [[WikiStrings]]" single "marmalade"])
  (wikidoc . [(0 9) ((s\.el (1 9 0))) "use elisp doc strings to make other documentation" single "marmalade"])
  (window-end-visible . [(0 1 0) nil "Find the last visible point in a window" single "marmalade"])
  (window-number . [(1 0 3) nil "Select windows by numbers." single "marmalade"])
  (workspaces . [(0 1) nil "Workspaces for Emacsen" single "marmalade"])
  (world-time-mode . [(0 0 6) nil "show whole days of world-time diffs" single "marmalade"])
  (writegood-mode . [(20130406 2316) nil "Polish up poor writing on the fly" single "marmalade"])
  (yaml-mode . [(0 0 9) nil "Major mode for editing YAML files" single "marmalade"])
  (yari . [(0 7) nil "Yet Another RI interface for Emacs" single "marmalade"])
  (znc . [(0 0 2) ((cl (2 2)) (erc (5 3))) "ZNC + ERC" single "marmalade"])
 )
