'(
  (abl-mode . [(0 9 0) nil "Python TDD minor mode" single "marmalade"])
  (ace-jump-mode . [(2 0 0 0) nil "a quick cursor location minor mode for emacs" single "marmalade"])
  (android-mode . [(0 2 1) nil "Minor mode for Android application development" single "marmalade"])
  (anything-complete . [(1 86) ((anything (1 287)) (anything-obsolete (0 1))) "completion with anything" single "marmalade"])
  (anything-el-swank-fuzzy . [(0 1 2009) ((anything (1 287)) (anything-complete (1 86))) "anything-sources for el-swank-fuzzy.el" single "marmalade"])
  (anything-ipython . [(0 1 2009) ((ipython (2927)) (anything (1 287))) "Ipython anything" single "marmalade"])
  (auto-indent-mode . [(0 99) nil "Auto indent Minor mode" single "marmalade"])
  (autopair . [(0 4) nil "Automagically pair braces and quotes like TextMate" single "marmalade"])
  (browse-kill-ring . [(1 3 1) nil "interactively insert items from kill-ring" single "marmalade"])
  (button-lock . [(0 81) nil "clickable text defined by regular expression, controlled by font-lock" single "marmalade"])
  (color-theme . [(6 6 1) nil "install color themes" single "marmalade"])
  (color-theme-complexity . [(0 1 1) ((color-theme (6 6 0))) "A black and green color theme for Emacs." single "marmalade"])
  (color-theme-dawn-night . [(2 0) nil "color theme of dawn and night" single "marmalade"])
  (color-theme-ir-black . [(1 0 1) ((color-theme (6 6 1))) "pastel color theme" single "marmalade"])
  (combinators . [(0 0 1) nil "" single "marmalade"])
  (cpputils-cmake . [(0 3 0) nil "Easy real time C++ syntax check and intellisense if you use CMake." tar "marmalade"])
  (creole . [(0 9 20130602) ((noflet (0 0 3))) "A parser for the Creole Wiki language" single "marmalade"])
  (ctags-update . [(0 1 2) nil "auto update TAGS in parent directory using exuberant-ctags" single "marmalade"])
  (dash . [(1 4 0) nil "A modern list library for Emacs" single "marmalade"])
  (db . [(0 0 6) ((kv (0 0 11))) "A database for EmacsLisp" single "marmalade"])
  (diff-hl . [(1 4 6) ((cl-lib (0 2))) "Highlight uncommitted changes" single "marmalade"])
  (dired-single . [(1 7) nil "reuse the current dired buffer to visit another directory" single "marmalade"])
  (eieio . [(1 4) nil "Enhanced Implementation of Emacs Interpreted Objects" single "marmalade"])
  (el-autoyas . [(0 20) nil "Automatically create Emacs-Lisp Yasnippets" single "marmalade"])
  (elixir-mix . [(0 0 2) nil "Emacs integration for Elixir's elixir-mix" single "marmalade"])
  (elnode . [(0 9 9 7 3) ((web (0 1 4)) (dash (1 1 0)) (s (1 5 0)) (creole (0 8 14)) (fakir (0 1 6)) (db (0 0 5)) (kv (0 0 17))) "The Emacs webserver." tar "marmalade"])
  (eshell-manual . [(1348477812) nil "An updated manual for Eshell." tar "marmalade"])
  (evernote-mode . [(0 41) nil "Evernote client for Emacs" single "marmalade"])
  (evil . [(1 0 5) ((undo-tree (0 5 1))) "Extensible Vi layer for Emacs." tar "marmalade"])
  (evil-nerd-commenter . [(0 0 5) nil "Comment/uncomment lines efficiently. Like Nerd Commenter in Vim" tar "marmalade"])
  (fakir . [(0 1 6) ((noflet (0 0 3)) (dash (1 3 2))) "fakeing bits of Emacs" single "marmalade"])
  (flex-autopair . [(0 1) nil "Automatically insert pair braces and quotes, insertion condition & action are highly customizable." single "marmalade"])
  (flycheck . [(0 12) ((s (1 3 1)) (dash (1 2)) (cl-lib (0 1)) (emacs (24 1))) "On-the-fly syntax checking (Flymake done right)" tar "marmalade"])
  (flycheck-color-mode-line . [(0 2) ((flycheck (0 13)) (dash (1 2)) (emacs (24 1))) "Change mode line color with Flycheck status" single "marmalade"])
  (flymake-elixir . [(0 4) nil "A flymake handler for elixir-mode .ex files." single "marmalade"])
  (flymake-haskell-multi . [(0 3) ((flymake-easy (0 1))) "Syntax-check haskell-mode using both ghc and hlint" single "marmalade"])
  (flymake-lua . [(1) nil "Flymake for Lua" single "marmalade"])
  (ghci-completion . [(0 1 3) nil "Completion for GHCi commands in inferior-haskell buffers" single "marmalade"])
  (git-commit-mode . [(0 12) nil "Major mode for editing git commit messages" single "marmalade"])
  (gitconfig-mode . [(0 3) nil "Major mode for editing .gitconfig files" single "marmalade"])
  (gnusnotes . [(0 91) nil "Adding per-message notes in gnus summary buffer" single "marmalade"])
  (goto-last-change . [(1 2) nil "Move point through buffer-undo-list positions" single "marmalade"])
  (groovy-mode . [(201203310931) nil "Groovy mode derived mode" single "marmalade"])
  (gruber-darker-theme . [(0 4) nil "Gruber Darker color theme for Emacs 24." single "marmalade"])
  (haskell-mode . [(13 6) nil "A Haskell editing mode" tar "marmalade"])
  (helm-projectile . [(0 9 1) ((helm (1 4 0)) (projectile (0 9 1))) "Helm integration for Projectile" single "marmalade"])
  (hideshowvis . [(0 3) nil "Add markers to the fringe for regions foldable by hideshow.el" single "marmalade"])
  (highlight-escape-sequences . [(0 1) nil "Highlight escape sequences" single "marmalade"])
  (ido-better-flex . [(0 2) nil "A better flex (fuzzy) algorithm for Ido." single "marmalade"])
  (inf-ruby . [(2 2 5) nil "Run a ruby process in a buffer" single "marmalade"])
  (isea . [(0 0 2) ((elpakit (0 0 18))) "interactive server eval at mode, a comint for a daemonized emacs" single "marmalade"])
  (jenkins-watch . [(1 2) nil "Watch continuous integration build status" single "marmalade"])
  (jump . [(2 2) ((findr (0 7)) (inflections (1 1))) "build functions which contextually jump between files" single "marmalade"])
  (kmacro-decision . [(0 9) ((el-x (1 0))) "Add conditional branching to keyboard macros" single "marmalade"])
  (legalese . [(20120706) nil "Add legalese to your program files" single "marmalade"])
  (let-recur . [(0 0 5) nil "Simplified implementation of recur" single "marmalade"])
  (maildir . [(0 0 18) nil "Simple maildir based MUA." tar "marmalade"])
  (main-line . [(1 2 2) nil "modeline replacement forked from an early version of powerline.el" single "marmalade"])
  (mode-compile . [(2 29) nil "Smart command for compiling files" single "marmalade"])
  (noflet . [(0 0 7) nil "locally override functions" single "marmalade"])
  (nurumacs . [(3 5 4) nil "smooth-scrolling and minimap, like sublime editor" single "marmalade"])
  (org-email . [(1 0) nil "use org for an email database" single "marmalade"])
  (org-table-comment . [(0 2) nil "Org table comment modes." single "marmalade"])
  (paredit . [(22) nil "minor mode for editing parentheses" single "marmalade"])
  (paste-kde . [(0 2 1) ((web (0 3 6))) "paste text to KDE's pastebin service" single "marmalade"])
  (pcmpl-args . [(0 1 1) nil "Enhanced shell command completion" single "marmalade"])
  (pcsv . [(1 3 2) nil "Parser of csv" single "marmalade"])
  (perl-myvar . [(1 23) nil "Declare lexicaly scoped vars as my()." single "marmalade"])
  (pinboard . [(0 0 1) nil "get stuff from pinboard" single "marmalade"])
  (po-elscreen . [(1 4 6) nil "Screen for Emacsen(this is not original. original is http://www.morishima.net/~naoto/elscreen-en/?lang=en)" single "marmalade"])
  (pos-tip . [(0 4 5) nil "Show tooltip at point" single "marmalade"])
  (projectile . [(0 9 1) ((s (1 0 0)) (dash (1 0 0))) "Manage and navigate projects in Emacs easily" single "marmalade"])
  (r-autoyas . [(2011 3 13) nil "Provides automatically created yasnippets for R function argument lists." single "marmalade"])
  (rainbow-delimiters . [(1 3 21) nil "Highlight nested parens, brackets, braces a different color at each depth." single "marmalade"])
  (rbenv . [(0 0 1) nil "Emacs integration for rbenv" single "marmalade"])
  (rcirc-robots . [(0 0 7) ((kv (0 0 8)) (anaphora (0 0 5))) "robots based on rcirc irc" single "marmalade"])
  (rcirc-ssh . [(0 0 7) ((kv (0 0 3))) "do irc over ssh sessions" single "marmalade"])
  (region-list-edit . [(20100530 808) nil "Add/delete a region into/from a region list, such as ((4 . 7) (11 . 15) (17 . 17) (20 . 25))." single "marmalade"])
  (ruby-compilation . [(2 10) ((inf-ruby (2 2 1))) "run a ruby process in a compilation buffer" single "marmalade"])
  (sackspace . [(0 8 1) nil "A better backspace" single "marmalade"])
  (sequence . [(0 0 1) nil "makes sequences of numbers" single "marmalade"])
  (skinny . [(0 0 3) ((elnode (0 9 9 6 1)) (creole (0 8 17))) "a blog engine with elnode" single "marmalade"])
  (slime-clj . [(0 1 6) nil "slime extensions for swank-clj" single "marmalade"])
  (smart-operator . [(2 0 20110812) nil "Insert operators with surrounding spaces smartly" single "marmalade"])
  (smartparens . [(1 4) ((dash (1 1 0))) "Automatic insertion, wrapping and paredit-like navigation with user defined pairs." tar "marmalade"])
  (smex . [(2 0) nil "M-x interface with Ido-style fuzzy matching." single "marmalade"])
  (sparql-mode . [(0 6 1) nil "Edit and interactively evaluate SPARQL queries." single "marmalade"])
  (subshell-proc . [(1 0 0) nil "Functions for working with comints" single "marmalade"])
  (tabbar . [(2 0 1) nil "Display a tab bar in the header line" single "marmalade"])
  (tabbar-ruler . [(0 36) ((tabbar (2 0 1))) "Pretty tabbar, autohide, use both tabbar/ruler" single "marmalade"])
  (tex-smart-umlauts . [(1 1 0) nil "Smart umlaut conversion for TeX." single "marmalade"])
  (theme-changer . [(2 0 0) nil "Sunrise/Sunset Theme Changer for Emacs" single "marmalade"])
  (virtualenv . [(1 2) nil "Virtualenv for Python" single "marmalade"])
  (wacspace . [(0 4) ((dash (1 2 0)) (cl-lib (0 2))) "The WACky WorkSPACE manager for emACS" single "marmalade"])
  (wcheck-mode . [(2013 6 13) nil "General interface for text checkers" tar "marmalade"])
  (web . [(0 3 7) nil "useful HTTP client" single "marmalade"])
  (wiki-nav . [(0 11) ((button-lock (0 8))) "simple file navigation using [[WikiStrings]]" single "marmalade"])
  (workspaces . [(0 1) nil "Workspaces for Emacsen" single "marmalade"])
  (yagist . [(0 8 3) ((json (1 2 0))) "Yet Another Emacs integration for gist.github.com" single "marmalade"])
  (zenburn-theme . [(2 0) nil "A low contrast color theme for Emacs." single "marmalade"])
  (znc . [(0 0 2) ((cl (2 2)) (erc (5 3))) "ZNC + ERC" single "marmalade"])
 )
