'(
  (creds [cl-struct-package-desc creds (0 0 4) "a simple parser credential file lib" nil tar "marmalade" nil nil nil])
  (flycheck-tcl [cl-struct-package-desc flycheck-tcl (0 4) "A flycheck checker for Tcl using ActiveState's tclchecker" ((flycheck (0 17))) single "marmalade" nil nil nil])
  (latex-preview-pane [cl-struct-package-desc latex-preview-pane (20140204) "Makes LaTeX editing less painful by providing a updatable preview pane. Full documentation can be found at: http://www.emacswiki.org/emacs/LaTeXPreviewPane" nil tar "marmalade" nil nil nil])
  (epl [cl-struct-package-desc epl (0 5) "Emacs Package Library -*- lexical-binding: t; -*-" ((cl-lib (0 3))) single "marmalade" nil nil nil])
  (lxc [cl-struct-package-desc lxc (0 0 1) "lxc integration with Emacs" nil single "marmalade" nil nil nil])
  (eshell-fringe-status [cl-struct-package-desc eshell-fringe-status (1 0 0) "Show last status in fringe  -*- lexical-binding: t; -*-" nil single "marmalade" nil nil nil])
  (finalize [cl-struct-package-desc finalize (1 0 0) "finalizers for Emacs Lisp" ((emacs (24 1)) (cl-lib (0 3)) (eieio (1 4))) tar "marmalade" nil nil nil])
  (gecf [cl-struct-package-desc gecf (0 1 0) "G\303\266ktu\304\237's Emacs configuration framework." nil single "marmalade" nil nil nil])
  (elfeed [cl-struct-package-desc elfeed (1 1 0) "an Emacs Atom/RSS feed reader" ((emacs (24 1))) tar "marmalade" nil nil nil])
  (memoize [cl-struct-package-desc memoize (1 0 1) "Memoization functions -*- lexical-binding: t; -*-" nil single "marmalade" nil nil nil])
  (cl-lib-highlight [cl-struct-package-desc cl-lib-highlight (1 0 0) "full cl-lib font-lock highlighting" ((cl-lib (0 3))) single "marmalade" nil nil nil])
  (skewer-mode [cl-struct-package-desc skewer-mode (1 6 0) "live browser JavaScript, CSS, and HTML interaction" ((simple-httpd (1 4 0)) (js2-mode (20090723)) (emacs (24))) tar "marmalade" nil nil nil])
  (simple-httpd [cl-struct-package-desc simple-httpd (1 4 5) "pure elisp HTTP server" ((cl-lib (0 3))) single "marmalade" nil nil nil])
  (es-windows [cl-struct-package-desc es-windows (0 2) "Window-management utilities -*- lexical-binding: t -*-" ((cl-lib (0 3)) (emacs (24))) single "marmalade" nil nil nil])
  (exercism [cl-struct-package-desc exercism (0 0 1) "An Emacs mode for submitting current file to exercism.io" nil single "marmalade" nil nil nil])
  (xkcd [cl-struct-package-desc xkcd (1 0) "View xkcd from Emacs" ((json (1 4))) single "marmalade" nil nil nil])
  (cider [cl-struct-package-desc cider (0 5 0) "Clojure Integrated Development Environment and REPL" ((clojure-mode (2 0 0)) (cl-lib (0 3)) (dash (2 4 1)) (pkg-info (0 4))) tar "marmalade" nil nil nil])
  (pyvenv [cl-struct-package-desc pyvenv (1 1) "Python virtual environment interface -*- lexical-binding: t -*-" nil single "marmalade" nil nil nil])
  (toggle-test [cl-struct-package-desc toggle-test (1 0 1) "Toggle between source and test files. It is language agnostic and creates source/test files if they don't exist." nil single "marmalade" nil nil nil])
  (flycheck-haskell [cl-struct-package-desc flycheck-haskell (0 1) "Flycheck: Haskell configuration" ((flycheck (0 16)) (haskell-mode (13 7)) (dash (2 4 0)) (f (0 11 0))) tar "marmalade" nil nil nil])
  (jam-mode [cl-struct-package-desc jam-mode (0 3) "Font-lock support for Jam files" nil single "marmalade" nil nil nil])
  (nose-mode [cl-struct-package-desc nose-mode (0 1) "Minor mode for running nose tests." ((nose (0 1 1))) tar "marmalade" nil nil nil])
  (downplay-mode [cl-struct-package-desc downplay-mode (0 1) "focus attention on a region of the buffer" nil single "marmalade" nil nil nil])
  (steady-theme [cl-struct-package-desc steady-theme (0 1 0) "A steady theme for Emacs  -*- lexical-binding: t -*-" nil single "marmalade" nil nil nil])
  (insert-shebang [cl-struct-package-desc insert-shebang (0 9 3) "Insert shebang line automatically." nil single "marmalade" nil nil nil])
  (wisp [cl-struct-package-desc wisp (0 1 3) "Supporting tools for editing wisp: The Whitespace-to-Lisp preprocesor" nil single "marmalade" nil nil nil])
  (goto-chg [cl-struct-package-desc goto-chg (1 6) "goto last change" nil single "marmalade" nil nil nil])
  (gnus-summary-ext [cl-struct-package-desc gnus-summary-ext (0 1) "Extra limit and process mark commands for the gnus summary buffer" ((macro-utils (1 0))) single "marmalade" nil nil nil])
  (bubbleberry-theme [cl-struct-package-desc bubbleberry-theme (0 1 2) "A theme based on LightTable for Emacs24" ((emacs (24 1))) single "marmalade" nil nil nil])
  (ido-select-window [cl-struct-package-desc ido-select-window (0 1 0) "Select a window using ido and buffer names." nil tar "marmalade" nil nil nil])
  (dakrone-theme [cl-struct-package-desc dakrone-theme (0 0 2) "dakrone's custom dark theme" nil single "marmalade" nil nil nil])
  (flymake-racket [cl-struct-package-desc flymake-racket (0 40) "A flymake handler for scheme-mode files" ((flymake-easy (0 1))) single "marmalade" nil nil nil])
  (org-gnome [cl-struct-package-desc org-gnome (0 1) "Orgmode integration with the GNOME desktop" ((notify (2010 8 20)) (telepathy (0 1))) single "marmalade" nil nil nil])
  (telepathy [cl-struct-package-desc telepathy (0 1) "Access Telepathy from Emacs" nil single "marmalade" nil nil nil])
  (gvpr-mode [cl-struct-package-desc gvpr-mode (0 1 0) "A major mode offering basic syntax coloring for gvpr scripts." nil single "marmalade" nil nil nil])
  (flycheck-ledger [cl-struct-package-desc flycheck-ledger (0 2) "Flycheck integration for ledger files" ((flycheck (0 15))) single "marmalade" nil nil nil])
  (pinboard-api [cl-struct-package-desc pinboard-api (0 1) "Rudimentary http://pinboard.in integration" nil single "marmalade" nil nil nil])
  (column-enforce-mode [cl-struct-package-desc column-enforce-mode (1 0 3) "Highlight text that extends beyond a  column" nil single "marmalade" nil nil nil])
  (ix [cl-struct-package-desc ix (0 7) "Emacs client for http://ix.io pastebin" ((grapnel (0 5 3))) single "marmalade" nil nil nil])
  (flycheck-hdevtools [cl-struct-package-desc flycheck-hdevtools (0 2) "A flycheck checker for Haskell using hdevtools" ((flycheck (0 15))) single "marmalade" nil nil nil])
  (zeal-at-point [cl-struct-package-desc zeal-at-point (0 0 3) "Search the word at point with Zeal" nil single "marmalade" nil nil nil])
  (tdd-status-mode-line [cl-struct-package-desc tdd-status-mode-line (0 1 2) "TDD status on the mode-line" nil single "marmalade" nil nil nil])
  (troncle [cl-struct-package-desc troncle (0 1 2) "Emacs convenience functions for tracing clojure code" ((cider (0 5 0))) single "marmalade" nil nil nil])
  (free-keys [cl-struct-package-desc free-keys (0 1) "Show free keybindings for modkeys or prefixes" ((cl-lib (0 3))) single "marmalade" nil nil nil])
  (prognth [cl-struct-package-desc prognth (1 0) "Extend prog1 to arbitrary index" nil single "marmalade" nil nil nil])
  (ariadne [cl-struct-package-desc ariadne (0 1) "Ariadne plugin for Emacs" ((bert (0 1))) single "marmalade" nil nil nil])
  (bert [cl-struct-package-desc bert (0 1) "BERT serialization library for Emacs" nil single "marmalade" nil nil nil])
  (livid-mode [cl-struct-package-desc livid-mode (0 1 0) "Live browser eval of JavaScript every time a buffer changes" ((skewer-mode (1 5 3)) (s (1 8 0))) single "marmalade" nil nil nil])
  (minitest [cl-struct-package-desc minitest (0 5) "An Emacs mode for ruby minitest files" ((dash (1 0 0))) single "marmalade" nil nil nil])
  (ido-vertical-mode [cl-struct-package-desc ido-vertical-mode (0 1 2) "Makes ido-mode display vertically." nil single "marmalade" nil nil nil])
  (nrepl-discover [cl-struct-package-desc nrepl-discover (0 0 1) "Client to load commands from nrepl server" nil single "marmalade" nil nil nil])
  (json-snatcher [cl-struct-package-desc json-snatcher (1 0) "Grabs the path to JSON values in a JSON file." nil single "marmalade" nil nil nil])
  (ac-inf-ruby [cl-struct-package-desc ac-inf-ruby (0 4) "Enable auto-complete in inf-ruby sessions" ((inf-ruby (2 3 2)) (auto-complete (1 4))) single "marmalade" nil nil nil])
  (relax [cl-struct-package-desc relax (0 2) "For browsing and interacting with CouchDB" ((json (1 2))) single "marmalade" nil nil nil])
  (el-init [cl-struct-package-desc el-init (20130416) "Loader for configuration files" nil tar "marmalade" nil nil nil])
  (lyskom [cl-struct-package-desc lyskom (20131008) "LysKOM elisp client." nil single "marmalade" nil nil nil])
  (proxy-mode [cl-struct-package-desc proxy-mode (0 9) "Provides proxy minor mode." nil single "marmalade" nil nil nil])
  (latest-clojure-libraries [cl-struct-package-desc latest-clojure-libraries (0 5) "Clojure dependency resolver" nil single "marmalade" nil nil nil])
  (list-register [cl-struct-package-desc list-register (2 2) "List register" nil single "marmalade" nil nil nil])
  (anzu [cl-struct-package-desc anzu (0 22) "Show number of matches in mode-line while searching" nil single "marmalade" nil nil nil])
  (magit-find-file [cl-struct-package-desc magit-find-file (1 0 4) "completing-read over all files in Git" ((magit (1 2 0))) single "marmalade" nil nil nil])
  (sequences [cl-struct-package-desc sequences (0 1 0) "Ports of some Clojure sequence functions." ((emacs (24))) single "marmalade" nil nil nil])
  (sensitive [cl-struct-package-desc sensitive (1 0 1) "A dead simple way to load sensitive information" ((emacs (24)) (sequences (0 1 0))) single "marmalade" nil nil nil])
  (skewer-less [cl-struct-package-desc skewer-less (0 2) "Skewer support for live LESS stylesheet updates" ((skewer-mode (1 5 3))) single "marmalade" nil nil nil])
  (evil-matchit [cl-struct-package-desc evil-matchit (1 2 7) "Vim matchit ported into Emacs (requires EVIL)" nil tar "marmalade" nil nil nil])
  (tbemail [cl-struct-package-desc tbemail (0 2) "Provide syntax highlighting for email editing via" nil single "marmalade" nil nil nil])
  (timestamper [cl-struct-package-desc timestamper (0 1 0) "A minor mode for easy timelogging" nil single "marmalade" nil nil nil])
  (pbcopy [cl-struct-package-desc pbcopy (0 1 0) "OS X clipboard integration for Emacs" nil single "marmalade" nil nil nil])
  (tommyh-theme [cl-struct-package-desc tommyh-theme (1 2) "A bright, bold-colored theme for emacs." nil single "marmalade" nil nil nil])
  (ample-zen-theme [cl-struct-package-desc ample-zen-theme (0 2) "AmpleZen Theme for Emacs 24" nil single "marmalade" nil nil nil])
  (iasm-mode [cl-struct-package-desc iasm-mode (0 1) "interactive assembly major mode." nil single "marmalade" nil nil nil])
  (ac-geiser [cl-struct-package-desc ac-geiser (0 1) "Auto-complete backend for geiser" ((geiser (0 5)) (auto-complete (1 4))) tar "marmalade" nil nil nil])
  (java-file-create [cl-struct-package-desc java-file-create (1 0) "automatically insert contents of empty java files" nil single "marmalade" nil nil nil])
  (isgd [cl-struct-package-desc isgd (20130927) "Shorten URLs using the isgd.com shortener service" nil single "marmalade" nil nil nil])
  (whitespace-cleanup-mode [cl-struct-package-desc whitespace-cleanup-mode (0 8) "Intelligently call whitespace-cleanup on save" nil single "marmalade" nil nil nil])
  (f [cl-struct-package-desc f (0 11 0) "Modern API for working with files and directories" ((s (1 7 0)) (dash (2 2 0))) single "marmalade" nil nil nil])
  (osx-pseudo-daemon [cl-struct-package-desc osx-pseudo-daemon (1 0) "Daemon mode that plays nice with OSX." nil single "marmalade" nil nil nil])
  (shell-pop [cl-struct-package-desc shell-pop (0 3) "helps you to use shell easily on Emacs. Only one key action to work." nil single "marmalade" nil nil nil])
  (zone-matrix [cl-struct-package-desc zone-matrix (0 0 1) "Matrix themed Zone mode" nil tar "marmalade" nil nil nil])
  (elfeed-web [cl-struct-package-desc elfeed-web (1 1 0) "web interface to Elfeed" ((simple-httpd (1 4 3)) (elfeed (1 0 1)) (emacs (24 1))) tar "marmalade" nil nil nil])
  (wonderland [cl-struct-package-desc wonderland (0 1 1) "declarative configuration for Emacsen -*- lexical-binding: t -*-" ((dash (2 0 0)) (dash-functional (1 0 0)) (multi (2 0 0)) (emacs (24))) single "marmalade" nil nil nil])
  (jujube-theme [cl-struct-package-desc jujube-theme (0 1) "Pastel theme loosely based on jellybeans" nil single "marmalade" nil nil nil])
  (helm-helm-commands [cl-struct-package-desc helm-helm-commands (0 2) "List all helm commands with helm" ((helm (1 5 4))) single "marmalade" nil nil nil])
  (evil-indent-textobject [cl-struct-package-desc evil-indent-textobject (0 2) "evil textobjects based on indentation" ((evil (0))) single "marmalade" nil nil nil])
  (multi [cl-struct-package-desc multi (2 0 1) "Clojure-style multi-methods for emacs lisp -*- lexical-binding: t -*-" ((emacs (24))) single "marmalade" nil nil nil])
  (gerrit-download [cl-struct-package-desc gerrit-download (0 2) "Show gerrit reviews in a diff buffer." ((magit (20130828 1540))) single "marmalade" nil nil nil])
  (waher-theme [cl-struct-package-desc waher-theme (20130917 7) "Emacs 24 theme based on waher for st2 by dduckster" ((emacs (24 1))) single "marmalade" nil nil nil])
  (comint-better-defaults [cl-struct-package-desc comint-better-defaults (1 0) "better defaults for comint-derived modes" nil single "marmalade" nil nil nil])
  (winpoint-ignore-dired [cl-struct-package-desc winpoint-ignore-dired (1 1) "Have winpoint ignore dired-mode buffers" ((winpoint (1 0))) single "marmalade" nil nil nil])
  (tox [cl-struct-package-desc tox (0 1) "Launch current python test with tox." nil single "marmalade" nil nil nil])
  (smart-whitespace-comment-fixup [cl-struct-package-desc smart-whitespace-comment-fixup (1 0) "Enables advice around yanking/killing lines that auto-indents and formats properly" nil single "marmalade" nil nil nil])
  (figlet [cl-struct-package-desc figlet (289) "banner generator" nil single "marmalade" nil nil nil])
  (smtpmail-multi [cl-struct-package-desc smtpmail-multi (0 6) "Use different smtp servers for sending mail" nil single "marmalade" nil nil nil])
  (openstack-cgit-browse-file [cl-struct-package-desc openstack-cgit-browse-file (0 2) "Browse the current file in OpenStack cgit" nil single "marmalade" nil nil nil])
  (flycheck-cask [cl-struct-package-desc flycheck-cask (0 1) "Cask support in Flycheck -*- lexical-binding: t; -*-" ((flycheck (0 14)) (dash (2 0 0)) (f (0 6 0))) single "marmalade" nil nil nil])
  (dash-functional [cl-struct-package-desc dash-functional (1 0 0) "Collection of useful combinators for Emacs Lisp  -*- lexical-binding: t -*-" ((dash (2 0 0)) (emacs (24))) single "marmalade" nil nil nil])
  (pkg-info [cl-struct-package-desc pkg-info (0 4) "Information about packages       -*- lexical-binding: t; -*-" ((dash (1 6 0)) (epl (0 4))) single "marmalade" nil nil nil])
  (discord [cl-struct-package-desc discord (0 5) "Discordian dates for calendar" nil single "marmalade" nil nil nil])
  (aok [cl-struct-package-desc aok (0 1) "various useful ways to do `multi-occur'" nil single "marmalade" nil nil nil])
  (magit-tramp [cl-struct-package-desc magit-tramp (0 1 0) "git method for TRAMP" ((magit (1 2 0))) single "marmalade" nil nil nil])
  (tronesque-theme [cl-struct-package-desc tronesque-theme (1 3) "Color Theme based on Tron universe." nil single "marmalade" nil nil nil])
  (helm-recoll [cl-struct-package-desc helm-recoll (20130905 2330) "helm interface for the recoll desktop search tool." ((helm (1 5 4))) single "marmalade" nil nil nil])
  (god-mode [cl-struct-package-desc god-mode (2 12 0) "God-like command entering minor mode" nil single "marmalade" nil nil nil])
  (heroku-theme [cl-struct-package-desc heroku-theme (1 1 0) "Heroku color theme" nil single "marmalade" nil nil nil])
  (tsql [cl-struct-package-desc tsql (1 0) "customizes sql.el for T-SQL" nil single "marmalade" nil nil nil])
  (helm-delicious [cl-struct-package-desc helm-delicious (1 3) "helm extensions for delicious bookmarks" nil single "marmalade" nil nil nil])
  (wedge-ws [cl-struct-package-desc wedge-ws (0 1 2) "Wedge whitespace between columns in text" nil tar "marmalade" nil nil nil])
  (sparkline [cl-struct-package-desc sparkline (0 3 0) "Make sparkline images from a list of numbers" nil single "marmalade" nil nil nil])
  (flymake-puppet [cl-struct-package-desc flymake-puppet (1 0 0) "An Emacs flymake handler for syntax-checking puppet using puppet-lint" ((flymake-easy (0 9))) single "marmalade" nil nil nil])
  (palimpsest [cl-struct-package-desc palimpsest (0 8) "Various deletion strategies when editing" nil single "marmalade" nil nil nil])
  (py-import-check [cl-struct-package-desc py-import-check (0 2) "Finds the unused python imports using importchecker" nil single "marmalade" nil nil nil])
  (cubicle-mode [cl-struct-package-desc cubicle-mode (0 1) "Cubicle major mode for emacs" nil single "marmalade" nil nil nil])
  (pickup [cl-struct-package-desc pickup (0 0 3) "pickup file. " nil single "marmalade" nil nil nil])
  (cobra-mode [cl-struct-package-desc cobra-mode (1 0 1) "Major mode for .NET-based Cobra language" nil single "marmalade" nil nil nil])
  (dummy-package [cl-struct-package-desc dummy-package (0 0 3) "a fake package for the marmalade test suite" ((timeclock (2 6 1))) single "marmalade" nil nil nil])
  (immutant-server [cl-struct-package-desc immutant-server (1 0 1) "Run your Immutant server in Emacs" nil single "marmalade" nil nil nil])
  (initchart [cl-struct-package-desc initchart (0 1 1) "Emacs' init process performance visualization  -*- lexical-binding: t -*-" ((cl-lib (0 3))) single "marmalade" nil nil nil])
  (wisp-mode [cl-struct-package-desc wisp-mode (0 1 5) "Tools for wisp: the Whitespace-to-Lisp preprocessor" nil single "marmalade" nil nil nil])
  (project-explorer [cl-struct-package-desc project-explorer (0 13) "A project explorer sidebar -*- lexical-binding: t -*-" ((cl-lib (0 3)) (es-lib (0 3)) (es-windows (0 1)) (emacs (24))) single "marmalade" nil nil nil])
  (ac-cider-compliment [cl-struct-package-desc ac-cider-compliment (0 1 0) "auto-complete sources for Clojure using" ((cider (0 5 0)) (auto-complete (1 4))) single "marmalade" nil nil nil])
 )
