'(
  (ac-R . [(0 2) nil "Autocompletion routines for R" single "marmalade"])
  (ac-python . [(20110519) ((auto-complete (1 4))) "Simple Python Completion Source for Auto-Complete" single "marmalade"])
  (alert . [(0 5 10) ((string-utils (0 0 2))) "Alternatives to `message'" single "marmalade"])
  (auto-complete-etags . [(0 2) ((auto-complete (1 3))) "Auto-complete etags" single "marmalade"])
  (auto-complete-octave . [(0 1) nil "Auto-complete for Octave" single "marmalade"])
  (auto-complete-verilog . [(0 0) nil "Verukig" single "marmalade"])
  (bbdb2erc . [(0 1 0) nil "make bbdb show if pal is online with ERC, click i to chat" single "marmalade"])
  (cedit . [(0 0 0) nil "paredit-like commands for c-like languages" single "marmalade"])
  (clojure-project . [(1 0) ((project-mode (1 0))) "Extends project-mode for Clojure projects" single "marmalade"])
  (color-theme-tangotango . [(0 0 2) ((color-theme (6 6 1))) "Tango Palette color theme for Emacs." single "marmalade"])
  (ctags . [(1 1 1) nil "Exuberant Ctags utilities for Emacs" single "marmalade"])
  (eh-common . [(0 0 1) nil "Tumashu's  emacs functions" single "marmalade"])
  (electric-case . [(2 2 1) nil "insert camelCase, snake_case words without \"Shift\"ing" single "marmalade"])
  (elscreen . [(1 4 6) nil "Screen for Emacsen" single "marmalade"])
  (erc-nick-notify . [(0 2 1) nil "Notify popup for ERC" single "marmalade"])
  (ess-R-object-popup . [(0 0 4) nil "popup description of R object" single "marmalade"])
  (fiplr . [(0 1 3) nil "Fuzzy finder for files in a project." single "marmalade"])
  (foo . [(3 0 20) ((haml-mode (3 0 20))) "Sass major mode" single "marmalade"])
  (guile-scheme . [(0 1) nil "Guile Scheme editing mode" single "marmalade"])
  (ir-black-theme . [(1 0) nil "Port of ir-black theme" single "marmalade"])
  (jasmin . [(1 2) nil "major editing mode for Jasmin Java bytecode assembler files" single "marmalade"])
  (jcuken-fix . [(1 0) nil "Map Modifier-CyrillicLetter to the underlying Modifier-LatinLetter." single "marmalade"])
  (journal . [(1 2 1) nil "a simple org-mode based journaling mode" single "marmalade"])
  (lang-refactor . [(0 1 1) nil "Simple refactorings, primarily for Perl" single "marmalade"])
  (latest-clojure-libraries . [(0 1) ((nrepl (0 1 7))) "Clojure dependency resolver" single "marmalade"])
  (latex-pretty-symbols . [(1 0) nil "Display many latex symbols as their unicode counterparts" single "marmalade"])
  (layout-restore . [(0 4) nil "keep window configuration as layout and restore it simply." single "marmalade"])
  (linear-undo . [(5 2) nil "Intuitive undo/redo." single "marmalade"])
  (mark . [(0 3) ((fm (1 0))) "Navigate and visualize the mark-ring" single "marmalade"])
  (master-mode . [(0 1) nil "Become an Emacs master" single "marmalade"])
  (mc-jump . [(1 0 0) nil "like \"jump-char\", but \"multiple-cursors\" friendly" single "marmalade"])
  (monky . [(0 1) nil "control Hg from Emacs." single "marmalade"])
  (outlined-elisp-mode . [(1 0 5) nil "outline-minor-mode settings for emacs lisp" single "marmalade"])
  (phi-search . [(1 1 0) nil "inferior isearch compatible with \"multiple-cursors\"" single "marmalade"])
  (php-completion . [(0 3) nil "complete everything PHP with Anything.el" single "marmalade"])
  (pycomplete . [(1 0) nil "Complete symbols at point using Pymacs." single "marmalade"])
  (python-django . [(0 1) nil "A Jazzy package for managing Django projects" single "marmalade"])
  (revive . [(2 19) nil "Resume Emacs." single "marmalade"])
  (scratch-palette . [(1 0 1) nil "add scratch notes for each file" single "marmalade"])
  (scratch-pop . [(1 0 0) nil "popup scratch" single "marmalade"])
  (setup-cygwin . [(21 0) nil "Set up Emacs for using Cygwin" single "marmalade"])
  (slime-scratch . [(1 0 0) ((slime (20100404))) "Imitate Emacs' *scratch* buffer" single "marmalade"])
  (tango-2 . [(1 0 0) nil "Tango 2 color theme for GNU Emacs 24" single "marmalade"])
  (vimpulse . [(0 5) nil "emulates Vim's most useful features" single "marmalade"])
  (viper-in-more-modes . [(0 1 3) nil "vi-like keybindings for various Emacs modes" single "marmalade"])
  (xahk-mode . [(1 2 1) nil "Major mode for editing AHK (Autohotkey) scripts." single "marmalade"])
 )
