'(
  (ac-R . [(0 2) nil "Autocompletion routines for R" single "marmalade"])
  (ac-cider . [(0 2 0) ((cider (0 8 0)) (auto-complete (1 4)) (cl-lib (0 3))) "Clojure auto-complete sources using CIDER" single "marmalade"])
  (ac-cider-compliment . [(0 1 0) ((cider (0 5 0)) (auto-complete (1 4))) "auto-complete sources for Clojure using" single "marmalade"])
  (ac-geiser . [(0 1) ((geiser (0 5)) (auto-complete (1 4))) "Auto-complete backend for geiser" tar "marmalade"])
  (ac-inf-ruby . [(0 4) ((inf-ruby (2 3 2)) (auto-complete (1 4))) "Enable auto-complete in inf-ruby sessions" single "marmalade"])
  (ac-python . [(20110519) ((auto-complete (1 4))) "Simple Python Completion Source for Auto-Complete" single "marmalade"])
  (ample-zen-theme . [(0 2) nil "AmpleZen Theme for Emacs 24" single "marmalade"])
  (anzu . [(0 22) nil "Show number of matches in mode-line while searching" single "marmalade"])
  (aok . [(0 1) nil "various useful ways to do `multi-occur'" single "marmalade"])
  (ariadne . [(0 1) ((bert (0 1))) "Ariadne plugin for Emacs" single "marmalade"])
  (auto-complete-etags . [(0 2) ((auto-complete (1 3))) "Auto-complete etags" single "marmalade"])
  (auto-complete-octave . [(0 1) nil "Auto-complete for Octave" single "marmalade"])
  (auto-complete-verilog . [(0 0) nil "Verukig" single "marmalade"])
  (bbdb2erc . [(0 1 0) nil "make bbdb show if pal is online with ERC, click i to chat" single "marmalade"])
  (bert . [(0 1) nil "BERT serialization library for Emacs" single "marmalade"])
  (bubbleberry-theme . [(0 1 2) ((emacs (24 1))) "A theme based on LightTable for Emacs24" single "marmalade"])
  (buffer-file-utils . [(1 0) nil "utilities operating on a buffer and the associated file" single "marmalade"])
  (cedit . [(0 0 0) nil "paredit-like commands for c-like languages" single "marmalade"])
  (cider . [(0 6 0) ((clojure-mode (2 0 0)) (cl-lib (0 3)) (dash (2 4 1)) (pkg-info (0 4))) "Clojure Integrated Development Environment and REPL" tar "marmalade"])
  (cl-lib-highlight . [(1 0 0) ((cl-lib (0 3))) "full cl-lib font-lock highlighting" single "marmalade"])
  (clojure-env . [(0 0 3) nil "manage clojure environments with Emacs" single "marmalade"])
  (clojure-project . [(1 0) ((project-mode (1 0))) "Extends project-mode for Clojure projects" single "marmalade"])
  (cmuclojure . [(0 2) nil "Clojure process in a buffer" single "marmalade"])
  (cobra-mode . [(1 0 1) nil "Major mode for .NET-based Cobra language" single "marmalade"])
  (color-theme-tangotango . [(0 0 2) ((color-theme (6 6 1))) "Tango Palette color theme for Emacs." single "marmalade"])
  (color-theme-zenburn . [(0 3) ((color-theme (6 6 1))) "A low contrast color theme for Emacs." single "marmalade"])
  (comint-better-defaults . [(1 0) nil "better defaults for comint-derived modes" single "marmalade"])
  (creds . [(0 0 6 1) ((s (1 9 0)) (dash (2 5 0))) "A parser credentials file library (not limited to credentials entries)" tar "marmalade"])
  (ctags . [(1 1 1) nil "Exuberant Ctags utilities for Emacs" single "marmalade"])
  (cubicle-mode . [(0 1) nil "Cubicle major mode for emacs" single "marmalade"])
  (dash-functional . [(1 2 0) ((dash (2 0 0)) (emacs (24))) "Collection of useful combinators for Emacs Lisp" single "marmalade"])
  (dired-nav-enhance . [(1 0) nil "Enhanced navigation for dired buffers" single "marmalade"])
  (dirtrack-buffer-name-track-mode . [(1 0 0) nil "minor mode to cause shell buffers to reflect the working directory" single "marmalade"])
  (discord . [(0 5) nil "Discordian dates for calendar" single "marmalade"])
  (downplay-mode . [(0 1) nil "focus attention on a region of the buffer" single "marmalade"])
  (dummy-package . [(0 0 23) ((timeclock (2 6 1))) "a fake package for the marmalade test suite" single "marmalade"])
  (eh-common . [(0 0 1) nil "Tumashu's  emacs functions" single "marmalade"])
  (el-init . [(20130416) nil "Loader for configuration files" tar "marmalade"])
  (eldoro . [(0 1 0) nil "A pomodoro timer/tracker that works with org-mode." tar "marmalade"])
  (electric-case . [(2 2 1) nil "insert camelCase, snake_case words without \"Shift\"ing" single "marmalade"])
  (elfeed . [(1 1 0) ((emacs (24 1))) "an Emacs Atom/RSS feed reader" tar "marmalade"])
  (elfeed-web . [(1 1 0) ((simple-httpd (1 4 3)) (elfeed (1 0 1)) (emacs (24 1))) "web interface to Elfeed" tar "marmalade"])
  (elisp-indexer . [(0 0 7) nil "indexing utils for emacslisp" single "marmalade"])
  (elpa-mirror . [(1 1 2) nil "ELPA mirror from locally installed packages is easy" tar "marmalade"])
  (elscreen . [(1 4 6) nil "Screen for Emacsen" single "marmalade"])
  (emacs-cl . [(0 5) nil "Emacs Common Lisp" tar "marmalade"])
  (emacs-xkcd . [(1 0) ((json (1 4))) "View xkcd from Emacs" single "marmalade"])
  (env-var-import . [(2 1) nil "Import shell environment variables in GUI Emacs" single "marmalade"])
  (epl . [(0 7) ((cl-lib (0 3))) "Emacs Package Library" single "marmalade"])
  (eprime-mode . [(1 1 2) nil "An E-prime checking mode for Emacs" single "marmalade"])
  (erc-nick-notify . [(0 2 1) nil "Notify popup for ERC" single "marmalade"])
  (ertx . [(0 0 1) nil "Extra useful testing functions for EmacsLisp." single "marmalade"])
  (es-windows . [(0 2) ((cl-lib (0 3)) (emacs (24))) "Window-management utilities" single "marmalade"])
  (eshell-fringe-status . [(1 0 0) nil "Show last status in fringe" single "marmalade"])
  (ess-R-object-popup . [(0 0 6) nil "popup description of R object" single "marmalade"])
  (evil-indent-textobject . [(0 2) ((evil (0))) "evil textobjects based on indentation" single "marmalade"])
  (evil-matchit . [(1 3 0) nil "Vim matchit ported into Emacs (requires EVIL)" tar "marmalade"])
  (exercism . [(0 0 1) nil "An Emacs mode for submitting current file to exercism.io" single "marmalade"])
  (eyebrowse . [(0 3 2) ((dash (2 7 0))) "Easy window config switching" single "marmalade"])
  (f . [(0 11 0) ((s (1 7 0)) (dash (2 2 0))) "Modern API for working with files and directories" single "marmalade"])
  (fancy-battery . [(0 2) ((emacs (24 1))) "Fancy battery display" single "marmalade"])
  (file-format . [(0 0 4) ((s (1 5 0))) "templates with files as the source" single "marmalade"])
  (finalize . [(1 0 0) ((emacs (24 1)) (cl-lib (0 3)) (eieio (1 4))) "finalizers for Emacs Lisp" tar "marmalade"])
  (fiplr . [(0 1 3) nil "Fuzzy finder for files in a project." single "marmalade"])
  (fit-frame . [(0) nil "Resize a frame.  In particular, fit a frame to its buffers." single "marmalade"])
  (fixme-mode . [(1 0 2) nil "fixme minor mode to highlight warning words" single "marmalade"])
  (flatland-theme . [(0 1 2) nil "A simple theme for Emacs." single "marmalade"])
  (flycheck-cask . [(0 1) ((flycheck (0 14)) (dash (2 0 0)) (f (0 6 0))) "Cask support in Flycheck" single "marmalade"])
  (flycheck-haskell . [(0 4) ((flycheck (0 16)) (haskell-mode (13 7)) (dash (2 4 0)) (f (0 11 0))) "Flycheck: Cabal projects and sandboxes" tar "marmalade"])
  (flycheck-hdevtools . [(0 2) ((flycheck (0 15))) "A flycheck checker for Haskell using hdevtools" single "marmalade"])
  (flycheck-ledger . [(0 2) ((flycheck (0 15))) "Flycheck integration for ledger files" single "marmalade"])
  (flycheck-tcl . [(0 4) ((flycheck (0 17))) "A flycheck checker for Tcl using ActiveState's tclchecker" single "marmalade"])
  (flymake-puppet . [(1 0 0) ((flymake-easy (0 9))) "An Emacs flymake handler for syntax-checking puppet using puppet-lint" single "marmalade"])
  (flymake-racket . [(0 40) ((flymake-easy (0 1))) "A flymake handler for scheme-mode files" single "marmalade"])
  (garoon . [(0 0 1) nil "A Garoon client." single "marmalade"])
  (gecf . [(0 1 0) nil "G\366ktu's Emacs configuration framework." single "marmalade"])
  (gerrit-download . [(0 2) ((magit (20130828 1540))) "Show gerrit reviews in a diff buffer." single "marmalade"])
  (git-draft . [(0 0 2) ((dash (2 9 0))) "draft git commit messages" single "marmalade"])
  (gnus-summary-ext . [(0 1) ((macro-utils (1 0))) "Extra limit and process mark commands for the gnus summary buffer" single "marmalade"])
  (god-mode . [(2 12 0) nil "God-like command entering minor mode" single "marmalade"])
  (goto-chg . [(1 6) nil "goto last change" single "marmalade"])
  (gratuitous-dark-theme . [(1 3) nil "A theme originally by 'cofi' from #emacs, Freenode. It is a combination of Monokai and several other themes. The modeline has been modelled after AwesomeWM because it looks cool." single "marmalade"])
  (guile-scheme . [(0 1) nil "Guile Scheme editing mode" single "marmalade"])
  (gvpr-mode . [(0 1 0) nil "A major mode offering basic syntax coloring for gvpr scripts." single "marmalade"])
  (helm-dash . [(1 1) ((helm (0 0 0))) "Helm extension to search dash docsets" single "marmalade"])
  (helm-delicious . [(1 3) nil "helm extensions for delicious bookmarks" single "marmalade"])
  (helm-helm-commands . [(0 2) ((helm (1 5 4))) "List all helm commands with helm" single "marmalade"])
  (heroku-theme . [(1 1 0) nil "Heroku color theme" single "marmalade"])
  (highlight-current-line . [(0 57) nil "highlight line where the cursor is." single "marmalade"])
  (highlight-sexp . [(1 0) nil "highlight current zone according to its context" single "marmalade"])
  (hl-spotlight . [(0) nil "Extension of hl-line.el to spotlight current few lines." single "marmalade"])
  (how-many-lines-in-project . [(0 3) ((find-file-in-project (3 3))) "Calculate how many lines are there in your project." single "marmalade"])
  (iasm-mode . [(0 1) nil "interactive assembly major mode." single "marmalade"])
  (ido-select-window . [(0 1 0) nil "Select a window using ido and buffer names." tar "marmalade"])
  (ido-vertical-mode . [(0 1 1) nil "Makes ido-mode display vertically." single "marmalade"])
  (immutant-server . [(1 0 1) nil "Run your Immutant server in Emacs" single "marmalade"])
  (initchart . [(0 1 1) ((cl-lib (0 3))) "Emacs' init process performance visualization" single "marmalade"])
  (insert-shebang . [(0 9 3) nil "Insert shebang line automatically." single "marmalade"])
  (ir-black-theme . [(1 0) nil "Port of ir-black theme" single "marmalade"])
  (iregister . [(0 5 0) nil "Interactive register commands for Emacs." tar "marmalade"])
  (isearch-switch . [(1 0) nil "switch the manner you are isearching in." single "marmalade"])
  (isgd . [(20130927) nil "Shorten URLs using the isgd.com shortener service" single "marmalade"])
  (ix . [(0 7) ((grapnel (0 5 3))) "Emacs client for http://ix.io pastebin" single "marmalade"])
  (jam-mode . [(0 3) nil "Font-lock support for Jam files" single "marmalade"])
  (jasmin . [(1 2) nil "major editing mode for Jasmin Java bytecode assembler files" single "marmalade"])
  (java-file-create . [(1 0) nil "automatically insert contents of empty java files" single "marmalade"])
  (jcuken-fix . [(1 0) nil "Map Modifier-CyrillicLetter to the underlying Modifier-LatinLetter." single "marmalade"])
  (journal . [(1 2 1) nil "a simple org-mode based journaling mode" single "marmalade"])
  (json-snatcher . [(1 0) nil "Grabs the path to JSON values in a JSON file." single "marmalade"])
  (jujube-theme . [(0 1) nil "Pastel theme loosely based on jellybeans" single "marmalade"])
  (jump-dls . [(0 5) nil "Jump to definition of symbol using various methods." single "marmalade"])
  (lang-refactor . [(0 1 1) nil "Simple refactorings, primarily for Perl" single "marmalade"])
  (latest-clojure-libraries . [(0 5) nil "Clojure dependency resolver" single "marmalade"])
  (latex-pretty-symbols . [(1 0) nil "Display many latex symbols as their unicode counterparts" single "marmalade"])
  (latex-preview-pane . [(20140205) nil "Makes LaTeX editing less painful by providing a updatable preview pane" tar "marmalade"])
  (layout-restore . [(0 4) nil "keep window configuration as layout and restore it simply." single "marmalade"])
  (linear-undo . [(5 2) nil "Intuitive undo/redo." single "marmalade"])
  (linky-client . [(0 0 2) nil "a client for linky.elnode.org" single "marmalade"])
  (list-register . [(2 2) nil "List register" single "marmalade"])
  (livecoder . [(0 0 2) nil "tools for live coders" single "marmalade"])
  (livid-mode . [(0 1 0) ((skewer-mode (1 5 3)) (s (1 8 0))) "Live browser eval of JavaScript every time a buffer changes" single "marmalade"])
  (lxc . [(0 0 2) nil "lxc integration with Emacs" single "marmalade"])
  (lyskom . [(20131008) nil "LysKOM elisp client." single "marmalade"])
  (magit-find-file . [(1 0 4) ((magit (1 2 0))) "completing-read over all files in Git" single "marmalade"])
  (magit-tramp . [(0 1 0) ((magit (1 2 0))) "git method for TRAMP" single "marmalade"])
  (mainline . [(1 1 0) nil "modeline replacement forked from an early version of powerline.el" single "marmalade"])
  (mark . [(0 3) ((fm (1 0))) "Navigate and visualize the mark-ring" single "marmalade"])
  (markdown-toc . [(0 0 6) ((markdown-mode (2 0)) (dash (2 5 0)) (s (1 7 0))) "A simple TOC generator for markdown file" single "marmalade"])
  (marmalade-client . [(0 0 9) ((web (0 4 2)) (kv (0 0 19))) "client for marmalade API from emacs" single "marmalade"])
  (marmalade-demo . [(0 0 5) nil "a demonstration elpa package" single "marmalade"])
  (marmalade-upload . [(0 0 5) ((web (0 4 2)) (kv (0 0 19))) "upload client for marmalade from emacs" single "marmalade"])
  (master-mode . [(0 1) nil "Become an Emacs master" single "marmalade"])
  (math-at-point . [(0 0 1) nil "Utilities for modifying numbers at point" single "marmalade"])
  (mc-jump . [(1 0 0) nil "like \"jump-char\", but \"multiple-cursors\" friendly" single "marmalade"])
  (memoize . [(1 0 1) nil "Memoization functions" single "marmalade"])
  (message-templ . [(0 1 20141026) nil "Templates for message-mode." single "marmalade"])
  (minitest . [(0 5) ((dash (1 0 0))) "An Emacs mode for ruby minitest files" single "marmalade"])
  (monky . [(0 1) nil "control Hg from Emacs." single "marmalade"])
  (move-line . [(0 0 1) nil "utilities for moving lines in file" single "marmalade"])
  (multi . [(2 0 1) ((emacs (24))) "Clojure-style multi-methods for emacs lisp" single "marmalade"])
  (mv-shell . [(1 2) nil "keep buffers in sync with filename throughout 'mv'commands in shell-mode." single "marmalade"])
  (navigate . [(0 1 5) nil "Seamlessly navigate between Emacs and tmux" single "marmalade"])
  (nose-mode . [(0 1) ((nose (0 1 1))) "Minor mode for running nose tests." tar "marmalade"])
  (nrepl-discover . [(0 0 1) nil "Client to load commands from nrepl server" single "marmalade"])
  (nssh-n . [(0 9 8) nil "SSH mode for Emacs" single "marmalade"])
  (om-mode . [(0 5 20140916) nil "Insert Om component template with life cycle." single "marmalade"])
  (openstack-cgit-browse-file . [(0 2) nil "Browse the current file in OpenStack cgit" single "marmalade"])
  (operate-on-number . [(1 1 0) nil "Operate on number at point with arithmetic functions" single "marmalade"])
  (org-gnome . [(0 1) ((notify (2010 8 20)) (telepathy (0 1))) "Orgmode integration with the GNOME desktop" single "marmalade"])
  (org-publish-agenda . [(1 7) nil "Publish org agenda with links to other files" single "marmalade"])
  (org2nikola . [(0 0 8) nil "export html and meta data used by static blog like nikola from org file" tar "marmalade"])
  (osx-pseudo-daemon . [(1 0) nil "Daemon mode that plays nice with OSX." single "marmalade"])
  (outlined-elisp-mode . [(1 0 5) nil "outline-minor-mode settings for emacs lisp" single "marmalade"])
  (palimpsest . [(0 8) nil "Various deletion strategies when editing" single "marmalade"])
  (palimpsest-mode . [(0 8) nil "Various deletion strategies when editing" single "marmalade"])
  (parenface2 . [(1 1) nil "Provide a face for parens in lisp modes." single "marmalade"])
  (pbcopy . [(0 1 0) nil "OS X clipboard integration for Emacs" single "marmalade"])
  (phi-search . [(1 1 0) nil "inferior isearch compatible with \"multiple-cursors\"" single "marmalade"])
  (php-completion . [(0 3) nil "complete everything PHP with Anything.el" single "marmalade"])
  (pickup . [(0 0 3) nil "pickup file." single "marmalade"])
  (pinboard-api . [(0 1) nil "Rudimentary http://pinboard.in integration" single "marmalade"])
  (pkg-info . [(0 5) ((dash (1 6 0)) (epl (0 4))) "Information about packages" single "marmalade"])
  (pkg-info-dummy-package . [(3 4 2 1) nil "pkg-info: Dummy package for unit tests" single "marmalade"])
  (project-explorer . [(0 13) ((cl-lib (0 3)) (es-lib (0 3)) (es-windows (0 1)) (emacs (24))) "A project explorer sidebar" single "marmalade"])
  (proxy-mode . [(0 9) nil "Provides proxy minor mode." single "marmalade"])
  (ps-ccrypt . [(1 10) nil "reading/writing/loading encrypted files" tar "marmalade"])
  (py-import-check . [(0 2) nil "Finds the unused python imports using importchecker" single "marmalade"])
  (pycomplete . [(1 0) nil "Complete symbols at point using Pymacs." single "marmalade"])
  (python-django . [(0 1) nil "A Jazzy package for managing Django projects" single "marmalade"])
  (pyvenv . [(1 4) nil "Python virtual environment interface" single "marmalade"])
  (relax . [(0 2) ((json (1 2))) "For browsing and interacting with CouchDB" single "marmalade"])
  (revive . [(2 19) nil "Resume Emacs." single "marmalade"])
  (scratch-palette . [(1 0 1) nil "add scratch notes for each file" single "marmalade"])
  (scratch-pop . [(1 0 0) nil "popup scratch" single "marmalade"])
  (sedated . [(1 0) nil "A few extremely simple sed functions for familiar text manipulation" single "marmalade"])
  (sensitive . [(1 0 1) ((emacs (24)) (sequences (0 1 0))) "A dead simple way to load sensitive information" single "marmalade"])
  (sequences . [(0 1 0) ((emacs (24))) "Ports of some Clojure sequence functions." single "marmalade"])
  (setup-cygwin . [(21 0) nil "Set up Emacs for using Cygwin" single "marmalade"])
  (shell-pop . [(0 3) nil "helps you to use shell easily on Emacs. Only one key action to work." single "marmalade"])
  (simple-httpd . [(1 4 5) ((cl-lib (0 3))) "pure elisp HTTP server" single "marmalade"])
  (skewer-less . [(0 2) ((skewer-mode (1 5 3))) "Skewer support for live LESS stylesheet updates" single "marmalade"])
  (skewer-mode . [(1 6 0) ((simple-httpd (1 4 0)) (js2-mode (20090723)) (emacs (24))) "live browser JavaScript, CSS, and HTML interaction" tar "marmalade"])
  (slime-scratch . [(1 0 0) ((slime (20100404))) "Imitate Emacs' *scratch* buffer" single "marmalade"])
  (smart-whitespace-comment-fixup . [(1 1) nil "Enables advice around yanking/killing lines that auto-indents and formats properly" single "marmalade"])
  (smtpmail-multi . [(0 6) nil "Use different smtp servers for sending mail" single "marmalade"])
  (snakehump . [(0 1 1) nil "Convert between compound word conventions" tar "marmalade"])
  (sparkline . [(0 3 0) nil "Make sparkline images from a list of numbers" single "marmalade"])
  (steady-theme . [(0 1 0) nil "A steady theme for Emacs" single "marmalade"])
  (subatomic-theme . [(1 6 0) nil "Low contrast bluish color theme" single "marmalade"])
  (sudo-edit . [(0 0 1) nil "Utilities for opening files with sudo" single "marmalade"])
  (tango-2 . [(1 0 0) nil "Tango 2 color theme for GNU Emacs 24" single "marmalade"])
  (tbemail . [(0 2) nil "Provide syntax highlighting for email editing via" single "marmalade"])
  (tdd . [(1 0) nil "recompile on save and indicate success in the mode line" single "marmalade"])
  (tdd-status-mode-line . [(0 1 2) nil "TDD status on the mode-line" single "marmalade"])
  (telepathy . [(0 1) nil "Access Telepathy from Emacs" single "marmalade"])
  (timestamper . [(0 1 0) nil "A minor mode for easy timelogging" single "marmalade"])
  (toggle-test . [(1 0 2) nil "Toggle between source and test files in various programming languages" single "marmalade"])
  (tommyh-theme . [(1 2) nil "A bright, bold-colored theme for emacs." single "marmalade"])
  (tox . [(20130819 1127) nil "Launch current python test with tox." single "marmalade"])
  (troncle . [(0 1 2) ((cider (0 5 0))) "Emacs convenience functions for tracing clojure code" single "marmalade"])
  (tronesque-theme . [(1 5) nil "Color Theme based on Tron universe." single "marmalade"])
  (tsql . [(1 0) nil "customizes sql.el for T-SQL" single "marmalade"])
  (typescript . [(0 1 1) nil "Major mode for editing typescript" single "marmalade"])
  (uzumaki . [(0 1) ((cl-lib (0 5))) "A simple buffer cycler" single "marmalade"])
  (vc-tfs . [(0 1 2) nil "Support for TFS version control system" single "marmalade"])
  (vimpulse . [(0 5) nil "emulates Vim's most useful features" single "marmalade"])
  (viper-in-more-modes . [(0 1 3) nil "vi-like keybindings for various Emacs modes" single "marmalade"])
  (waher-theme . [(20130917 7) ((emacs (24 1))) "Emacs 24 theme based on waher for st2 by dduckster" single "marmalade"])
  (wedge-ws . [(0 1 2) nil "Wedge whitespace between columns in text" tar "marmalade"])
  (whitespace-cleanup-mode . [(0 8) nil "Intelligently call whitespace-cleanup on save" single "marmalade"])
  (window-margin . [(0 1) nil "automatic margins for visual-line-mode wrapping" single "marmalade"])
  (winpoint-ignore-dired . [(1 1) ((winpoint (1 0))) "Have winpoint ignore dired-mode buffers" single "marmalade"])
  (wisp . [(0 1 4) nil "Tools for wisp: the Whitespace-to-Lisp preprocessor" single "marmalade"])
  (wisp-mode . [(0 1 5) nil "Tools for wisp: the Whitespace-to-Lisp preprocessor" single "marmalade"])
  (wonderland . [(0 1 1) ((dash (2 0 0)) (dash-functional (1 0 0)) (multi (2 0 0)) (emacs (24))) "declarative configuration for Emacsen" single "marmalade"])
  (xkcd . [(1 0) ((json (1 4))) "View xkcd from Emacs" single "marmalade"])
  (zeal-at-point . [(0 0 3) nil "Search the word at point with Zeal" single "marmalade"])
  (zenburn . [(0 1) nil "A low contrast colour theme for Emacs" single "marmalade"])
  (zone-matrix . [(0 0 1) nil "Matrix themed Zone mode" tar "marmalade"])
  (monroe . [(0 2 0) nil "Yet another client for nREPL" single "marmalade"])
 )
