'(
  (tsql . [(1 0) nil "customizes sql.el for T-SQL" single "marmalade"])
  (frame-restore . [(0 3) ((dash (1 2)) (f (0 4 1)) (emacs (24 1))) "Restore Emacs frame -*- lexical-binding: t; -*-" single "marmalade"])
  (ample-theme . [(0 11) ((color-theme (6 6 5))) "Calm Dark Theme for Emacs" single "marmalade"])
  (emmet-mode . [(1 0 1) nil "Unofficial Emmet's support for emacs" single "marmalade"])
  (processing-mode . [(1 1 1) nil "Major mode for Processing 2.0" single "marmalade"])
  (git-gutter+ . [(0 2) nil "Manage Git hunks straight from the buffer" single "marmalade"])
  (remember-theme . [(20130807 1251) nil "Remembers the last theme in use and re-loads for the next session." single "marmalade"])
  (org-trello . [(0 1 0) ((org (8 0 7)) (dash (1 4 0)) (request (0 1 0)) (cl-lib (0 3 0)) (json (1 2))) "Minor mode for org-mode to sync org-mode and trello" tar "marmalade"])
  (syslog-mode . [(2 1) ((hide-lines (20130623))) "Major-mode for viewing log files" single "marmalade"])
  (desktop-registry . [(1 1 0) nil "Keep a central registry of desktop files -*- lexical-binding: t -*-" single "marmalade"])
  (show-marks . [(0 4) ((fm (1 0))) "Navigate and visualize the mark-ring" single "marmalade"])
  (evil-leader . [(0 3 4) ((evil (0))) "let there be <leader>" single "marmalade"])
  (ag . [(0 24) nil "A front-end for ag ('the silver searcher'), the C ack replacement." single "marmalade"])
  (groovy-mode . [(201203310931) nil "Groovy mode derived mode" single "marmalade"])
  (psgml . [(1 4 1) nil "Lennart Staflin's Psgml package, with Elisp syntax and sgml-validate fixed for Emacsen >=24." tar "marmalade"])
  (smartparens . [(1 5) ((cl-lib (0 1)) (dash (1 1 0))) "Automatic insertion, wrapping and paredit-like navigation with user defined pairs." tar "marmalade"])
  (evil . [(1 0 7) ((undo-tree (0 5 1))) "Extensible Vi layer for Emacs." tar "marmalade"])
  (rbenv . [(0 0 3) nil "Emacs integration for rbenv" single "marmalade"])
  (creole . [(1 0 3) ((noflet (0 0 3)) (kv (0 0 17))) "A parser for the Creole Wiki language" single "marmalade"])
  (robe . [(0 7 6) ((inf-ruby (2 3 0))) "Code navigation, documentation lookup and completion for Ruby" tar "marmalade"])
  (evil-nerd-commenter . [(0 0 9) nil "Comment/uncomment lines efficiently. Like Nerd Commenter in Vim" tar "marmalade"])
  (cpputils-cmake . [(0 4 0) nil "Easy real time C++ syntax check and intellisense if you use CMake." tar "marmalade"])
  (elpy . [(1 1) ((auto-complete (1 4)) (fuzzy (0 1)) (yasnippet (0 8)) (virtualenv (1 2)) (highlight-indentation (0 5 0)) (find-file-in-project (3 2)) (idomenu (0 1)) (nose (0 1 1)) (iedit (0 97))) "Emacs Lisp Python Environment" tar "marmalade"])
  (auto-indent-mode . [(0 103) nil "Auto indent Minor mode" single "marmalade"])
  (lispyscript-mode . [(0 3 0) nil "Major mode for LispyScript code." single "marmalade"])
  (git-commit-mode . [(0 13) nil "Major mode for editing git commit messages -*- lexical-binding: t; -*-" single "marmalade"])
  (exec-path-from-shell . [(1 6) nil "Get environment variables such as $PATH from the shell" single "marmalade"])
  (fill-column-indicator . [(1 85) nil "Graphically indicate the fill column" single "marmalade"])
  (nrepl . [(0 1 8) ((clojure-mode (2 0 0)) (cl-lib (0 3))) "Client for Clojure nREPL" single "marmalade"])
  (android-mode . [(0 2 4) nil "Minor mode for Android application development" single "marmalade"])
 )
