'(
  (smart-whitespace-comment-fixup . [(1 0) nil "Enables advice around yanking/killing lines that auto-indents and formats properly" single "marmalade"])
  (figlet . [(289) nil "banner generator" single "marmalade"])
  (smtpmail-multi . [(0 3) nil "Use different smtp servers for sending mail" single "marmalade"])
  (insert-shebang . [(0 9 1) nil "Inserts shebang line automatically" tar "marmalade"])
  (tronesque-theme . [(1 3) nil "Color Theme based on Tron universe." single "marmalade"])
  (openstack-cgit-browse-file . [(0 2) nil "Browse the current file in OpenStack cgit" single "marmalade"])
  (flycheck-cask . [(0 1) ((flycheck (0 14)) (dash (2 0 0)) (f (0 6 0))) "Cask support in Flycheck -*- lexical-binding: t; -*-" single "marmalade"])
  (dash-functional . [(1 0 0) ((dash (2 0 0)) (emacs (24))) "Collection of useful combinators for Emacs Lisp  -*- lexical-binding: t -*-" single "marmalade"])
  (pkg-info . [(0 1) ((dash (1 6 0)) (s (1 6 0))) "Information about packages       -*- lexical-binding: t; -*-" single "marmalade"])
  (f . [(0 6 0) ((s (1 6 1)) (dash (1 5 0))) "Modern API for working with files and directories" single "marmalade"])
  (aok . [(0 1) nil "various useful ways to do `multi-occur'" single "marmalade"])
  (magit-tramp . [(0 1 0) ((magit (1 2 0))) "git method for TRAMP" single "marmalade"])
  (helm-recoll . [(20130815 0) ((helm (20130806 1505))) "helm interface for the recoll desktop search tool." single "marmalade"])
  (god-mode . [(2 7 0) nil "God-like command entering minor mode" single "marmalade"])
  (heroku-theme . [(1 1 0) nil "Heroku color theme" single "marmalade"])
  (wisp-mode . [(0 1 2) nil "Major mode for editing wisp: Whitespace-to-Lisp" single "marmalade"])
  (tsql . [(1 0) nil "customizes sql.el for T-SQL" single "marmalade"])
  (frame-restore . [(0 3) ((dash (1 2)) (f (0 4 1)) (emacs (24 1))) "Restore Emacs frame -*- lexical-binding: t; -*-" single "marmalade"])
  (ample-theme . [(0 11) ((color-theme (6 6 5))) "Calm Dark Theme for Emacs" single "marmalade"])
  (emmet-mode . [(1 0 2) nil "Unofficial Emmet's support for emacs" single "marmalade"])
  (web-mode . [(6 0 31) nil "major mode for editing html templates" single "marmalade"])
  (processing-mode . [(1 2 0) nil "Major mode for Processing 2.0" single "marmalade"])
  (git-gutter+ . [(0 2) nil "Manage Git hunks straight from the buffer" single "marmalade"])
  (remember-theme . [(20130807 1251) nil "Remembers the last theme in use and re-loads for the next session." single "marmalade"])
  (org-trello . [(0 1 5) ((org (8 0 7)) (dash (1 5 0)) (request (0 2 0)) (cl-lib (0 3 0)) (json (1 2)) (elnode (0 9 9 7 6)) (esxml (0 3 0))) "Org minor mode to synchronize with trello" tar "marmalade"])
  (syslog-mode . [(2 1) ((hide-lines (20130623))) "Major-mode for viewing log files" single "marmalade"])
  (org-journal . [(1 4 2) nil "a simple org-mode based journaling mode" single "marmalade"])
  (desktop-registry . [(1 1 0) nil "Keep a central registry of desktop files -*- lexical-binding: t -*-" single "marmalade"])
  (show-marks . [(0 4) ((fm (1 0))) "Navigate and visualize the mark-ring" single "marmalade"])
  (evil-leader . [(0 3 4) ((evil (0))) "let there be <leader>" single "marmalade"])
  (ag . [(0 24) nil "A front-end for ag ('the silver searcher'), the C ack replacement." single "marmalade"])
  (groovy-mode . [(201203310931) nil "Groovy mode derived mode" single "marmalade"])
  (flymake-elixir . [(0 5) nil "A flymake handler for elixir-mode .ex files.     " single "marmalade"])
  (psgml . [(1 4 1) nil "Lennart Staflin's Psgml package, with Elisp syntax and sgml-validate fixed for Emacsen >=24." tar "marmalade"])
  (smartparens . [(1 5) ((cl-lib (0 1)) (dash (1 1 0))) "Automatic insertion, wrapping and paredit-like navigation with user defined pairs." tar "marmalade"])
  (evil . [(1 0 7) ((undo-tree (0 5 1))) "Extensible Vi layer for Emacs." tar "marmalade"])
  (rbenv . [(0 0 3) nil "Emacs integration for rbenv" single "marmalade"])
  (creole . [(1 0 3) ((noflet (0 0 3)) (kv (0 0 17))) "A parser for the Creole Wiki language" single "marmalade"])
  (robe . [(0 7 6) ((inf-ruby (2 3 0))) "Code navigation, documentation lookup and completion for Ruby" tar "marmalade"])
  (evil-nerd-commenter . [(1 2 0) nil "Comment/uncomment lines efficiently. Like Nerd Commenter in Vim" tar "marmalade"])
  (cpputils-cmake . [(0 4 0) nil "Easy real time C++ syntax check and intellisense if you use CMake." tar "marmalade"])
  (flycheck . [(0 14 1) ((s (1 6 0)) (dash (1 6 0)) (f (0 5 0)) (cl-lib (0 1)) (emacs (24 1))) "On-the-fly syntax checking (Flymake done right)" tar "marmalade"])
  (elpy . [(1 1) ((auto-complete (1 4)) (fuzzy (0 1)) (yasnippet (0 8)) (virtualenv (1 2)) (highlight-indentation (0 5 0)) (find-file-in-project (3 2)) (idomenu (0 1)) (nose (0 1 1)) (iedit (0 97))) "Emacs Lisp Python Environment" tar "marmalade"])
  (auto-indent-mode . [(0 107) nil "Auto indent Minor mode" single "marmalade"])
  (flymake-coffee . [(0 11) ((flymake-easy (0 1))) "A flymake handler for coffee script" single "marmalade"])
  (lispyscript-mode . [(0 3 0) nil "Major mode for LispyScript code." single "marmalade"])
  (dash . [(2 1 0) nil "A modern list library for Emacs" single "marmalade"])
  (git-commit-mode . [(0 13) nil "Major mode for editing git commit messages -*- lexical-binding: t; -*-" single "marmalade"])
  (s . [(1 7 0) nil "The long lost Emacs string manipulation library." single "marmalade"])
  (exec-path-from-shell . [(1 6) nil "Get environment variables such as $PATH from the shell" single "marmalade"])
  (fill-column-indicator . [(1 85) nil "Graphically indicate the fill column" single "marmalade"])
  (nrepl . [(0 1 8) ((clojure-mode (2 0 0)) (cl-lib (0 3))) "Client for Clojure nREPL" single "marmalade"])
  (android-mode . [(0 2 4) nil "Minor mode for Android application development" single "marmalade"])
  (ack-and-a-half . [(1 2 0) nil "Yet another front-end for ack" single "marmalade"])
  (ido-ubiquitous . [(1 7) nil "Use ido (nearly) everywhere." single "marmalade"])
  (yaml-mode . [(0 0 9) nil "Major mode for editing YAML files" single "marmalade"])
 )
