'(
  (org2nikola . [(0 0 4) nil "export html and meta data used by static blog like nikola from org file" tar "marmalade"])
  (elpa-mirror . [(1 1 2) nil "ELPA mirror from locally installed packages is easy" tar "marmalade"])
  (flycheck-haskell . [(0 4) ((flycheck (0 16)) (haskell-mode (13 7)) (dash (2 4 0)) (f (0 11 0))) "Flycheck: Cabal projects and sandboxes" tar "marmalade"])
  (iregister . [(0 2 1) nil "Interactive register commands for Emacs." single "marmalade"])
  (epl . [(0 7) ((cl-lib (0 3))) "Emacs Package Library -*- lexical-binding: t; -*-" single "marmalade"])
  (creds . [(0 0 4) nil "a simple parser credential file lib" tar "marmalade"])
  (flycheck-tcl . [(0 4) ((flycheck (0 17))) "A flycheck checker for Tcl using ActiveState's tclchecker" single "marmalade"])
  (latex-preview-pane . [(20140204) nil "Makes LaTeX editing less painful by providing a updatable preview pane. Full documentation can be found at: http://www.emacswiki.org/emacs/LaTeXPreviewPane" tar "marmalade"])
  (lxc . [(0 0 1) nil "lxc integration with Emacs" single "marmalade"])
  (eshell-fringe-status . [(1 0 0) nil "Show last status in fringe  -*- lexical-binding: t; -*-" single "marmalade"])
  (finalize . [(1 0 0) ((emacs (24 1)) (cl-lib (0 3)) (eieio (1 4))) "finalizers for Emacs Lisp" tar "marmalade"])
  (gecf . [(0 1 0) nil "G\303\266ktu\304\237's Emacs configuration framework." single "marmalade"])
  (elfeed . [(1 1 0) ((emacs (24 1))) "an Emacs Atom/RSS feed reader" tar "marmalade"])
  (memoize . [(1 0 1) nil "Memoization functions -*- lexical-binding: t; -*-" single "marmalade"])
  (cl-lib-highlight . [(1 0 0) ((cl-lib (0 3))) "full cl-lib font-lock highlighting" single "marmalade"])
  (skewer-mode . [(1 6 0) ((simple-httpd (1 4 0)) (js2-mode (20090723)) (emacs (24))) "live browser JavaScript, CSS, and HTML interaction" tar "marmalade"])
  (simple-httpd . [(1 4 5) ((cl-lib (0 3))) "pure elisp HTTP server" single "marmalade"])
  (es-windows . [(0 2) ((cl-lib (0 3)) (emacs (24))) "Window-management utilities -*- lexical-binding: t -*-" single "marmalade"])
  (exercism . [(0 0 1) nil "An Emacs mode for submitting current file to exercism.io" single "marmalade"])
  (xkcd . [(1 0) ((json (1 4))) "View xkcd from Emacs" single "marmalade"])
  (cider . [(0 5 0) ((clojure-mode (2 0 0)) (cl-lib (0 3)) (dash (2 4 1)) (pkg-info (0 4))) "Clojure Integrated Development Environment and REPL" tar "marmalade"])
  (pyvenv . [(1 1) nil "Python virtual environment interface -*- lexical-binding: t -*-" single "marmalade"])
  (toggle-test . [(1 0 1) nil "Toggle between source and test files. It is language agnostic and creates source/test files if they don't exist." single "marmalade"])
  (jam-mode . [(0 3) nil "Font-lock support for Jam files" single "marmalade"])
  (nose-mode . [(0 1) ((nose (0 1 1))) "Minor mode for running nose tests." tar "marmalade"])
  (downplay-mode . [(0 1) nil "focus attention on a region of the buffer" single "marmalade"])
  (steady-theme . [(0 1 0) nil "A steady theme for Emacs  -*- lexical-binding: t -*-" single "marmalade"])
  (insert-shebang . [(0 9 3) nil "Insert shebang line automatically." single "marmalade"])
  (wisp . [(0 1 3) nil "Supporting tools for editing wisp: The Whitespace-to-Lisp preprocesor" single "marmalade"])
  (goto-chg . [(1 6) nil "goto last change" single "marmalade"])
  (gnus-summary-ext . [(0 1) ((macro-utils (1 0))) "Extra limit and process mark commands for the gnus summary buffer" single "marmalade"])
  (bubbleberry-theme . [(0 1 2) ((emacs (24 1))) "A theme based on LightTable for Emacs24" single "marmalade"])
  (ido-select-window . [(0 1 0) nil "Select a window using ido and buffer names." tar "marmalade"])
  (dakrone-theme . [(0 0 2) nil "dakrone's custom dark theme" single "marmalade"])
  (flymake-racket . [(0 40) ((flymake-easy (0 1))) "A flymake handler for scheme-mode files" single "marmalade"])
  (org-gnome . [(0 1) ((notify (2010 8 20)) (telepathy (0 1))) "Orgmode integration with the GNOME desktop" single "marmalade"])
  (telepathy . [(0 1) nil "Access Telepathy from Emacs" single "marmalade"])
  (gvpr-mode . [(0 1 0) nil "A major mode offering basic syntax coloring for gvpr scripts." single "marmalade"])
  (flycheck-ledger . [(0 2) ((flycheck (0 15))) "Flycheck integration for ledger files" single "marmalade"])
  (pinboard-api . [(0 1) nil "Rudimentary http://pinboard.in integration" single "marmalade"])
  (column-enforce-mode . [(1 0 3) nil "Highlight text that extends beyond a  column" single "marmalade"])
  (ix . [(0 7) ((grapnel (0 5 3))) "Emacs client for http://ix.io pastebin" single "marmalade"])
  (flycheck-hdevtools . [(0 2) ((flycheck (0 15))) "A flycheck checker for Haskell using hdevtools" single "marmalade"])
  (zeal-at-point . [(0 0 3) nil "Search the word at point with Zeal" single "marmalade"])
  (tdd-status-mode-line . [(0 1 2) nil "TDD status on the mode-line" single "marmalade"])
  (troncle . [(0 1 2) ((cider (0 5 0))) "Emacs convenience functions for tracing clojure code" single "marmalade"])
  (free-keys . [(0 1) ((cl-lib (0 3))) "Show free keybindings for modkeys or prefixes" single "marmalade"])
  (prognth . [(1 0) nil "Extend prog1 to arbitrary index" single "marmalade"])
  (ariadne . [(0 1) ((bert (0 1))) "Ariadne plugin for Emacs" single "marmalade"])
  (bert . [(0 1) nil "BERT serialization library for Emacs" single "marmalade"])
  (livid-mode . [(0 1 0) ((skewer-mode (1 5 3)) (s (1 8 0))) "Live browser eval of JavaScript every time a buffer changes" single "marmalade"])
  (minitest . [(0 5) ((dash (1 0 0))) "An Emacs mode for ruby minitest files" single "marmalade"])
  (ido-vertical-mode . [(0 1 2) nil "Makes ido-mode display vertically." single "marmalade"])
  (nrepl-discover . [(0 0 1) nil "Client to load commands from nrepl server" single "marmalade"])
  (json-snatcher . [(1 0) nil "Grabs the path to JSON values in a JSON file." single "marmalade"])
  (ac-inf-ruby . [(0 4) ((inf-ruby (2 3 2)) (auto-complete (1 4))) "Enable auto-complete in inf-ruby sessions" single "marmalade"])
  (relax . [(0 2) ((json (1 2))) "For browsing and interacting with CouchDB" single "marmalade"])
  (el-init . [(20130416) nil "Loader for configuration files" tar "marmalade"])
  (lyskom . [(20131008) nil "LysKOM elisp client." single "marmalade"])
  (proxy-mode . [(0 9) nil "Provides proxy minor mode." single "marmalade"])
  (latest-clojure-libraries . [(0 5) nil "Clojure dependency resolver" single "marmalade"])
  (list-register . [(2 2) nil "List register" single "marmalade"])
  (anzu . [(0 22) nil "Show number of matches in mode-line while searching" single "marmalade"])
  (magit-find-file . [(1 0 4) ((magit (1 2 0))) "completing-read over all files in Git" single "marmalade"])
  (sequences . [(0 1 0) ((emacs (24))) "Ports of some Clojure sequence functions." single "marmalade"])
  (sensitive . [(1 0 1) ((emacs (24)) (sequences (0 1 0))) "A dead simple way to load sensitive information" single "marmalade"])
  (skewer-less . [(0 2) ((skewer-mode (1 5 3))) "Skewer support for live LESS stylesheet updates" single "marmalade"])
  (evil-matchit . [(1 2 9) nil "Vim matchit ported into Emacs (requires EVIL)" tar "marmalade"])
  (tbemail . [(0 2) nil "Provide syntax highlighting for email editing via" single "marmalade"])
  (timestamper . [(0 1 0) nil "A minor mode for easy timelogging" single "marmalade"])
  (pbcopy . [(0 1 0) nil "OS X clipboard integration for Emacs" single "marmalade"])
  (tommyh-theme . [(1 2) nil "A bright, bold-colored theme for emacs." single "marmalade"])
  (ample-zen-theme . [(0 2) nil "AmpleZen Theme for Emacs 24" single "marmalade"])
  (iasm-mode . [(0 1) nil "interactive assembly major mode." single "marmalade"])
  (ac-geiser . [(0 1) ((geiser (0 5)) (auto-complete (1 4))) "Auto-complete backend for geiser" tar "marmalade"])
  (java-file-create . [(1 0) nil "automatically insert contents of empty java files" single "marmalade"])
  (isgd . [(20130927) nil "Shorten URLs using the isgd.com shortener service" single "marmalade"])
  (whitespace-cleanup-mode . [(0 8) nil "Intelligently call whitespace-cleanup on save" single "marmalade"])
  (f . [(0 11 0) ((s (1 7 0)) (dash (2 2 0))) "Modern API for working with files and directories" single "marmalade"])
  (osx-pseudo-daemon . [(1 0) nil "Daemon mode that plays nice with OSX." single "marmalade"])
  (shell-pop . [(0 3) nil "helps you to use shell easily on Emacs. Only one key action to work." single "marmalade"])
  (zone-matrix . [(0 0 1) nil "Matrix themed Zone mode" tar "marmalade"])
  (elfeed-web . [(1 1 0) ((simple-httpd (1 4 3)) (elfeed (1 0 1)) (emacs (24 1))) "web interface to Elfeed" tar "marmalade"])
  (wonderland . [(0 1 1) ((dash (2 0 0)) (dash-functional (1 0 0)) (multi (2 0 0)) (emacs (24))) "declarative configuration for Emacsen -*- lexical-binding: t -*-" single "marmalade"])
  (jujube-theme . [(0 1) nil "Pastel theme loosely based on jellybeans" single "marmalade"])
  (helm-helm-commands . [(0 2) ((helm (1 5 4))) "List all helm commands with helm" single "marmalade"])
  (evil-indent-textobject . [(0 2) ((evil (0))) "evil textobjects based on indentation" single "marmalade"])
  (multi . [(2 0 1) ((emacs (24))) "Clojure-style multi-methods for emacs lisp -*- lexical-binding: t -*-" single "marmalade"])
  (gerrit-download . [(0 2) ((magit (20130828 1540))) "Show gerrit reviews in a diff buffer." single "marmalade"])
  (waher-theme . [(20130917 7) ((emacs (24 1))) "Emacs 24 theme based on waher for st2 by dduckster" single "marmalade"])
  (comint-better-defaults . [(1 0) nil "better defaults for comint-derived modes" single "marmalade"])
  (winpoint-ignore-dired . [(1 1) ((winpoint (1 0))) "Have winpoint ignore dired-mode buffers" single "marmalade"])
  (tox . [(0 1) nil "Launch current python test with tox." single "marmalade"])
  (smart-whitespace-comment-fixup . [(1 0) nil "Enables advice around yanking/killing lines that auto-indents and formats properly" single "marmalade"])
  (figlet . [(289) nil "banner generator" single "marmalade"])
  (smtpmail-multi . [(0 6) nil "Use different smtp servers for sending mail" single "marmalade"])
  (openstack-cgit-browse-file . [(0 2) nil "Browse the current file in OpenStack cgit" single "marmalade"])
  (flycheck-cask . [(0 1) ((flycheck (0 14)) (dash (2 0 0)) (f (0 6 0))) "Cask support in Flycheck -*- lexical-binding: t; -*-" single "marmalade"])
  (dash-functional . [(1 0 0) ((dash (2 0 0)) (emacs (24))) "Collection of useful combinators for Emacs Lisp  -*- lexical-binding: t -*-" single "marmalade"])
  (pkg-info . [(0 5) ((dash (1 6 0)) (epl (0 4))) "Information about packages       -*- lexical-binding: t; -*-" single "marmalade"])
  (discord . [(0 5) nil "Discordian dates for calendar" single "marmalade"])
  (aok . [(0 1) nil "various useful ways to do `multi-occur'" single "marmalade"])
  (magit-tramp . [(0 1 0) ((magit (1 2 0))) "git method for TRAMP" single "marmalade"])
  (tronesque-theme . [(1 3) nil "Color Theme based on Tron universe." single "marmalade"])
  (helm-recoll . [(20130905 2330) ((helm (1 5 4))) "helm interface for the recoll desktop search tool." single "marmalade"])
  (god-mode . [(2 12 0) nil "God-like command entering minor mode" single "marmalade"])
  (heroku-theme . [(1 1 0) nil "Heroku color theme" single "marmalade"])
  (tsql . [(1 0) nil "customizes sql.el for T-SQL" single "marmalade"])
  (helm-delicious . [(1 3) nil "helm extensions for delicious bookmarks" single "marmalade"])
  (wedge-ws . [(0 1 2) nil "Wedge whitespace between columns in text" tar "marmalade"])
  (sparkline . [(0 3 0) nil "Make sparkline images from a list of numbers" single "marmalade"])
  (flymake-puppet . [(1 0 0) ((flymake-easy (0 9))) "An Emacs flymake handler for syntax-checking puppet using puppet-lint" single "marmalade"])
  (palimpsest . [(0 8) nil "Various deletion strategies when editing" single "marmalade"])
  (py-import-check . [(0 2) nil "Finds the unused python imports using importchecker" single "marmalade"])
  (cubicle-mode . [(0 1) nil "Cubicle major mode for emacs" single "marmalade"])
  (pickup . [(0 0 3) nil "pickup file. " single "marmalade"])
  (cobra-mode . [(1 0 1) nil "Major mode for .NET-based Cobra language" single "marmalade"])
  (dummy-package . [(0 0 3) ((timeclock (2 6 1))) "a fake package for the marmalade test suite" single "marmalade"])
  (immutant-server . [(1 0 1) nil "Run your Immutant server in Emacs" single "marmalade"])
  (initchart . [(0 1 1) ((cl-lib (0 3))) "Emacs' init process performance visualization  -*- lexical-binding: t -*-" single "marmalade"])
  (wisp-mode . [(0 1 5) nil "Tools for wisp: the Whitespace-to-Lisp preprocessor" single "marmalade"])
  (project-explorer . [(0 13) ((cl-lib (0 3)) (es-lib (0 3)) (es-windows (0 1)) (emacs (24))) "A project explorer sidebar -*- lexical-binding: t -*-" single "marmalade"])
  (ac-cider-compliment . [(0 1 0) ((cider (0 5 0)) (auto-complete (1 4))) "auto-complete sources for Clojure using" single "marmalade"])
 )
