'(
  (ac-html . [(0 22) ((auto-complete (1 4))) "auto complete source for html tags and attributes" tar ((:url . "https://github.com/cheunghy/ac-html") (:keywords "html" "auto-complete" "rails" "ruby")) "melpa-stable"])
  (ace-isearch . [(0 1 0) ((ace-jump-mode (2 0)) (helm-swoop (1 4)) (emacs (24))) "A seamless bridge between isearch and ace-jump-mode" single ((:url . "https://github.com/tam17aki/ace-isearch")) "melpa-stable"])
  (ace-jump-buffer . [(0 3 1) ((ace-jump-mode (1 0)) (dash (2 4 0))) "fast buffer switching extension to `ace-jump-mode'" single ((:url . "https://github.com/waymondo/ace-jump-buffer")) "melpa-stable"])
  (ace-jump-zap . [(0 0 3) ((ace-jump-mode (1 0))) "Character zapping, `ace-jump-mode` style" single ((:url . "https://github.com/waymondo/ace-jump-zap") (:keywords "convenience" "tools" "extensions")) "melpa-stable"])
  (ace-link . [(0 3 0) ((ace-jump-mode (2 0))) "Quickly follow links using `ace-jump-mode'" single ((:url . "https://github.com/abo-abo/ace-link") (:keywords "convenience" "links")) "melpa-stable"])
  (aggressive-indent . [(0 3 4) ((emacs (24 1)) (names (0 5)) (cl-lib (0 5))) "Minor mode to aggressively keep your code always indented" single ((:url . "http://github.com/Bruce-Connor/aggressive-indent-mode") (:keywords "indent" "lisp" "maint" "tools")) "melpa-stable"])
  (alert . [(1 1) ((gntp (0 1))) "Growl-style notification system for Emacs" single ((:url . "https://github.com/jwiegley/alert") (:keywords "notification" "emacs" "message")) "melpa-stable"])
  (android-mode . [(0 4 0) nil "Minor mode for Android application development" single ((:url . "https://github.com/remvee/android-mode") (:keywords "tools" "processes")) "melpa-stable"])
  (aproject . [(0 1) nil "A simple project framework for Emacs" single ((:url . "https://github.com/vietor/aproject") (:keywords "environment" "project")) "melpa-stable"])
  (artbollocks-mode . [(1 1 2) nil "Improve your writing (especially about art)" single ((:url . "https://github.com/sachac/artbollocks-mode")) "melpa-stable"])
  (asilea . [(0 2 1) ((emacs (24)) (cl-lib (0 5))) "Find best compiler options using simulated annealing" single ((:url . "https://github.com/Fanael/asilea")) "melpa-stable"])
  (aurora-config-mode . [(0 0 2) nil "Major mode for Apache Aurora configuration files" single ((:url . "https://github.com/bdd/aurora-config.el") (:keywords "languages" "configuration")) "melpa-stable"])
  (auto-complete-nxml . [(0 5 0) ((auto-complete (1 4))) "do completion by auto-complete.el on nXML-mode" single ((:url . "https://github.com/aki2o/auto-complete-nxml") (:keywords "completion" "html" "xml")) "melpa-stable"])
  (auto-complete-pcmp . [(0 0 2) ((auto-complete (1 4 0)) (log4e (0 2 0)) (yaxception (0 1))) "Provide auto-complete sources using pcomplete results" single ((:url . "https://github.com/aki2o/auto-complete-pcmp") (:keywords "completion")) "melpa-stable"])
  (auto-package-update . [(1 2) ((emacs (24 3)) (dash (2 1 0))) "Automatically update Emacs packages." single ((:url . "http://github.com/rranelli/auto-package-update.el") (:keywords "package" "update")) "melpa-stable"])
  (bbdb- . [(0 0 2) ((bbdb (20140123 1541)) (log4e (0 2 0)) (yaxception (0 1))) "provide interface for more easily search/choice than BBDB." single ((:url . "https://github.com/aki2o/bbdb-") (:keywords "bbdb" "news" "mail")) "melpa-stable"])
  (boon . [(0 1) ((emacs (24 3)) (expand-region (0 10 0))) "Ergonomic Command Mode for Emacs." tar nil "melpa-stable"])
  (boxquote . [(1 22) nil "Quote text with a semi-box." single nil "melpa-stable"])
  (caskxy . [(0 0 5) ((log4e (0 2 0)) (yaxception (0 1))) "Control Cask in Emacs" single ((:url . "https://github.com/aki2o/caskxy") (:keywords "convenience")) "melpa-stable"])
  (checkbox . [(0 2 1) ((emacs (24)) (cl-lib (0 5))) "Quick manipulation of textual checkboxes" single ((:url . "http://github.com/camdez/checkbox.el") (:keywords "convenience")) "melpa-stable"])
  (chinese-word-at-point . [(0 2) ((cl-lib (0 5))) "Add `chinese-word' thing to `thing-at-point'" single ((:url . "https://github.com/xuchunyang/chinese-word-at-point.el") (:keywords "convenience" "chinese")) "melpa-stable"])
  (circe . [(1 5) ((lui (0)) (lcs (0))) "Client for IRC in Emacs" tar nil "melpa-stable"])
  (clocker . [(0 0 3) ((projectile (0 11 0)) (dash (2 10))) "Note taker and clock-in enforcer" single ((:keywords "org")) "melpa-stable"])
  (company-cabal . [(0 1 0) ((cl-lib (0 5)) (company (0 8 0)) (emacs (24))) "company-mode cabal backend" tar ((:url . "https://github.com/iquiw/company-cabal")) "melpa-stable"])
  (company-restclient . [(0 0 2) ((cl-lib (0 5)) (company (0 8 0)) (emacs (24)) (know-your-http-well (0 2 0))) "company-mode completion back-end for restclient-mode" single ((:url . "https://github.com/iquiw/company-restclient")) "melpa-stable"])
  (company-ycmd . [(0 9) ((ycmd (0 1)) (company (0 8 3)) (deferred (0 2 0)) (s (1 0 0))) "company-mode backend for ycmd" single ((:url . "https://github.com/abingham/emacs-ycmd")) "melpa-stable"])
  (csharp-mode . [(0 8 8) nil "C# mode derived mode" tar ((:url . "https://github.com/josteink/csharp-mode") (:keywords "c#" "languages" "oop" "mode")) "melpa-stable"])
  (ctxmenu . [(0 3 0) ((popup (20140205 103)) (log4e (0 2 0)) (yaxception (0 1))) "Provide a context menu like right-click." tar ((:url . "https://github.com/aki2o/emacs-ctxmenu") (:keywords "popup")) "melpa-stable"])
  (date-at-point . [(0 1) nil "Add `date' to `thing-at-point' function" single ((:url . "https://gitorious.org/alezost-emacs/date-at-point") (:keywords "convenience")) "melpa-stable"])
  (date-field . [(0 0 1) ((dash (2 9 0)) (log4e (0 2 0)) (yaxception (0 3 2))) "Date widget" single ((:url . "https://github.com/aki2o/emacs-date-field") (:keywords "widgets")) "melpa-stable"])
  (dired-fdclone . [(1 2) nil "dired functions and settings to mimic FDclone" single ((:url . "https://github.com/knu/dired-fdclone.el") (:keywords "unix" "directories" "dired")) "melpa-stable"])
  (dired-imenu . [(0 5 0) nil "imenu binding for dired mode" single ((:url . "https://github.com/DamienCassou/dired-imenu") (:keywords "dired" "imenu")) "melpa-stable"])
  (direx-grep . [(0 1 0) ((direx (0 1 -3))) "Grep node of direx.el using incremental search like anything.el/helm.el" single ((:url . "https://github.com/aki2o/direx-grep") (:keywords "convenience")) "melpa-stable"])
  (dockerfile-mode . [(1 0) nil "Major mode for editing Docker's Dockerfiles" single nil "melpa-stable"])
  (downplay-mode . [(0 1) nil "focus attention on a region of the buffer" single ((:url . "https://github.com/tobias/downplay-mode/")) "melpa-stable"])
  (dyalog-mode . [(0 3) nil "Major mode for editing Dyalog APL source code" single ((:url . "http://bitbucket.org/harsman/dyalog-mode") (:keywords "languages")) "melpa-stable"])
  (e2wm-direx . [(0 0 5) ((e2wm (1 2)) (direx (0 1 -3))) "Plugin of e2wm.el for direx.el" single ((:url . "https://github.com/aki2o/e2wm-direx") (:keywords "tools" "window manager" "convenience")) "melpa-stable"])
  (e2wm-pkgex4pl . [(0 0 1) ((e2wm (1 2)) (plsense-direx (0 2 0))) "Plugin of e2wm.el for package explorer of Perl" single ((:url . "https://github.com/aki2o/e2wm-pkgex4pl") (:keywords "tools" "window manager" "perl")) "melpa-stable"])
  (e2wm-sww . [(0 0 2) ((e2wm (1 2))) "Plugin of e2wm.el to switch plugin quickly" single ((:url . "https://github.com/aki2o/e2wm-sww") (:keywords "tools" "window manager")) "melpa-stable"])
  (e2wm-term . [(0 0 5) ((e2wm (1 2)) (log4e (0 2 0)) (yaxception (0 3 2))) "Perspective of e2wm.el for work in terminal" single ((:url . "https://github.com/aki2o/e2wm-term") (:keywords "tools" "window manager")) "melpa-stable"])
  (edit-indirect . [(0 1 2) ((emacs (24 3))) "Edit regions in separate buffers" single ((:url . "https://github.com/Fanael/edit-indirect")) "melpa-stable"])
  (el-init . [(0 1 2) ((emacs (24)) (cl-lib (0 5)) (anaphora (1 0 0))) "A loader inspired by init-loader" single nil "melpa-stable"])
  (elscreen-mew . [(1 0 1) ((elscreen (20120413 807))) "ElScreen Add-On for Mew" single ((:url . "https://github.com/masutaka/elscreen-mew")) "melpa-stable"])
  (elscreen-persist . [(0 1 1) ((elscreen (1 4 6)) (revive (2 1 9))) "persist the elscreen across sessions" single ((:keywords "elscreen" "frames")) "melpa-stable"])
  (erc-youtube . [(0 -3) ((erc (5 3))) "Show received youtube urls in the ERC buffer" single ((:keywords "multimedia")) "melpa-stable"])
  (erefactor . [(0 6 13) nil "Emacs-Lisp refactoring utilities" single ((:url . "https://github.com/mhayashi1120/Emacs-erefactor/raw/master/erefactor.el") (:keywords "extensions" "tools" "maint")) "melpa-stable"])
  (es-lib . [(0 4) ((cl-lib (0 3))) "A collection of emacs utilities" tar ((:url . "https://github.com/sabof/es-lib")) "melpa-stable"])
  (ess-R-data-view . [(1 0) ((ctable (20130313 1743)) (popup (20130324 1305)) (ess (20130225 1754))) "Data viewer for GNU R" single ((:url . "https://github.com/myuhe/ess-R-data-view.el") (:keywords "convenience")) "melpa-stable"])
  (ess-R-object-popup . [(1 0) ((popup (20130117 1954)) (ess (20130225 1754))) "popup description of R object" single ((:url . "https://github.com/myuhe/ess-R-object-popup.el") (:keywords "convenience" "ess")) "melpa-stable"])
  (eval-in-repl . [(0 5 1) ((dash (0 0 0)) (paredit (0 0 0))) "Consistent ESS-like eval interface for various REPLs" tar nil "melpa-stable"])
  (evil-anzu . [(0 2) ((evil (1 0 0)) (anzu (0 46))) "anzu for evil-mode" single ((:url . "https://github.com/syohex/emacs-evil-anzu")) "melpa-stable"])
  (evil-commentary . [(0 0 2) ((evil (1 0 0))) "Comment stuff out. A port of vim-commentary." single ((:url . "http://github.com/linktohack/evil-commentary") (:keywords "evil" "comment" "commentary" "evil-commentary")) "melpa-stable"])
  (evil-escape . [(2 6) ((emacs (24)) (evil (1 0 9))) "Escape from anything with a customizable key sequence" single ((:url . "https://github.com/syl20bnr/evil-escape") (:keywords "convenience" "editing" "evil")) "melpa-stable"])
  (evil-iedit-state . [(1 0) ((evil (1 0 9)) (iedit (0 97))) "Evil states to interface iedit mode." single ((:url . "https://github.com/syl20bnr/evil-iedit-state") (:keywords "convenience" "editing" "evil" "iedit" "mnemonic")) "melpa-stable"])
  (evil-snipe . [(1 0) nil "emulate vim-sneak & vim-seek" single ((:url . "https://github.com/hlissner/evil-snipe") (:keywords "emulation" "vim" "evil" "sneak" "seek")) "melpa-stable"])
  (evil-tutor . [(1 0) ((evil (1 0 9))) "Vimtutor adapted to Evil and wrapped in a major-mode" tar ((:url . "https://github.com/syl20bnr/evil-tutor") (:keywords "convenience" "editing" "evil")) "melpa-stable"])
  (feature-mode . [(0 4) nil "Major mode for editing Gherkin (i.e. Cucumber) user stories" tar nil "melpa-stable"])
  (flycheck-clojure . [(0 1 3) ((cider (0 8 1)) (flycheck (0 22 -3 1)) (let-alist (1 0 1)) (emacs (24))) "Flycheck: Clojure support" single ((:url . "https://github.com/clojure-emacs/squiggly-clojure")) "melpa-stable"])
  (flycheck-ocaml . [(0 2) ((emacs (24 1)) (flycheck (0 22 -3 1)) (merlin (2 0)) (let-alist (1 0 3))) "Flycheck: OCaml support" single ((:url . "https://github.com/flycheck/flycheck-ocaml") (:keywords "convenience" "tools" "languages")) "melpa-stable"])
  (flycheck-package . [(0 6) ((cl-lib (0 5)) (flycheck (0 22)) (emacs (24))) "A Flycheck checker for elisp package authors" single ((:keywords "lisp")) "melpa-stable"])
  (flycheck-ycmd . [(0 9) ((emacs (24)) (dash (1 2 0)) (flycheck (0 22)) (ycmd (20141217 453))) "flycheck integration for ycmd" single ((:url . "https://github.com/abingham/emacs-ycmd")) "melpa-stable"])
  (form-feed . [(0 1 6) nil "Display ^L glyphs as horizontal lines" single ((:url . "https://github.com/wasamasa/form-feed") (:keywords "faces")) "melpa-stable"])
  (genrnc . [(0 1 0) ((deferred (0 3 1)) (concurrent (0 3)) (log4e (0 2 0)) (yaxception (0 1))) "generate RELAX NG Compact Schema from RELAX NG Schema, XML Schema and DTD." tar ((:url . "https://github.com/aki2o/emacs-genrnc") (:keywords "xml")) "melpa-stable"])
  (ghc-imported-from . [(0 1 2) ((emacs (24 1))) "Haskell documentation lookup with ghc-imported-from" single ((:keywords "languages")) "melpa-stable"])
  (gitlab . [(0 2 0) ((s (1 9 0)) (dash (2 9 0)) (pkg-info (0 5 0)) (request (0 1 0))) "Emacs client for Gitlab" tar ((:url . "https://github.com/nlamirault/emacs-gitlab") (:keywords "gitlab")) "melpa-stable"])
  (gnus-x-gm-raw . [(0 0 1) ((log4e (0 2 0)) (yaxception (0 1))) "Search mail of Gmail using X-GM-RAW as web interface" single ((:url . "https://github.com/aki2o/gnus-x-gm-raw") (:keywords "gnus")) "melpa-stable"])
  (go-errcheck . [(1 0 0) nil "errcheck integration for go-mode" single nil "melpa-stable"])
  (go-mode . [(1 0 0) nil "Major mode for the Go programming language" tar ((:url . "https://github.com/dominikh/go-mode.el") (:keywords "languages" "go")) "melpa-stable"])
  (gotham-theme . [(1 0) nil "A very dark Emacs color theme." single ((:url . "https://github.com/wasamasa/gotham-theme")) "melpa-stable"])
  (goto-last-change . [(1 2 0) nil "Move point through buffer-undo-list positions" single ((:url . "https://github.com/camdez/goto-last-change.el") (:keywords "convenience")) "melpa-stable"])
  (graphviz-dot-mode . [(0 4) nil "Mode for the dot-language used by graphviz (att)." single ((:url . "http://ppareit.github.com/graphviz-dot-mode/") (:keywords "mode" "dot" "dot-language" "dotlanguage" "graphviz" "graphs" "att")) "melpa-stable"])
  (guide-key . [(1 2 5) ((popwin (0 3 0))) "Guide the following key bindings automatically and dynamically" single ((:url . "https://github.com/kai2nenobu/guide-key") (:keywords "help" "convenience")) "melpa-stable"])
  (guide-key-tip . [(0 0 1) ((guide-key (1 2 3)) (pos-tip (0 4 5))) "Show guide-key.el hints using pos-tip.el" single ((:url . "https://github.com/aki2o/guide-key-tip") (:keywords "help" "convenience" "tooltip")) "melpa-stable"])
  (haskell-emacs . [(1 5 0) nil "write emacs extensions in haskell" tar ((:url . "https://github.com/knupfer/haskell-emacs") (:keywords "haskell" "emacs" "ffi")) "melpa-stable"])
  (helm-ghc . [(0 1 0) ((emacs (24)) (cl-lib (0 5)) (helm (1 6 4)) (ghc (5 2 1 0))) "A Helm datasource for ghc-mod errors" single ((:keywords "languages" "helm")) "melpa-stable"])
  (helm-gitlab . [(0 2 0) ((s (1 9 0)) (dash (2 9 0)) (helm (1 0)) (gitlab (0))) "Helm interface to Gitlab" single ((:url . "https://github.com/nlamirault/emacs-gitlab") (:keywords "gitlab" "helm")) "melpa-stable"])
  (helm-hatena-bookmark . [(1 0 2) ((helm (1 5 6))) "Hatena::Bookmark helm.el interface" single ((:url . "https://github.com/masutaka/emacs-helm-hatena-bookmark")) "melpa-stable"])
  (helm-pages . [(0 1 1) ((helm (1 6 5)) (emacs (24)) (cl-lib (0 5))) "Pages in current buffer as Helm datasource" single ((:keywords "convenience" "helm" "outlines")) "melpa-stable"])
  (helm-w32-launcher . [(0 1 6) ((emacs (24)) (helm (1 6 5)) (cl-lib (0 5))) "Start Menu entry launcher using Helm" tar ((:url . "https://github.com/Fanael/helm-w32-launcher")) "melpa-stable"])
  (hi2 . [(1 0) nil "indentation module for Haskell Mode" single ((:url . "https://github.com/errge/hi2") (:keywords "indentation" "haskell")) "melpa-stable"])
  (hindent . [(4 3 0) ((cl-lib (0 5))) "Indent haskell code using the \"hindent\" program" single ((:url . "https://github.com/chrisdone/hindent")) "melpa-stable"])
  (history . [(1 0 0) ((emacs (24 3))) "History utility for source code navigation" tar ((:url . "https://github.com/boyw165/history")) "melpa-stable"])
  (hl-anything . [(0 0 9) ((emacs (24 3))) "Highlight symbols, selections, enclosing parens and more." tar nil "melpa-stable"])
  (hydra . [(0 3 0) ((cl-lib (0 5))) "Make bindings that stick around" tar ((:url . "https://github.com/abo-abo/hydra") (:keywords "bindings")) "melpa-stable"])
  (ibuffer-projectile . [(0 2) ((projectile (0 11 0))) "Group ibuffer's list by projectile root" single ((:url . "http://github.com/purcell/ibuffer-projectile") (:keywords "themes")) "melpa-stable"])
  (idomenu . [(0 1) nil "imenu tag selection with ido" single ((:url . "https://github.com/birkenfeld/idomenu") (:keywords "extensions" "convenience")) "melpa-stable"])
  (image-archive . [(0 0 7) ((emacs (24)) (cl-lib (0 5))) "Image thumbnails in archive file with non-blocking" single ((:url . "https://github.com/mhayashi1120/Emacs-image-archive/raw/master/image-archive.el") (:keywords "multimedia")) "melpa-stable"])
  (image-dired+ . [(0 5 4) nil "Image-dired extensions" single ((:url . "http://github.com/mhayashi1120/Emacs-image-diredx/raw/master/image-dired+.el") (:keywords "image-dired" "extensions")) "melpa-stable"])
  (imenus . [(0 1) ((cl-lib (0 5))) "Imenu for multiple buffers" single ((:url . "https://gitorious.org/alezost-emacs/imenus") (:keywords "tools" "convenience")) "melpa-stable"])
  (imgix . [(1 0 0) ((json (1 2)) (ht (2 0)) (s (1 9 0)) (dash (2 9 0)) (cl-lib (0 5))) "Major mode for editing images in emacs via imgix" tar ((:keywords "images" "image processing" "image editing" "sepia" "blur")) "melpa-stable"])
  (inf-clojure . [(1 0 0) ((emacs (24 1)) (clojure-mode (4 0))) "an inferior-clojure mode" single ((:url . "http://github.com/clojure-emacs/inf-clojure") (:keywords "processes" "clojure")) "melpa-stable"])
  (inlineR . [(1 0) nil "insert Tag for inline image of R graphics" single ((:url . "https://github.com/myuhe/inlineR.el") (:keywords "convenience" "iimage.el" "cacoo.el")) "melpa-stable"])
  (iplayer . [(0 1) nil "Browse and download BBC TV/radio shows" single ((:url . "https://github.com/csrhodes/iplayer-el") (:keywords "multimedia" "bbc")) "melpa-stable"])
  (json-reformat . [(0 0 2) nil "Reformatting tool for JSON" single ((:url . "https://github.com/gongo/json-reformat") (:keywords "json")) "melpa-stable"])
  (jvm-mode . [(0 1 0) ((dash (2 6 0)) (emacs (24))) "Monitor and manage your JVMs" single ((:url . "https://github.com/martintrojer/jvm-mode.el") (:keywords "convenience")) "melpa-stable"])
  (kakapo-mode . [(0 2) ((cl-lib (0 5))) "TABS (hard or soft) for indentation (leading whitespace), and SPACES for alignment." single ((:url . "https://github.com/listx/kakapo-mode") (:keywords "indentation")) "melpa-stable"])
  (karma . [(0 1 0) nil "Karma Test Runner Emacs Integration" single ((:url . "http://github.com/tonini/karma.el") (:keywords "javascript" "js" "karma" "testing")) "melpa-stable"])
  (keyfreq . [(1 5) nil "track command frequencies" single nil "melpa-stable"])
  (keyset . [(0 1 2) ((dash (2 8 0)) (cl-lib (0 5))) "A small library for structuring key bindings." single nil "melpa-stable"])
  (kurecolor . [(1 1) ((emacs (24 1)) (s (1 0))) "color editing goodies for Emacs" single nil "melpa-stable"])
  (latex-math-preview . [(0 7 0) nil "preview LaTeX mathematical expressions." single ((:url . "http://www.emacswiki.org/latex-math-preview.el") (:keywords "latex" "tex")) "melpa-stable"])
  (lcs . [(1 5) nil "find out the longest common sequence" single ((:url . "https://github.com/jorgenschaefer/circe/wiki/lcs")) "melpa-stable"])
  (lentic . [(0 6 1) ((emacs (24)) (m-buffer (0 8)) (dash (2 5 0))) "One buffer as a view of another" tar nil "melpa-stable"])
  (lit-mode . [(0 1 1) nil "Major mode for lit" single ((:keywords "languages" "tools")) "melpa-stable"])
  (live-code-talks . [(0 2 1) ((emacs (24)) (cl-lib (0 5)) (narrowed-page-navigation (0 1))) "Support for slides with live code in them" single ((:keywords "docs" "multimedia")) "melpa-stable"])
  (load-relative . [(1 0) nil "relative file load (within a multi-file Emacs package)" tar ((:url . "http://github.com/rocky/emacs-load-relative") (:keywords "internal")) "melpa-stable"])
  (loc-changes . [(1 1) nil "Helps users and programs keep track of positions even after buffer changes." single ((:url . "http://github.com/rocky/emacs-loc-changes")) "melpa-stable"])
  (log4e . [(0 3 0) nil "provide logging framework for elisp" single ((:url . "https://github.com/aki2o/log4e") (:keywords "log")) "melpa-stable"])
  (lui . [(1 5) ((tracking (0))) "Linewise User Interface" tar nil "melpa-stable"])
  (marcopolo . [(0 1 0) ((s (1 9 0)) (dash (2 9 0)) (pkg-info (0 5 0)) (request (0 1 0))) "Emacs client for Docker API" tar ((:url . "https://github.com/nlamirault/marcopolo") (:keywords "docker")) "melpa-stable"])
  (markup-faces . [(1 0 0) nil "collection of faces for markup language modes" single ((:url . "https://github.com/sensorflo/markup-faces") (:keywords "wp" "faces")) "melpa-stable"])
  (marshal . [(0 3 1) ((eieio (1 4)) (json (1 4))) "eieio extension for automatic (un)marshalling" single ((:url . "https://github.com/sigma/marshal.el") (:keywords "eieio")) "melpa-stable"])
  (maven-test-mode . [(0 1 5) ((s (1 9)) (emacs (24))) "Utilities for navigating test files and running maven test tasks." single ((:url . "http://github.com/rranelli/maven-test-mode") (:keywords "java" "maven" "test")) "melpa-stable"])
  (mbe . [(0 1) ((emacs (24)) (cl-lib (0 5))) "Macros by Example" single ((:url . "https://github.com/ijp/mbe.el") (:keywords "tools" "macros")) "melpa-stable"])
  (metaweblog . [(0 1 1) ((xml-rpc (1 6 8))) "An emacs library to access metaweblog based weblogs" tar nil "melpa-stable"])
  (monokai-theme . [(1 0 0) nil "A fruity color theme for Emacs." single ((:url . "http://github.com/oneKelvinSmith/monokai-emacs")) "melpa-stable"])
  (moz-controller . [(1 0) ((moz (0))) "Control Firefox from Emacs" single ((:url . "https://github.com/RenWenshan/emacs-moz-controller")) "melpa-stable"])
  (mwim . [(0 1) nil "Move to the beginning/end of line or code" single ((:url . "https://gitorious.org/alezost-emacs/mwim") (:keywords "convenience")) "melpa-stable"])
  (narrowed-page-navigation . [(0 1 0) ((emacs (24)) (cl-lib (0 5))) "A minor mode for showing one page at a time" single ((:keywords "outlines")) "melpa-stable"])
  (omnisharp . [(3 8) ((json (1 2)) (flycheck (0 21)) (dash (20141201 2206)) (auto-complete (1 4)) (popup (0 5 1)) (csharp-mode (0 8 7)) (cl-lib (0 5))) "Omnicompletion (intellisense) and more for C#" tar ((:url . "https://github.com/sp3ctum/omnisharp-emacs") (:keywords "csharp" "c#" "ide" "auto-complete" "intellisense")) "melpa-stable"])
  (org-ac . [(0 0 2) ((auto-complete-pcmp (0 0 1)) (log4e (0 2 0)) (yaxception (0 1))) "Some auto-complete sources for org-mode" single ((:url . "https://github.com/aki2o/org-ac") (:keywords "org" "completion")) "melpa-stable"])
  (org-autolist . [(0 12) nil "Improved list management in org-mode" single ((:url . "https://github.com/calvinwyoung/org-autolist") (:keywords "lists" "checklists" "org-mode")) "melpa-stable"])
  (org-link-travis . [(0 0 1) ((org (7))) "Insert/Export the link of Travis CI on org-mode" single ((:url . "https://github.com/aki2o/org-link-travis") (:keywords "org")) "melpa-stable"])
  (org-linkany . [(0 0 2) ((log4e (0 2 0)) (yaxception (0 1))) "Insert link using anything.el/helm.el on org-mode" single ((:url . "https://github.com/aki2o/org-linkany") (:keywords "org" "completion")) "melpa-stable"])
  (org-repo-todo . [(0 0 2) nil "Simple repository todo management with org-mode" single ((:url . "https://github.com/waymondo/org-repo-todo") (:keywords "convenience")) "melpa-stable"])
  (org2blog . [(0 9 2) ((org (8 1)) (xml-rpc (1 6 8)) (metaweblog (0 1))) "Blog from Org mode to wordpress" tar nil "melpa-stable"])
  (overseer . [(0 1 0) ((emacs (24)) (dash (2 10 0)) (pkg-info (0 4))) "Ert-runner Integration Into Emacs." single ((:url . "http://www.github.com/tonini/overseer.el")) "melpa-stable"])
  (owdriver . [(0 0 6) ((smartrep (0 0 3)) (log4e (0 2 0)) (yaxception (0 2 0))) "Quickly perform various actions on other windows" single ((:url . "https://github.com/aki2o/owdriver") (:keywords "convenience")) "melpa-stable"])
  (ox-twbs . [(0 1 0) nil "Bootstrap compatible HTML Back-End for Org" single ((:url . "https://github.com/marsmining/ox-twbs") (:keywords "org" "html" "publish" "twitter" "bootstrap")) "melpa-stable"])
  (package+ . [(1 0 1) nil "Extensions for the package library." single ((:url . "TBA") (:keywords "extensions" "tools")) "melpa-stable"])
  (parenface . [(1 0 3) nil "Provide a face for parens in lispy modes." tar nil "melpa-stable"])
  (parsebib . [(1 0 3) ((emacs (24 3))) "A library for parsing bib files" single ((:keywords "text" "bibtex")) "melpa-stable"])
  (paxedit . [(1 1 4) ((cl-lib (0 5)) (paredit (23))) "Structured, Context Driven LISP Editing and Refactoring" single ((:url . "https://github.com/promethial/paxedit") (:keywords "lisp" "refactoring" "context")) "melpa-stable"])
  (pcsv . [(1 3 5) nil "Parser of csv" single ((:url . "https://github.com/mhayashi1120/Emacs-pcsv/raw/master/pcsv.el") (:keywords "data")) "melpa-stable"])
  (persistent-scratch . [(0 2 1) ((emacs (24))) "Preserve the scratch buffer across Emacs sessions" single ((:url . "https://github.com/Fanael/persistent-scratch")) "melpa-stable"])
  (persp-mode . [(1 0) nil "\"perspectives\" + save/load + shared among frames - bugs." single ((:url . "https://github.com/Bad-ptr/persp-mode.el") (:keywords "perspectives" "session")) "melpa-stable"])
  (pixiv-novel-mode . [(0 0 3) nil "Major mode for pixiv novel" single ((:keywords "novel" "pixiv")) "melpa-stable"])
  (plsense . [(0 4 6) ((auto-complete (1 4 0)) (log4e (0 2 0)) (yaxception (0 2 0))) "provide interface for PlSense that is a development tool for Perl." single ((:url . "https://github.com/aki2o/emacs-plsense") (:keywords "perl" "completion")) "melpa-stable"])
  (plsense-direx . [(0 2 0) ((direx (0 1 -3)) (plsense (0 3 2)) (log4e (0 2 0)) (yaxception (0 3 2))) "Perl Package Explorer" single ((:url . "https://github.com/aki2o/plsense-direx") (:keywords "perl" "convenience")) "melpa-stable"])
  (pophint . [(0 9 3) ((popup (0 5 0)) (log4e (0 2 0)) (yaxception (0 1))) "Provide navigation using pop-up tips, like Firefox's Vimperator Hint Mode" tar ((:url . "https://github.com/aki2o/emacs-pophint") (:keywords "popup")) "melpa-stable"])
  (pos-tip . [(0 4 6) nil "Show tooltip at point" single ((:keywords "tooltip")) "melpa-stable"])
  (rake . [(0 3 0) ((f (0 13 0)) (dash (1 5 0)) (cl-lib (0 5))) "Run rake commands" single ((:url . "https://github.com/asok/rake.el") (:keywords "rake" "ruby")) "melpa-stable"])
  (realgud . [(1 1) ((load-relative (1 0)) (list-utils (0 4 2)) (loc-changes (1 1)) (test-simple (1 0))) "A modular front-end for interacting with external debuggers" tar ((:url . "http://github.com/rocky/emacs-dbgr")) "melpa-stable"])
  (rect+ . [(1 0 7) nil "Extensions to rect.el" single ((:url . "https://github.com/mhayashi1120/Emacs-rectplus/raw/master/rect+.el") (:keywords "extensions" "data" "tools")) "melpa-stable"])
  (reverse-theme . [(0 3) nil "Reverse theme for Emacs" single ((:url . "https://github.com/syohex/emacs-reverse-theme")) "melpa-stable"])
  (scala-mode2 . [(0 22) nil "Major mode for editing Scala >= 2.9" tar nil "melpa-stable"])
  (scala-outline-popup . [(0 3 4) ((dash (2 9 0)) (popup (0 5 2)) (scala-mode2 (0 22))) "scala file summary popup" single ((:url . "https://github.com/ancane/scala-outline-popup.el") (:keywords "scala" "structure" "summary")) "melpa-stable"])
  (shackle . [(0 2 2) ((cl-lib (0 5))) "Enforce rules for popups" single ((:url . "https://github.com/wasamasa/shackle") (:keywords "convenience")) "melpa-stable"])
  (shell-toggle . [(1 3 1) nil "Toggle to and from the shell buffer" single ((:url . "https://github.com/knu/shell-toggle.el") (:keywords "processes")) "melpa-stable"])
  (shelldoc . [(0 0 5) ((cl-lib (0 3)) (s (1 9 0))) "shell command editing support with man page." single ((:url . "http://github.com/mhayashi1120/Emacs-shelldoc/raw/master/shelldoc.el") (:keywords "applications")) "melpa-stable"])
  (shelltest-mode . [(1 0) nil "Major mode for shelltestrunner" single ((:url . "https://github.com/rtrn/shelltest-mode") (:keywords "languages")) "melpa-stable"])
  (shorten . [(1 5) nil "component-wise string shortener" single ((:url . "https://github.com/jorgenschaefer/circe/blob/master/lisp/shorten.el") (:keywords "extensions")) "melpa-stable"])
  (smartparens . [(1 6 3) ((cl-lib (0 3)) (dash (2 6 0))) "Automatic insertion, wrapping and paredit-like navigation with user defined pairs." tar nil "melpa-stable"])
  (smooth-scrolling . [(1 0 4) nil "Make emacs scroll smoothly" single ((:url . "http://github.com/aspiers/smooth-scrolling/") (:keywords "convenience")) "melpa-stable"])
  (sos . [(0 1) ((org (7))) "StackOverflow Search" single ((:url . "https://github.com/omouse/emacs-sos") (:keywords "tools" "search" "questions")) "melpa-stable"])
  (sparkline . [(1 0 2) ((cl-lib (0 3))) "Make sparkline images from a list of numbers" single ((:keywords "extensions")) "melpa-stable"])
  (spotify . [(0 3 2) nil "Control the spotify application from emacs" single ((:url . "https://github.com/remvee/spotify-el") (:keywords "convenience")) "melpa-stable"])
  (sqlup-mode . [(0 5 0) nil "Upcase SQL words for you" single ((:url . "https://github.com/trevoke/sqlup-mode.el") (:keywords "sql" "tools")) "melpa-stable"])
  (sx . [(0 1) ((emacs (24 1)) (cl-lib (0 5)) (json (1 3)) (markdown-mode (2 0))) "Core functions of the sx package." tar ((:url . "https://github.com/vermiculus/stack-mode/") (:keywords "help" "hypermedia" "tools")) "melpa-stable"])
  (tabulated-list . [(0) nil "generic major mode for tabulated lists." single ((:keywords "extensions" "lisp")) "melpa-stable"])
  (term-alert . [(1 0) ((term-cmd (1 0)) (alert (1 1))) "Get notifications when commands complete in the Emacs terminal emulator" single ((:url . "https://github.com/CallumCameron/term-alert") (:keywords "notifications" "processes")) "melpa-stable"])
  (term-cmd . [(1 0) nil "Send commands to Emacs from programs running under term.el" single ((:url . "https://github.com/CallumCameron/term-cmd") (:keywords "processes")) "melpa-stable"])
  (tern-django . [(0 1 0) ((emacs (24)) (tern (0 0 1)) (f (0 17 1))) "Create tern projects for django applications." tar ((:url . "https://github.com/proofit404/tern-django")) "melpa-stable"])
  (test-simple . [(1 0) nil "Simple Unit Test Framework for Emacs Lisp" single ((:url . "http://github.com/rocky/emacs-test-simple") (:keywords "unit-test")) "melpa-stable"])
  (timer-revert . [(0 1) nil "minor mode to revert buffer for a given time interval." single ((:url . "http://github.com/yyr/timer-revert") (:keywords "timer" "revert" "auto-revert.")) "melpa-stable"])
  (tracking . [(1 5) ((shorten (0 1))) "Buffer modification tracking" single ((:url . "https://github.com/jorgenschaefer/circe/wiki/Tracking")) "melpa-stable"])
  (travis . [(0 4 0) ((s (1 9 0)) (dash (2 9 0)) (pkg-info (0 5 0)) (request (0 1 0))) "Emacs client for Travis" tar ((:url . "https://github.com/nlamirault/emacs-travis") (:keywords "travis")) "melpa-stable"])
  (tss . [(0 6 0) ((auto-complete (1 4 0)) (json-mode (1 1 0)) (log4e (0 2 0)) (yaxception (0 1))) "provide a interface for auto-complete.el/flymake.el on typescript-mode." tar ((:url . "https://github.com/aki2o/emacs-tss") (:keywords "typescript" "completion")) "melpa-stable"])
  (typed-clojure-mode . [(1 0 0) ((clojure-mode (2 1 1)) (cider (0 5 0))) "Typed Clojure minor mode for Emacs" single ((:url . "https://github.com/typedclojure/typed-clojure-mode")) "melpa-stable"])
  (ubuntu-theme . [(0 2) nil "A color theme for Emacs." single ((:url . "http://github.com/rocher/ubuntu-theme")) "melpa-stable"])
  (vagrant . [(0 5 2) nil "Manage a vagrant box from emacs" single ((:url . "https://github.com/ottbot/vagrant.el") (:keywords "vagrant" "chef")) "melpa-stable"])
  (vbasense . [(0 1 1) ((auto-complete (1 4 0)) (log4e (0 2 0)) (yaxception (0 1))) "provide a environment like Visual Basic Editor." tar ((:url . "https://github.com/aki2o/emacs-vbasense") (:keywords "vba" "completion")) "melpa-stable"])
  (visual-fill-column . [(1 4) ((emacs (24 3))) "fill-column for visual-line-mode" single nil "melpa-stable"])
  (whole-line-or-region . [(1 3 1) nil "operate on current line if region undefined" single ((:keywords "kill" "yank" "cut" "copy" "paste" "whole" "lines")) "melpa-stable"])
  (wn-mode . [(1 4) ((emacs (24))) "numeric window switching shortcuts" single ((:url . "https://github.com/luismbo/wn-mode") (:keywords "buffers" "windows" "switching-windows")) "melpa-stable"])
  (wsd-mode . [(0 3 0) nil "Emacs major-mode for www.websequencediagrams.com" tar ((:url . "https://github.com/josteink/wsd-mode") (:keywords "wsd" "diagrams" "design" "process" "modelling" "uml")) "melpa-stable"])
  (xtest . [(1 1 0) ((cl-lib (0 5))) "Simple Testing with Emacs & ERT" single ((:url . "https://github.com/promethial/xtest") (:keywords "testing" "ert")) "melpa-stable"])
  (yaml-mode . [(0 0 11) nil "Major mode for editing YAML files" single ((:keywords "data" "yaml")) "melpa-stable"])
  (yaxception . [(0 3 3) nil "Provide framework about exception like Java for Elisp" single ((:url . "https://github.com/aki2o/yaxception") (:keywords "exception" "error" "signal")) "melpa-stable"])
  (ycmd . [(0 9) ((emacs (24)) (f (0 17 1)) (dash (1 2 0)) (deferred (0 3 2)) (popup (0 5 0))) "emacs bindings to the ycmd completion server" tar ((:url . "https://github.com/abingham/emacs-ycmd")) "melpa-stable"])
 )
