'(
  (yasnippet . [(0 8 0) nil "A template system for Emacs" tar "gnu"])
  (xclip . [(1 0) nil "Emacs Interface to XClip" single "gnu"])
  (windresize . [(0 1) nil "Resize windows interactively" single "gnu"])
  (vlf . [(0 9) nil "View Large Files" single "gnu"])
  (uni-confusables . [(0 1) nil "Unicode confusables table" tar "gnu"])
  (undo-tree . [(0 6 3) nil "Treat undo history as a tree" single "gnu"])
  (trie . [(0 2 6) ((tNFA (0 1 1)) (heap (0 3))) "Trie data structure" single "gnu"])
  (tNFA . [(0 1 1) ((queue (0 1))) "Tagged non-deterministic finite-state automata" single "gnu"])
  (svg-clock . [(0 5) nil "Analog clock using Scalable Vector Graphics" single "gnu"])
  (sokoban . [(1 0 4) nil "Sokoban game for emacs" tar "gnu"])
  (sml-mode . [(6 4) nil "Major mode for editing (Standard) ML" single "gnu"])
  (smart-operator . [(4 0) nil "Insert operators with surrounding spaces smartly" single "gnu"])
  (sisu-mode . [(3 0 3) nil "Major mode for SiSU markup text" single "gnu"])
  (shen-mode . [(0 1) nil "Utilities for working with Shen code." tar "gnu"])
  (register-list . [(0 1) nil "Interactively list/edit registers" single "gnu"])
  (rainbow-mode . [(0 8) nil "Colorize color names in buffers" single "gnu"])
  (queue . [(0 1) nil "Queue data structure" single "gnu"])
  (quarter-plane . [(0 1) nil "Minor mode for quarter-plane style editing" single "gnu"])
  (org . [(20130729) nil "Outline-based notes management and organizer" tar "gnu"])
  (adaptive-wrap . [(0 5) nil "Smart line-wrapping with wrap-prefix" single "gnu"])
 )
