'(
  (yasnippet . [(0 8 0) nil "A template system for Emacs" tar "gnu"])
  (xclip . [(1 0) nil "Emacs Interface to XClip" single "gnu"])
  (windresize . [(0 1) nil "Resize windows interactively" single "gnu"])
  (vlf . [(0 9 1) nil "View Large Files" single "gnu"])
  (rainbow-mode . [(0 9) nil "Colorize color names in buffers" single "gnu"])
  (org . [(20130819) nil "Outline-based notes management and organizer" tar "gnu"])
  (js2-mode . [(20130619) ((emacs (24 1))) "Improved JavaScript editing mode" tar "gnu"])
  (ggtags . [(0 6 7) nil "GNU Global source code tagging system" single "gnu"])
  (adaptive-wrap . [(0 5) nil "Smart line-wrapping with wrap-prefix" single "gnu"])
  (ack . [(1 3) nil "Interface to ack-like source code search tools" tar "gnu"])
 )
