'(
  (yasnippet . [(0 8 0) nil "Yet another snippet extension for Emacs." tar "gnu"])
  (xclip . [(1 3) nil "use xclip to copy&paste" single "gnu"])
  (vlf . [(0 9 1) nil "View Large Files" single "gnu"])
  (shen-mode . [(0 1) nil "A major mode for editing shen source code" tar "gnu"])
  (rainbow-mode . [(0 9) nil "Colorize color names in buffers" single "gnu"])
  (org . [(20130923) nil "Outline-based notes management and organizer" tar "gnu"])
  (notes-mode . [(1 30) nil "Indexing system for on-line note-taking" tar "gnu"])
  (muse . [(3 20) nil "Authoring and publishing tool for Emacs" tar "gnu"])
  (js2-mode . [(20130619) ((emacs (24 1))) "Improved JavaScript editing mode" tar "gnu"])
  (ggtags . [(0 6 7) nil "GNU Global source code tagging system" single "gnu"])
  (coffee-mode . [(0 4 1) nil "Major mode for CoffeeScript files" single "gnu"])
  (auctex . [(11 87) nil "Integrated environment for *TeX*" tar "gnu"])
  (adaptive-wrap . [(0 5) nil "Smart line-wrapping with wrap-prefix" single "gnu"])
  (ack . [(1 3) nil "Interface to ack-like source code search tools" tar "gnu"])
 )
