'(
  (wpuzzle [cl-struct-package-desc wpuzzle (1 1) "find as many word in a given time" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/wpuzzle.html") (:keywords quote nil)) nil])
  (wisi [cl-struct-package-desc wisi (1 0) "Utilities for implementing an indentation/navigation engine using a generalized LALR parser" ((cl-lib (0))) tar "gnu" nil ((:keywords quote nil) (:url . "http://stephe-leake.org/emacs/ada-mode/emacs-ada-mode.html")) nil])
  (websocket [cl-struct-package-desc websocket (1 1) "Emacs WebSocket client and server" nil tar "gnu" nil ((:keywords quote ("communication" "websocket" "server")) (:url . "http://elpa.gnu.org/packages/websocket.html")) nil])
  (w3 [cl-struct-package-desc w3 (4 0 49) "Fully customizable, largely undocumented web browser for Emacs" nil tar "gnu" nil ((:keywords quote ("faces" "help" "comm" "news" "mail" "processes" "mouse" "hypermedia")) (:url . "http://elpa.gnu.org/packages/w3.html")) nil])
  (temp-buffer-browse [cl-struct-package-desc temp-buffer-browse (1 2) "temp buffer browse mode" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/temp-buffer-browse.html") (:keywords quote ("convenience"))) nil])
  (gnugo [cl-struct-package-desc gnugo (2 3 1) "play GNU Go in a buffer" nil tar "gnu" nil ((:keywords quote nil) (:url . "http://elpa.gnu.org/packages/gnugo.html")) nil])
  (flylisp [cl-struct-package-desc flylisp (0 2) "Color unbalanced parentheses and parentheses inconsistent with indentation" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/flylisp.html") (:keywords quote nil)) nil])
  (dismal [cl-struct-package-desc dismal (1 5) "Dis Mode Ain't Lotus: Spreadsheet program Emacs" ((cl-lib (0))) tar "gnu" nil ((:keywords quote nil) (:url . "http://elpa.gnu.org/packages/dismal.html")) nil])
  (diff-hl [cl-struct-package-desc diff-hl (1 5 3) "Highlight uncommitted changes" ((cl-lib (0 2))) tar "gnu" nil ((:keywords quote ("vc" "diff")) (:url . "https://github.com/dgutov/diff-hl")) nil])
  (ascii-art-to-unicode [cl-struct-package-desc ascii-art-to-unicode (1 4) "a small artist adjunct" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/ascii-art-to-unicode.html") (:keywords quote nil)) nil])
  (adjust-parens [cl-struct-package-desc adjust-parens (3 0) "Indent and dedent Lisp code, automatically adjust close parens" nil tar "gnu" nil ((:keywords quote nil) (:url . "http://elpa.gnu.org/packages/adjust-parens.html")) nil])
  (ada-mode [cl-struct-package-desc ada-mode (5 0 1) "major-mode for editing Ada sources" ((wisi (1 0))) tar "gnu" nil ((:keywords quote nil) (:url . "http://stephe-leake.org/emacs/ada-mode/emacs-ada-mode.html")) nil])
 )
