'(
  (ztree [cl-struct-package-desc ztree (1 0 2) "Text mode directory tree" nil tar "gnu" nil ((:keywords "files" "tools") (:url . "https://github.com/fourier/ztree")) nil])
  (yasnippet [cl-struct-package-desc yasnippet (0 8 0) "Yet another snippet extension for Emacs." nil tar "gnu" nil ((:keywords "convenience" "emulation") (:url . "http://github.com/capitaomorte/yasnippet")) nil])
  (xclip [cl-struct-package-desc xclip (1 3) "use xclip to copy&paste" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/xclip.html") (:keywords "convenience" "tools")) nil])
  (windresize [cl-struct-package-desc windresize (0 1) "Resize windows interactively" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/windresize.html") (:keywords "window")) nil])
  (vlf [cl-struct-package-desc vlf (1 7) "View Large Files" nil tar "gnu" nil ((:keywords "large files" "utilities") (:url . "https://github.com/m00natic/vlfi")) nil])
  (uni-confusables [cl-struct-package-desc uni-confusables (0 1) "Unicode confusables table" nil tar "gnu" nil ((:url . "http://elpa.gnu.org/packages/uni-confusables.html")) nil])
  (undo-tree [cl-struct-package-desc undo-tree (0 6 5) "Treat undo history as a tree" nil single "gnu" nil ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords "convenience" "files" "undo" "redo" "history" "tree")) nil])
  (trie [cl-struct-package-desc trie (0 2 6) "Trie data structure" ((tNFA (0 1 1)) (heap (0 3))) single "gnu" nil ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords "extensions" "matching" "data structures trie" "ternary search tree" "tree" "completion" "regexp")) nil])
  (tNFA [cl-struct-package-desc tNFA (0 1 1) "Tagged non-deterministic finite-state automata" ((queue (0 1))) single "gnu" nil ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords "extensions" "matching" "data structures tnfa" "nfa" "dfa" "finite state automata" "automata" "regexp")) nil])
  (svg-clock [cl-struct-package-desc svg-clock (0 5) "Analog clock using Scalable Vector Graphics" ((svg (0 1)) (emacs (25 0))) single "gnu" nil ((:url . "http://elpa.gnu.org/packages/svg-clock.html") (:keywords "demo" "svg" "clock")) nil])
  (sokoban [cl-struct-package-desc sokoban (1 4) "Implementation of Sokoban for Emacs." nil tar "gnu" nil ((:keywords "games") (:url . "http://elpa.gnu.org/packages/sokoban.html")) nil])
  (sml-mode [cl-struct-package-desc sml-mode (6 7) "Major mode for editing (Standard) ML" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/sml-mode.html") (:keywords "sml")) nil])
  (sisu-mode [cl-struct-package-desc sisu-mode (3 0 3) "Major mode for SiSU markup text" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/sisu-mode.html") (:keywords "text" "processes" "tools")) nil])
  (shen-mode [cl-struct-package-desc shen-mode (0 1) "A major mode for editing shen source code" nil tar "gnu" nil ((:keywords "languages" "shen") (:url . "http://elpa.gnu.org/packages/shen-mode.html")) nil])
  (register-list [cl-struct-package-desc register-list (0 1) "Interactively list/edit registers" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/register-list.html") (:keywords "register")) nil])
  (rainbow-mode [cl-struct-package-desc rainbow-mode (0 12) "Colorize color names in buffers" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/rainbow-mode.html") (:keywords "faces")) nil])
  (queue [cl-struct-package-desc queue (0 1 1) "Queue data structure" nil single "gnu" nil ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords "extensions" "data structures" "queue")) nil])
  (quarter-plane [cl-struct-package-desc quarter-plane (0 1) "Minor mode for quarter-plane style editing" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/quarter-plane.html") (:keywords "convenience" "wp")) nil])
  (org [cl-struct-package-desc org (20151005) "Outline-based notes management and organizer" nil tar "gnu" nil nil nil])
  (omn-mode [cl-struct-package-desc omn-mode (1 2) "Support for OWL Manchester Notation" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/omn-mode.html") (:keywords)) nil])
  (oauth2 [cl-struct-package-desc oauth2 (0 10) "OAuth 2.0 Authorization Protocol" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/oauth2.html") (:keywords "comm")) nil])
  (num3-mode [cl-struct-package-desc num3-mode (1 2) "highlight groups of digits in long numbers" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/num3-mode.html") (:keywords "faces" "minor-mode")) nil])
  (notes-mode [cl-struct-package-desc notes-mode (1 30) "Indexing system for on-line note-taking" nil tar "gnu" nil ((:url . "http://elpa.gnu.org/packages/notes-mode.html")) nil])
  (nlinum [cl-struct-package-desc nlinum (1 6) "Show line numbers in the margin" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/nlinum.html") (:keywords "convenience")) nil])
  (nhexl-mode [cl-struct-package-desc nhexl-mode (0 1) "Minor mode to edit files via hex-dump format" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/nhexl-mode.html") (:keywords "data")) nil])
  (muse [cl-struct-package-desc muse (3 20) "Authoring and publishing tool for Emacs" nil tar "gnu" nil ((:keywords "hypermedia") (:url . "http://mwolson.org/projects/EmacsMuse.html")) nil])
  (minimap [cl-struct-package-desc minimap (1 2) "Sidebar showing a \"mini-map\" of a buffer" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/minimap.html") (:keywords)) nil])
  (memory-usage [cl-struct-package-desc memory-usage (0 2) "Analyze the memory usage of Emacs in various ways" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/memory-usage.html") (:keywords "maint")) nil])
  (markchars [cl-struct-package-desc markchars (0 2 0) "Mark chars fitting certain characteristics" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/markchars.html") (:keywords)) nil])
  (load-dir [cl-struct-package-desc load-dir (0 0 3) "Load all Emacs Lisp files in a given directory" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/load-dir.html") (:keywords "lisp" "files" "convenience")) nil])
  (lmc [cl-struct-package-desc lmc (1 3) "Little Man Computer in Elisp" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/lmc.html") (:keywords)) nil])
  (lex [cl-struct-package-desc lex (1 1) "Lexical analyser construction" nil tar "gnu" nil ((:url . "http://elpa.gnu.org/packages/lex.html")) nil])
  (jumpc [cl-struct-package-desc jumpc (3 0) "jump to previous insertion points" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/jumpc.html") (:keywords)) nil])
  (js2-mode [cl-struct-package-desc js2-mode (20150909) "Improved JavaScript editing mode" ((emacs (24 1)) (cl-lib (0 5))) tar "gnu" nil ((:keywords "languages" "javascript") (:url . "https://github.com/mooz/js2-mode/")) nil])
  (jgraph-mode [cl-struct-package-desc jgraph-mode (1 1) "Major mode for Jgraph files" ((cl-lib (0 5))) single "gnu" nil ((:url . "http://elpa.gnu.org/packages/jgraph-mode.html") (:keywords "tex" "wp")) nil])
  (ioccur [cl-struct-package-desc ioccur (2 4) "Incremental occur" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/ioccur.html") (:keywords)) nil])
  (heap [cl-struct-package-desc heap (0 3) "Heap (a.k.a. priority queue) data structure" nil single "gnu" nil ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords "extensions" "data structures" "heap" "priority queue")) nil])
  (ggtags [cl-struct-package-desc ggtags (0 8 10) "emacs frontend to GNU Global source code tagging system" ((emacs (24)) (cl-lib (0 5))) single "gnu" nil ((:url . "https://github.com/leoliu/ggtags") (:keywords "tools" "convenience")) nil])
  (f90-interface-browser [cl-struct-package-desc f90-interface-browser (1 1) "Parse and browse f90 interfaces" nil single "gnu" nil ((:url . "http://github.com/wence-/f90-iface/") (:keywords)) nil])
  (epoch-view [cl-struct-package-desc epoch-view (0 0 1) "Minor mode to visualize epoch timestamps" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/epoch-view.html") (:keywords "data" "timestamp" "epoch" "unix")) nil])
  (enwc [cl-struct-package-desc enwc (1 0) "The Emacs Network Client" nil tar "gnu" nil ((:keywords "enwc" "network" "wicd" "manager" "nm") (:url . "http://elpa.gnu.org/packages/enwc.html")) nil])
  (eldoc-eval [cl-struct-package-desc eldoc-eval (0 1) "Enable eldoc support when minibuffer is in use." nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/eldoc-eval.html") (:keywords)) nil])
  (ediprolog [cl-struct-package-desc ediprolog (1 1) "Emacs Does Interactive Prolog" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/ediprolog.html") (:keywords "languages" "processes")) nil])
  (docbook [cl-struct-package-desc docbook (0 1) "Info-like viewer for DocBook" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/docbook.html") (:keywords "docs" "help")) nil])
  (djvu [cl-struct-package-desc djvu (0 5) "Edit and view Djvu files via djvused" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/djvu.html") (:keywords "files" "wp")) nil])
  (dict-tree [cl-struct-package-desc dict-tree (0 12 8) "Dictionary data structure" ((trie (0 2 5)) (tNFA (0 1 1)) (heap (0 3))) single "gnu" nil ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords "extensions" "matching" "data structures trie" "tree" "dictionary" "completion" "regexp")) nil])
  (debbugs [cl-struct-package-desc debbugs (0 7) "SOAP library to access debbugs servers" nil tar "gnu" nil ((:keywords "comm" "hypermedia") (:url . "http://elpa.gnu.org/packages/debbugs.html")) nil])
  (csv-mode [cl-struct-package-desc csv-mode (1 5) "Major mode for editing comma/char separated values" nil single "gnu" nil ((:url . "http://centaur.maths.qmul.ac.uk/Emacs/") (:keywords "convenience")) nil])
  (company [cl-struct-package-desc company (0 8 12) "Modular text completion framework" ((emacs (24 1)) (cl-lib (0 5))) tar "gnu" nil ((:keywords "abbrev" "convenience" "matching") (:url . "http://company-mode.github.io/")) nil])
  (coffee-mode [cl-struct-package-desc coffee-mode (0 4 1 1) "Major mode for CoffeeScript files" nil single "gnu" nil ((:url . "http://github.com/defunkt/coffee-mode") (:keywords "coffeescript" "major" "mode")) nil])
  (cl-lib [cl-struct-package-desc cl-lib (0 5) "Properly prefixed CL functions and macros" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/cl-lib.html") (:keywords)) nil])
  (auctex [cl-struct-package-desc auctex (11 88 8) "Integrated environment for *TeX*" nil tar "gnu" nil ((:url . "http://www.gnu.org/software/auctex/")) nil])
  (all [cl-struct-package-desc all (1 0) "Edit all lines matching a given regexp" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/all.html") (:keywords "matching")) nil])
  (adaptive-wrap [cl-struct-package-desc adaptive-wrap (0 5) "Smart line-wrapping with wrap-prefix" nil single "gnu" nil ((:url . "http://elpa.gnu.org/packages/adaptive-wrap.html") (:keywords)) nil])
  (ack [cl-struct-package-desc ack (1 5) "interface to ack-like tools" nil tar "gnu" nil ((:keywords "tools" "processes" "convenience") (:url . "https://github.com/leoliu/ack-el")) nil])
 )
