'(
  (yasnippet . [(0 8 0) nil "Yet another snippet extension for Emacs." tar ((:keywords quote ("convenience" "emulation")) (:url . "http://github.com/capitaomorte/yasnippet")) "gnu"])
  (xclip . [(1 3) nil "use xclip to copy&paste" single ((:url . "http://elpa.gnu.org/packages/xclip.html") (:keywords quote ("convenience" "tools"))) "gnu"])
  (windresize . [(0 1) nil "Resize windows interactively" single ((:url . "http://elpa.gnu.org/packages/windresize.html") (:keywords quote ("window"))) "gnu"])
  (vlf . [(1 4) nil "View Large Files" tar ((:keywords quote ("large files" "utilities")) (:url . "https://github.com/m00natic/vlfi")) "gnu"])
  (uni-confusables . [(0 1) nil "Unicode confusables table" tar ((:keywords quote nil) (:url . "http://elpa.gnu.org/packages/uni-confusables.html")) "gnu"])
  (undo-tree . [(0 6 5) nil "Treat undo history as a tree" single ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords quote ("convenience" "files" "undo" "redo" "history" "tree"))) "gnu"])
  (trie . [(0 2 6) ((tNFA (0 1 1)) (heap (0 3))) "Trie data structure" single ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords quote ("extensions" "matching" "data structures trie" "ternary search tree" "tree" "completion" "regexp"))) "gnu"])
  (tNFA . [(0 1 1) ((queue (0 1))) "Tagged non-deterministic finite-state automata" single ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords quote ("extensions" "matching" "data structures tnfa" "nfa" "dfa" "finite state automata" "automata" "regexp"))) "gnu"])
  (svg-clock . [(0 5) nil "Analog clock using Scalable Vector Graphics" single ((:url . "http://elpa.gnu.org/packages/svg-clock.html") (:keywords quote ("demo" "svg" "clock"))) "gnu"])
  (sokoban . [(1 4) nil "Implementation of Sokoban for Emacs." tar ((:keywords quote ("games")) (:url . "http://elpa.gnu.org/packages/sokoban.html")) "gnu"])
  (sml-mode . [(6 4) nil "Major mode for editing (Standard) ML" single ((:url . "http://elpa.gnu.org/packages/sml-mode.html") (:keywords quote ("sml"))) "gnu"])
  (smart-operator . [(4 0) nil "Insert operators with surrounding spaces smartly" single ((:url . "http://xwl.appspot.com/ref/smart-operator.el") (:keywords quote nil)) "gnu"])
  (sisu-mode . [(3 0 3) nil "Major mode for SiSU markup text" single ((:url . "http://elpa.gnu.org/packages/sisu-mode.html") (:keywords quote ("text" "processes" "tools"))) "gnu"])
  (shen-mode . [(0 1) nil "A major mode for editing shen source code" tar ((:keywords quote ("languages" "shen")) (:url . "http://elpa.gnu.org/packages/shen-mode.html")) "gnu"])
  (register-list . [(0 1) nil "Interactively list/edit registers" single ((:url . "http://elpa.gnu.org/packages/register-list.html") (:keywords quote ("register"))) "gnu"])
  (rainbow-mode . [(0 9) nil "Colorize color names in buffers" single ((:url . "http://elpa.gnu.org/packages/rainbow-mode.html") (:keywords quote ("faces"))) "gnu"])
  (queue . [(0 1) nil "Queue data structure" single ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords quote ("extensions" "data structures" "queue"))) "gnu"])
  (quarter-plane . [(0 1) nil "Minor mode for quarter-plane style editing" single ((:url . "http://elpa.gnu.org/packages/quarter-plane.html") (:keywords quote ("convenience" "wp"))) "gnu"])
  (org . [(20140130) nil "Outline-based notes management and organizer" tar nil "gnu"])
  (omn-mode . [(1 0) nil "Support for OWL Manchester Notation" single ((:url . "http://elpa.gnu.org/packages/omn-mode.html") (:keywords quote nil)) "gnu"])
  (oauth2 . [(0 10) nil "OAuth 2.0 Authorization Protocol" single ((:url . "http://elpa.gnu.org/packages/oauth2.html") (:keywords quote ("comm"))) "gnu"])
  (num3-mode . [(1 1) nil "highlight groups of digits in long numbers" single ((:url . "http://elpa.gnu.org/packages/num3-mode.html") (:keywords quote nil)) "gnu"])
  (notes-mode . [(1 30) nil "Indexing system for on-line note-taking" tar ((:keywords quote nil) (:url . "http://elpa.gnu.org/packages/notes-mode.html")) "gnu"])
  (nlinum . [(1 2) nil "Show line numbers in the margin" single ((:url . "http://elpa.gnu.org/packages/nlinum.html") (:keywords quote ("convenience"))) "gnu"])
  (nhexl-mode . [(0 1) nil "Minor mode to edit files via hex-dump format" single ((:url . "http://elpa.gnu.org/packages/nhexl-mode.html") (:keywords quote ("data"))) "gnu"])
  (muse . [(3 20) nil "Authoring and publishing tool for Emacs" tar ((:keywords quote ("hypermedia")) (:url . "http://mwolson.org/projects/EmacsMuse.html")) "gnu"])
  (minimap . [(1 0) nil "Sidebar showing a \"mini-map\" of a buffer" single ((:url . "http://elpa.gnu.org/packages/minimap.html") (:keywords quote nil)) "gnu"])
  (memory-usage . [(0 2) nil "Analyze the memory usage of Emacs in various ways" single ((:url . "http://elpa.gnu.org/packages/memory-usage.html") (:keywords quote ("maint"))) "gnu"])
  (markchars . [(0 2 0) nil "Mark chars fitting certain characteristics" single ((:url . "http://elpa.gnu.org/packages/markchars.html") (:keywords quote nil)) "gnu"])
  (load-dir . [(0 0 3) nil "Load all Emacs Lisp files in a given directory" single ((:url . "http://elpa.gnu.org/packages/load-dir.html") (:keywords quote ("lisp" "files" "convenience"))) "gnu"])
  (lmc . [(1 3) nil "Little Man Computer in Elisp" single ((:url . "http://elpa.gnu.org/packages/lmc.html") (:keywords quote nil)) "gnu"])
  (lex . [(1 1) nil "Lexical analyser construction" tar ((:keywords quote nil) (:url . "http://elpa.gnu.org/packages/lex.html")) "gnu"])
  (jumpc . [(3 0) nil "jump to previous insertion points" single ((:url . "http://elpa.gnu.org/packages/jumpc.html") (:keywords quote nil)) "gnu"])
  (js2-mode . [(20140114) ((emacs (24 1))) "Improved JavaScript editing mode" tar ((:keywords quote ("languages" "javascript")) (:url . "https://github.com/mooz/js2-mode/")) "gnu"])
  (jgraph-mode . [(1 0) nil "Major mode for Jgraph files" single ((:url . "http://elpa.gnu.org/packages/jgraph-mode.html") (:keywords quote ("tex" "wp"))) "gnu"])
  (ioccur . [(2 4) nil "Incremental occur" single ((:url . "http://elpa.gnu.org/packages/ioccur.html") (:keywords quote nil)) "gnu"])
  (heap . [(0 3) nil "Heap (a.k.a. priority queue) data structure" single ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords quote ("extensions" "data structures" "heap" "priority queue"))) "gnu"])
  (ggtags . [(0 7 8) ((emacs (24))) "emacs frontend to GNU Global source code tagging system" single ((:url . "https://github.com/leoliu/ggtags") (:keywords quote ("tools" "convenience"))) "gnu"])
  (f90-interface-browser . [(1 1) nil "Parse and browse f90 interfaces" single ((:url . "http://github.com/wence-/f90-iface/") (:keywords quote nil)) "gnu"])
  (epoch-view . [(0 0 1) nil "Minor mode to visualize epoch timestamps" single ((:url . "http://elpa.gnu.org/packages/epoch-view.html") (:keywords quote ("data" "timestamp" "epoch" "unix"))) "gnu"])
  (enwc . [(1 0) nil "The Emacs Network Client" tar ((:keywords quote ("enwc" "network" "wicd" "manager" "nm")) (:url . "http://elpa.gnu.org/packages/enwc.html")) "gnu"])
  (eldoc-eval . [(0 1) nil "Enable eldoc support when minibuffer is in use." single ((:url . "http://elpa.gnu.org/packages/eldoc-eval.html") (:keywords quote nil)) "gnu"])
  (ediprolog . [(1 0) nil "Emacs Does Interactive Prolog" single ((:url . "http://elpa.gnu.org/packages/ediprolog.html") (:keywords quote ("languages" "processes"))) "gnu"])
  (docbook . [(0 1) nil "Info-like viewer for DocBook" single ((:url . "http://elpa.gnu.org/packages/docbook.html") (:keywords quote ("docs" "help"))) "gnu"])
  (djvu . [(0 5) nil "Edit and view Djvu files via djvused" single ((:url . "http://elpa.gnu.org/packages/djvu.html") (:keywords quote ("files" "wp"))) "gnu"])
  (dict-tree . [(0 12 8) ((trie (0 2 5)) (tNFA (0 1 1)) (heap (0 3))) "Dictionary data structure" single ((:url . "http://www.dr-qubit.org/emacs.php") (:keywords quote ("extensions" "matching" "data structures trie" "tree" "dictionary" "completion" "regexp"))) "gnu"])
  (debbugs . [(0 6) nil "SOAP library to access debbugs servers" tar ((:keywords quote ("comm" "hypermedia")) (:url . "http://elpa.gnu.org/packages/debbugs.html")) "gnu"])
  (csv-mode . [(1 2) nil "Major mode for editing comma/char separated values" single ((:url . "http://centaur.maths.qmul.ac.uk/Emacs/") (:keywords quote ("convenience"))) "gnu"])
  (company . [(0 6 14) nil "Modular in-buffer completion framework" tar ((:keywords quote ("abbrev" "convenience" "matching")) (:url . "http://company-mode.github.io/")) "gnu"])
  (coffee-mode . [(0 4 1 1) nil "Major mode for CoffeeScript files" single ((:url . "http://github.com/defunkt/coffee-mode") (:keywords quote ("coffeescript" "major" "mode"))) "gnu"])
  (cl-lib . [(0 4) nil "Properly prefixed CL functions and macros" single ((:url . "http://elpa.gnu.org/packages/cl-lib.html") (:keywords quote nil)) "gnu"])
  (auctex . [(11 87 2) nil "Integrated environment for *TeX*" tar ((:keywords quote nil) (:url . "http://www.gnu.org/software/auctex/")) "gnu"])
  (all . [(1 0) nil "Edit all lines matching a given regexp" single ((:url . "http://elpa.gnu.org/packages/all.html") (:keywords quote ("matching"))) "gnu"])
  (adaptive-wrap . [(0 5) nil "Smart line-wrapping with wrap-prefix" single ((:url . "http://elpa.gnu.org/packages/adaptive-wrap.html") (:keywords quote nil)) "gnu"])
  (ack . [(1 3) nil "Interface to ack-like source code search tools" tar ((:keywords quote ("tools" "processes" "convenience")) (:url . "https://github.com/leoliu/ack-el")) "gnu"])
 )
